vocabData["chaihong"] = {
    title: "차이홍 단어(주황)",
    words: [
        // --- 1. 인사 / 대명사 ---
        { id: 1, category: "1. 인사 / 대명사", zh: "你好", py: "nǐ hǎo", mean: "안녕" },
        { id: 2, category: "1. 인사 / 대명사", zh: "初次见面", py: "chūcì jiànmiàn", mean: "처음 뵙겠습니다" },
        { id: 3, category: "1. 인사 / 대명사", zh: "我们", py: "wǒmen", mean: "우리" },
        { id: 4, category: "1. 인사 / 대명사", zh: "你们", py: "nǐmen", mean: "너희들" },
        { id: 5, category: "1. 인사 / 대명사", zh: "他", py: "tā", mean: "그" },
        { id: 6, category: "1. 인사 / 대명사", zh: "她", py: "tā", mean: "그녀" },
        { id: 7, category: "1. 인사 / 대명사", zh: "它", py: "tā", mean: "그것 (사물/동물)" },
        { id: 8, category: "1. 인사 / 대명사", zh: "晚安", py: "wǎn'ān", mean: "안녕히 주무세요" },
        { id: 9, category: "1. 인사 / 대명사", zh: "再见", py: "zàijiàn", mean: "안녕히 가세요" },
        { id: 10, category: "1. 인사 / 대명사", zh: "慢走", py: "màn zǒu", mean: "조심히 가세요" },
        { id: 11, category: "1. 인사 / 대명사", zh: "明天见", py: "míngtiān jiàn", mean: "내일 봐요" },
        { id: 12, category: "1. 인사 / 대명사", zh: "贵姓", py: "guìxìng", mean: "성함이 어떻게 되십니까" },
        { id: 13, category: "1. 인사 / 대명사", zh: "叫", py: "jiào", mean: "~라고 부르다" },
        { id: 14, category: "1. 인사 / 대명사", zh: "什么", py: "shénme", mean: "무엇" },
        { id: 15, category: "1. 인사 / 대명사", zh: "名字", py: "míngzi", mean: "이름" },
        { id: 16, category: "1. 인사 / 대명사", zh: "认识", py: "rènshi", mean: "알다" },
        { id: 17, category: "1. 인사 / 대명사", zh: "多多关照", py: "duōduō guānzhào", mean: "잘 부탁드립니다" },
        { id: 18, category: "1. 인사 / 대명사", zh: "这", py: "zhè", mean: "이것" },
        { id: 19, category: "1. 인사 / 대명사", zh: "这儿", py: "zhèr", mean: "여기" },
        { id: 20, category: "1. 인사 / 대명사", zh: "那", py: "nà", mean: "저것" },
        { id: 21, category: "1. 인사 / 대명사", zh: "谁", py: "shéi", mean: "누구" },
        { id: 22, category: "1. 인사 / 대명사", zh: "哪", py: "nǎ", mean: "어느" },
        { id: 23, category: "1. 인사 / 대명사", zh: "哪儿", py: "nǎr", mean: "어디" },
        { id: 24, category: "1. 인사 / 대명사", zh: "先生", py: "xiānsheng", mean: "선생님, 미스터" },
        { id: 25, category: "1. 인사 / 대명사", zh: "怎么", py: "zěnme", mean: "어떻게, 왜" },

        // --- 2. 사물 / 전자기기 ---
        { id: 26, category: "2. 사물 / 전자기기", zh: "电话", py: "diànhuà", mean: "전화" },
        { id: 27, category: "2. 사물 / 전자기기", zh: "电脑", py: "diànnǎo", mean: "컴퓨터" },
        { id: 28, category: "2. 사물 / 전자기기", zh: "笔记本电脑", py: "bǐjìběn diànnǎo", mean: "노트북" },
        { id: 29, category: "2. 사물 / 전자기기", zh: "平板电脑", py: "píngbǎn diànnǎo", mean: "태블릿 PC" },
        { id: 30, category: "2. 사물 / 전자기기", zh: "手机", py: "shǒujī", mean: "휴대폰" },
        { id: 31, category: "2. 사물 / 전자기기", zh: "充电器", py: "chōngdiànqì", mean: "충전기" },
        { id: 32, category: "2. 사물 / 전자기기", zh: "耳机", py: "ěrjī", mean: "이어폰" },
        { id: 33, category: "2. 사물 / 전자기기", zh: "电视", py: "diànshì", mean: "TV" },
        { id: 34, category: "2. 사물 / 전자기기", zh: "空调", py: "kōngtiáo", mean: "에어컨" },
        { id: 35, category: "2. 사물 / 전자기기", zh: "冰箱", py: "bīngxiāng", mean: "냉장고" },
        { id: 36, category: "2. 사물 / 전자기기", zh: "洗衣机", py: "xǐyījī", mean: "세탁기" },
        { id: 37, category: "2. 사물 / 전자기기", zh: "微波炉", py: "wēibōlú", mean: "전자레인지" },
        { id: 38, category: "2. 사물 / 전자기기", zh: "照相机", py: "zhàoxiàngjī", mean: "카메라" },
        { id: 39, category: "2. 사물 / 전자기기", zh: "吹风机", py: "chuīfēngjī", mean: "헤어드라이어" },
        { id: 40, category: "2. 사물 / 전자기기", zh: "打印机", py: "dǎyìnjī", mean: "프린터" },
        { id: 41, category: "2. 사물 / 전자기기", zh: "书", py: "shū", mean: "책" },
        { id: 42, category: "2. 사물 / 전자기기", zh: "桌子", py: "zhuōzi", mean: "책상" },
        { id: 43, category: "2. 사물 / 전자기기", zh: "椅子", py: "yǐzi", mean: "의자" },
        { id: 44, category: "2. 사물 / 전자기기", zh: "铅笔", py: "qiānbǐ", mean: "연필" },
        { id: 45, category: "2. 사물 / 전자기기", zh: "笔", py: "bǐ", mean: "펜" },
        { id: 46, category: "2. 사물 / 전자기기", zh: "书包", py: "shūbāo", mean: "책가방" },
        { id: 47, category: "2. 사물 / 전자기기", zh: "手表", py: "shǒubiǎo", mean: "손목시계" },
        { id: 48, category: "2. 사물 / 전자기기", zh: "钱包", py: "qiánbāo", mean: "지갑" },
        { id: 49, category: "2. 사물 / 전자기기", zh: "手绢", py: "shǒujuàn", mean: "손수건" },
        { id: 50, category: "2. 사물 / 전자기기", zh: "口罩", py: "kǒuzhào", mean: "마스크" },
        { id: 51, category: "2. 사물 / 전자기기", zh: "镜子", py: "jìngzi", mean: "거울" },
        { id: 52, category: "2. 사물 / 전자기기", zh: "梳子", py: "shūzi", mean: "빗" },
        { id: 53, category: "2. 사물 / 전자기기", zh: "名片", py: "míngpiàn", mean: "명함" },
        { id: 54, category: "2. 사물 / 전자기기", zh: "纸巾", py: "zhǐjīn", mean: "휴지" },
        { id: 55, category: "2. 사물 / 전자기기", zh: "雨伞", py: "yǔsǎn", mean: "우산" },
        { id: 56, category: "2. 사물 / 전자기기", zh: "照片", py: "zhàopiàn", mean: "사진" },

        // --- 3. 의류 / 패션 ---
        { id: 57, category: "3. 의류 / 패션", zh: "帽子", py: "màozi", mean: "모자" },
        { id: 58, category: "3. 의류 / 패션", zh: "皮鞋", py: "píxié", mean: "구두" },
        { id: 59, category: "3. 의류 / 패션", zh: "运动鞋", py: "yùndòngxié", mean: "운동화" },
        { id: 60, category: "3. 의류 / 패션", zh: "裤子", py: "kùzi", mean: "바지" },
        { id: 61, category: "3. 의류 / 패션", zh: "牛仔裤", py: "niúzǎikù", mean: "청바지" },
        { id: 62, category: "3. 의류 / 패션", zh: "裙子", py: "qúnzi", mean: "치마" },
        { id: 63, category: "3. 의류 / 패션", zh: "连衣裙", py: "liányīqún", mean: "원피스" },
        { id: 64, category: "3. 의류 / 패션", zh: "大衣", py: "dàyī", mean: "외투, 코트" },
        { id: 65, category: "3. 의류 / 패션", zh: "衬衫", py: "chènshān", mean: "셔츠" },
        { id: 66, category: "3. 의류 / 패션", zh: "袜子", py: "wàzi", mean: "양말" },
        { id: 67, category: "3. 의류 / 패션", zh: "手套", py: "shǒutào", mean: "장갑" },

        // --- 4. 시간 / 날짜 / 날씨 ---
        { id: 68, category: "4. 시간 / 날짜 / 날씨", zh: "时间", py: "shíjiān", mean: "시간" },
        { id: 69, category: "4. 시간 / 날짜 / 날씨", zh: "岁", py: "suì", mean: "살, 세 (나이)" },
        { id: 70, category: "4. 시간 / 날짜 / 날씨", zh: "年纪", py: "niánjì", mean: "연세" },
        { id: 71, category: "4. 시간 / 날짜 / 날씨", zh: "今天", py: "jīntiān", mean: "오늘" },
        { id: 72, category: "4. 시간 / 날짜 / 날씨", zh: "前天", py: "qiántiān", mean: "그제" },
        { id: 73, category: "4. 시간 / 날짜 / 날씨", zh: "昨天", py: "zuótiān", mean: "어제" },
        { id: 74, category: "4. 시간 / 날짜 / 날씨", zh: "明天", py: "míngtiān", mean: "내일" },
        { id: 75, category: "4. 시간 / 날짜 / 날씨", zh: "后天", py: "hòutiān", mean: "모레" },
        { id: 76, category: "4. 시간 / 날짜 / 날씨", zh: "现在", py: "xiànzài", mean: "지금" },
        { id: 77, category: "4. 시간 / 날짜 / 날씨", zh: "早上", py: "zǎoshang", mean: "아침" },
        { id: 78, category: "4. 시간 / 날짜 / 날씨", zh: "上午", py: "shàngwǔ", mean: "오전" },
        { id: 79, category: "4. 시간 / 날짜 / 날씨", zh: "中午", py: "zhōngwǔ", mean: "정오, 점심" },
        { id: 80, category: "4. 시간 / 날짜 / 날씨", zh: "下午", py: "xiàwǔ", mean: "오후" },
        { id: 81, category: "4. 시간 / 날짜 / 날씨", zh: "晚上", py: "wǎnshang", mean: "저녁" },
        { id: 82, category: "4. 시간 / 날짜 / 날씨", zh: "夜晚", py: "yèwǎn", mean: "밤, 야간" },
        { id: 83, category: "4. 시간 / 날짜 / 날씨", zh: "凌晨", py: "língchén", mean: "새벽" },
        { id: 84, category: "4. 시간 / 날짜 / 날씨", zh: "月", py: "yuè", mean: "월, 달" },
        { id: 85, category: "4. 시간 / 날짜 / 날씨", zh: "号", py: "hào", mean: "일(날짜), 번호" },
        { id: 86, category: "4. 시간 / 날짜 / 날씨", zh: "星期", py: "xīngqī", mean: "요일" },
        { id: 87, category: "4. 시간 / 날짜 / 날씨", zh: "星期天", py: "xīngqītiān", mean: "일요일" },
        { id: 88, category: "4. 시간 / 날짜 / 날씨", zh: "周", py: "zhōu", mean: "주" },
        { id: 89, category: "4. 시간 / 날짜 / 날씨", zh: "点", py: "diǎn", mean: "시" },
        { id: 90, category: "4. 시간 / 날짜 / 날씨", zh: "分", py: "fēn", mean: "분" },
        { id: 91, category: "4. 시간 / 날짜 / 날씨", zh: "刻", py: "kè", mean: "15분" },
        { id: 92, category: "4. 시간 / 날짜 / 날씨", zh: "半", py: "bàn", mean: "반, 30분" },
        { id: 93, category: "4. 시간 / 날짜 / 날씨", zh: "差", py: "chà", mean: "~전이다, 부족하다" },
        { id: 94, category: "4. 시간 / 날짜 / 날씨", zh: "天气", py: "tiānqì", mean: "날씨" },
        { id: 95, category: "4. 시간 / 날짜 / 날씨", zh: "暖和", py: "nuǎnhuo", mean: "따뜻하다" },
        { id: 96, category: "4. 시간 / 날짜 / 날씨", zh: "热", py: "rè", mean: "덥다" },
        { id: 97, category: "4. 시간 / 날짜 / 날씨", zh: "冷", py: "lěng", mean: "춥다" },
        { id: 98, category: "4. 시간 / 날짜 / 날씨", zh: "凉快", py: "liángkuai", mean: "시원하다" },
        { id: 99, category: "4. 시간 / 날짜 / 날씨", zh: "干燥", py: "gānzào", mean: "건조하다" },
        { id: 100, category: "4. 시간 / 날짜 / 날씨", zh: "晴", py: "qíng", mean: "맑다" },
        { id: 101, category: "4. 시간 / 날짜 / 날씨", zh: "阴", py: "yīn", mean: "흐리다" },
        { id: 102, category: "4. 시간 / 날짜 / 날씨", zh: "多云", py: "duōyún", mean: "구름이 많다" },
        { id: 103, category: "4. 시간 / 날짜 / 날씨", zh: "下雨", py: "xiàyǔ", mean: "비가 오다" },
        { id: 104, category: "4. 시간 / 날짜 / 날씨", zh: "下雪", py: "xiàxuě", mean: "눈이 오다" },
        { id: 105, category: "4. 시간 / 날짜 / 날씨", zh: "刮风", py: "guāfēng", mean: "바람이 불다" },

        // --- 5. 사람 / 직업 / 가족 ---
        { id: 106, category: "5. 사람 / 직업 / 가족", zh: "老师", py: "lǎoshī", mean: "선생님" },
        { id: 107, category: "5. 사람 / 직업 / 가족", zh: "学生", py: "xuésheng", mean: "학생" },
        { id: 108, category: "5. 사람 / 직업 / 가족", zh: "老板", py: "lǎobǎn", mean: "사장님" },
        { id: 109, category: "5. 사람 / 직업 / 가족", zh: "同事", py: "tóngshì", mean: "동료" },
        { id: 110, category: "5. 사람 / 직업 / 가족", zh: "客户", py: "kèhù", mean: "거래처, 고객" },
        { id: 111, category: "5. 사람 / 직업 / 가족", zh: "顾客", py: "gùkè", mean: "손님" },
        { id: 112, category: "5. 사람 / 직업 / 가족", zh: "朋友", py: "péngyou", mean: "친구" },
        { id: 113, category: "5. 사람 / 직업 / 가족", zh: "同学", py: "tóngxué", mean: "반 친구" },
        { id: 114, category: "5. 사람 / 직업 / 가족", zh: "室友", py: "shìyǒu", mean: "룸메이트" },
        { id: 115, category: "5. 사람 / 직업 / 가족", zh: "同桌", py: "tóngzhuō", mean: "짝꿍" },
        { id: 116, category: "5. 사람 / 직업 / 가족", zh: "邻居", py: "línjū", mean: "이웃" },
        { id: 117, category: "5. 사람 / 직업 / 가족", zh: "房东", py: "fángdōng", mean: "집주인" },
        { id: 118, category: "5. 사람 / 직업 / 가족", zh: "上班族", py: "shàngbānzú", mean: "직장인" },
        { id: 119, category: "5. 사람 / 직업 / 가족", zh: "公务员", py: "gōngwùyuán", mean: "공무원" },
        { id: 120, category: "5. 사람 / 직업 / 가족", zh: "演员", py: "yǎnyuán", mean: "배우" },
        { id: 121, category: "5. 사람 / 직업 / 가족", zh: "歌手", py: "gēshǒu", mean: "가수" },
        { id: 122, category: "5. 사람 / 직업 / 가족", zh: "医生", py: "yīshēng", mean: "의사" },
        { id: 123, category: "5. 사람 / 직업 / 가족", zh: "护士", py: "hùshi", mean: "간호사" },
        { id: 124, category: "5. 사람 / 직업 / 가족", zh: "厨师", py: "chúshī", mean: "요리사" },
        { id: 125, category: "5. 사람 / 직업 / 가족", zh: "警察", py: "jǐngchá", mean: "경찰" },
        { id: 126, category: "5. 사람 / 직업 / 가족", zh: "消防员", py: "xiāofángyuán", mean: "소방관" },
        { id: 127, category: "5. 사람 / 직업 / 가족", zh: "飞行员", py: "fēixíngyuán", mean: "조종사" },
        { id: 128, category: "5. 사람 / 직업 / 가족", zh: "设计师", py: "shèjìshī", mean: "디자이너" },
        { id: 129, category: "5. 사람 / 직업 / 가족", zh: "作家", py: "zuòjiā", mean: "작가" },
        { id: 130, category: "5. 사람 / 직업 / 가족", zh: "播音员", py: "bōyīnyuán", mean: "아나운서" },
        { id: 131, category: "5. 사람 / 직업 / 가족", zh: "推销员", py: "tuīxiāoyuán", mean: "세일즈맨" },
        { id: 132, category: "5. 사람 / 직업 / 가족", zh: "家人", py: "jiārén", mean: "가족" },
        { id: 133, category: "5. 사람 / 직업 / 가족", zh: "亲戚", py: "qīnqi", mean: "친척" },
        { id: 134, category: "5. 사람 / 직업 / 가족", zh: "兄弟姐妹", py: "xiōngdì jiěmèi", mean: "형제자매" },
        { id: 135, category: "5. 사람 / 직업 / 가족", zh: "爷爷", py: "yéye", mean: "할아버지" },
        { id: 136, category: "5. 사람 / 직업 / 가족", zh: "奶奶", py: "nǎinai", mean: "할머니" },
        { id: 137, category: "5. 사람 / 직업 / 가족", zh: "外公", py: "wàigōng", mean: "외할아버지" },
        { id: 138, category: "5. 사람 / 직업 / 가족", zh: "外婆", py: "wàipó", mean: "외할머니" },
        { id: 139, category: "5. 사람 / 직업 / 가족", zh: "爸爸", py: "bàba", mean: "아빠" },
        { id: 140, category: "5. 사람 / 직업 / 가족", zh: "妈妈", py: "māma", mean: "엄마" },
        { id: 141, category: "5. 사람 / 직업 / 가족", zh: "哥哥", py: "gēge", mean: "형, 오빠" },
        { id: 142, category: "5. 사람 / 직업 / 가족", zh: "姐姐", py: "jiějie", mean: "누나, 언니" },
        { id: 143, category: "5. 사람 / 직업 / 가족", zh: "弟弟", py: "dìdi", mean: "남동생" },
        { id: 144, category: "5. 사람 / 직업 / 가족", zh: "妹妹", py: "mèimei", mean: "여동생" },
        { id: 145, category: "5. 사람 / 직업 / 가족", zh: "儿子", py: "érzi", mean: "아들" },
        { id: 146, category: "5. 사람 / 직업 / 가족", zh: "女儿", py: "nǚ'ér", mean: "딸" },
        { id: 147, category: "5. 사람 / 직업 / 가족", zh: "孙子", py: "sūnzi", mean: "손자" },
        { id: 148, category: "5. 사람 / 직업 / 가족", zh: "孙女", py: "sūnnǚ", mean: "손녀" },
        { id: 149, category: "5. 사람 / 직업 / 가족", zh: "丈夫", py: "zhàngfu", mean: "남편" },
        { id: 150, category: "5. 사람 / 직업 / 가족", zh: "妻子", py: "qīzi", mean: "아내" },
        { id: 151, category: "5. 사람 / 직업 / 가족", zh: "孩子", py: "háizi", mean: "아이" },

        // --- 6. 장소 / 교통 / 위치 ---
        { id: 152, category: "6. 장소 / 교통 / 위치", zh: "国", py: "guó", mean: "나라" },
        { id: 153, category: "6. 장소 / 교통 / 위치", zh: "中国", py: "Zhōngguó", mean: "중국" },
        { id: 154, category: "6. 장소 / 교통 / 위치", zh: "美国", py: "Měiguó", mean: "미국" },
        { id: 155, category: "6. 장소 / 교통 / 위치", zh: "日本", py: "Rìběn", mean: "일본" },
        { id: 156, category: "6. 장소 / 교통 / 위치", zh: "北京", py: "Běijīng", mean: "베이징" },
        { id: 157, category: "6. 장소 / 교통 / 위치", zh: "上海", py: "Shànghǎi", mean: "상하이" },
        { id: 158, category: "6. 장소 / 교통 / 위치", zh: "公司", py: "gōngsī", mean: "회사" },
        { id: 159, category: "6. 장소 / 교통 / 위치", zh: "学校", py: "xuéxiào", mean: "학교" },
        { id: 160, category: "6. 장소 / 교통 / 위치", zh: "医院", py: "yīyuàn", mean: "병원" },
        { id: 161, category: "6. 장소 / 교통 / 위치", zh: "银行", py: "yínháng", mean: "은행" },
        { id: 162, category: "6. 장소 / 교통 / 위치", zh: "邮局", py: "yóujú", mean: "우체국" },
        { id: 163, category: "6. 장소 / 교통 / 위치", zh: "商店", py: "shāngdiàn", mean: "상점" },
        { id: 164, category: "6. 장소 / 교통 / 위치", zh: "超市", py: "chāoshì", mean: "슈퍼마켓" },
        { id: 165, category: "6. 장소 / 교통 / 위치", zh: "饭馆", py: "fànguǎn", mean: "식당" },
        { id: 166, category: "6. 장소 / 교통 / 위치", zh: "咖啡", py: "kāfēi", mean: "커피(숍)" },
        { id: 167, category: "6. 장소 / 교통 / 위치", zh: "图书馆", py: "túshūguǎn", mean: "도서관" },
        { id: 168, category: "6. 장소 / 교통 / 위치", zh: "书店", py: "shūdiàn", mean: "서점" },
        { id: 169, category: "6. 장소 / 교통 / 위치", zh: "电影院", py: "diànyǐngyuàn", mean: "영화관" },
        { id: 170, category: "6. 장소 / 교통 / 위치", zh: "公安局", py: "gōng'ānjú", mean: "공안국, 경찰서" },
        { id: 171, category: "6. 장소 / 교통 / 위치", zh: "机场", py: "jīchǎng", mean: "공항" },
        { id: 172, category: "6. 장소 / 교통 / 위치", zh: "地铁站", py: "dìtiězhàn", mean: "지하철역" },
        { id: 173, category: "6. 장소 / 교통 / 위치", zh: "停车场", py: "tíngchēchǎng", mean: "주차장" },
        { id: 174, category: "6. 장소 / 교통 / 위치", zh: "公园", py: "gōngyuán", mean: "공원" },
        { id: 175, category: "6. 장소 / 교통 / 위치", zh: "动物园", py: "dòngwùyuán", mean: "동물원" },
        { id: 176, category: "6. 장소 / 교통 / 위치", zh: "游乐场", py: "yóulèchǎng", mean: "놀이공원" },
        { id: 177, category: "6. 장소 / 교통 / 위치", zh: "网吧", py: "wǎngbā", mean: "PC방" },
        { id: 178, category: "6. 장소 / 교통 / 위치", zh: "购物中心", py: "gòuwù zhōngxīn", mean: "쇼핑센터" },
        { id: 179, category: "6. 장소 / 교통 / 위치", zh: "家", py: "jiā", mean: "집" },
        { id: 180, category: "6. 장소 / 교통 / 위치", zh: "宿舍", py: "sùshè", mean: "기숙사" },
        { id: 181, category: "6. 장소 / 교통 / 위치", zh: "房间", py: "fángjiān", mean: "방" },
        { id: 182, category: "6. 장소 / 교통 / 위치", zh: "卧室", py: "wòshì", mean: "침실" },
        { id: 183, category: "6. 장소 / 교통 / 위치", zh: "客厅", py: "kètīng", mean: "거실" },
        { id: 184, category: "6. 장소 / 교통 / 위치", zh: "厨房", py: "chúfáng", mean: "주방" },
        { id: 185, category: "6. 장소 / 교통 / 위치", zh: "洗手间", py: "xǐshǒujiān", mean: "화장실" },
        { id: 186, category: "6. 장소 / 교통 / 위치", zh: "阳台", py: "yángtái", mean: "베란다" },
        { id: 187, category: "6. 장소 / 교통 / 위치", zh: "办公室", py: "bàngōngshì", mean: "사무실" },
        { id: 188, category: "6. 장소 / 교통 / 위치", zh: "教室", py: "jiàoshì", mean: "교실" },
        { id: 189, category: "6. 장소 / 교통 / 위치", zh: "操场", py: "cāochǎng", mean: "운동장" },
        { id: 190, category: "6. 장소 / 교통 / 위치", zh: "里", py: "lǐ", mean: "안, 속" },
        { id: 191, category: "6. 장소 / 교통 / 위치", zh: "在", py: "zài", mean: "~에 있다, ~에서" },

        // --- 7. 신체 / 건강 ---
        { id: 192, category: "7. 신체 / 건강", zh: "身体", py: "shēntǐ", mean: "신체, 몸" },
        { id: 193, category: "7. 신체 / 건강", zh: "头", py: "tóu", mean: "머리" },
        { id: 194, category: "7. 신체 / 건강", zh: "脸", py: "liǎn", mean: "얼굴" },
        { id: 195, category: "7. 신체 / 건강", zh: "眼睛", py: "yǎnjing", mean: "눈" },
        { id: 196, category: "7. 신체 / 건강", zh: "鼻子", py: "bízi", mean: "코" },
        { id: 197, category: "7. 신체 / 건강", zh: "耳朵", py: "ěrduo", mean: "귀" },
        { id: 198, category: "7. 신체 / 건강", zh: "嘴", py: "zuǐ", mean: "입" },
        { id: 199, category: "7. 신체 / 건강", zh: "牙", py: "yá", mean: "치아" },
        { id: 200, category: "7. 신체 / 건강", zh: "脖子", py: "bózi", mean: "목" },
        { id: 201, category: "7. 신체 / 건강", zh: "嗓子", py: "sǎngzi", mean: "목구멍, 목소리" },
        { id: 202, category: "7. 신체 / 건강", zh: "肩膀", py: "jiānbǎng", mean: "어깨" },
        { id: 203, category: "7. 신체 / 건강", zh: "胳膊", py: "gēbo", mean: "팔" },
        { id: 204, category: "7. 신체 / 건강", zh: "手", py: "shǒu", mean: "손" },
        { id: 205, category: "7. 신체 / 건강", zh: "腰", py: "yāo", mean: "허리" },
        { id: 206, category: "7. 신체 / 건강", zh: "肚子", py: "dùzi", mean: "배" },
        { id: 207, category: "7. 신체 / 건강", zh: "屁股", py: "pìgu", mean: "엉덩이" },
        { id: 208, category: "7. 신체 / 건강", zh: "腿", py: "tuǐ", mean: "다리" },
        { id: 209, category: "7. 신체 / 건강", zh: "膝盖", py: "xīgài", mean: "무릎" },
        { id: 210, category: "7. 신체 / 건강", zh: "脚", py: "jiǎo", mean: "발" },
        { id: 211, category: "7. 신체 / 건강", zh: "力气", py: "lìqi", mean: "힘, 기운" },
        { id: 212, category: "7. 신체 / 건강", zh: "个子", py: "gèzi", mean: "키, 체격" },
        { id: 213, category: "7. 신체 / 건강", zh: "感冒", py: "gǎnmào", mean: "감기" },
        { id: 214, category: "7. 신체 / 건강", zh: "发烧", py: "fāshāo", mean: "열이 나다" },
        { id: 215, category: "7. 신체 / 건강", zh: "咳嗽", py: "késou", mean: "기침하다" },
        { id: 216, category: "7. 신체 / 건강", zh: "流", py: "liú", mean: "흐르다" },
        { id: 217, category: "7. 신체 / 건강", zh: "鼻涕", py: "bítì", mean: "콧물" },
        { id: 218, category: "7. 신체 / 건강", zh: "拉肚子", py: "lādùzi", mean: "설사하다" },
        { id: 219, category: "7. 신체 / 건강", zh: "疼", py: "téng", mean: "아프다" },

        // --- 8. 동식물 / 띠 ---
        { id: 220, category: "8. 동식물 / 띠", zh: "小狗", py: "xiǎogǒu", mean: "강아지" },
        { id: 221, category: "8. 동식물 / 띠", zh: "属", py: "shǔ", mean: "(띠가) ~이다" },
        { id: 222, category: "8. 동식물 / 띠", zh: "鼠", py: "shǔ", mean: "쥐" },
        { id: 223, category: "8. 동식물 / 띠", zh: "牛", py: "niú", mean: "소" },
        { id: 224, category: "8. 동식물 / 띠", zh: "虎", py: "hǔ", mean: "호랑이" },
        { id: 225, category: "8. 동식물 / 띠", zh: "兔", py: "tù", mean: "토끼" },
        { id: 226, category: "8. 동식물 / 띠", zh: "龙", py: "lóng", mean: "용" },
        { id: 227, category: "8. 동식물 / 띠", zh: "蛇", py: "shé", mean: "뱀" },
        { id: 228, category: "8. 동식물 / 띠", zh: "猴", py: "hóu", mean: "원숭이" },
        { id: 229, category: "8. 동식물 / 띠", zh: "鸡", py: "jī", mean: "닭" },
        { id: 230, category: "8. 동식물 / 띠", zh: "狗", py: "gǒu", mean: "개" },
        { id: 231, category: "8. 동식물 / 띠", zh: "猪", py: "zhū", mean: "돼지" },

        // --- 9. 음식 / 음료 ---
        { id: 232, category: "9. 음식 / 음료", zh: "菜", py: "cài", mean: "요리, 반찬" },
        { id: 233, category: "9. 음식 / 음료", zh: "火锅", py: "huǒguō", mean: "훠궈" },
        { id: 234, category: "9. 음식 / 음료", zh: "烤鸭", py: "kǎoyā", mean: "카오야 (오리구이)" },
        { id: 235, category: "9. 음식 / 음료", zh: "炸酱面", py: "zhájiàngmiàn", mean: "짜장면" },
        { id: 236, category: "9. 음식 / 음료", zh: "麻辣烫", py: "málàtàng", mean: "마라탕" },
        { id: 237, category: "9. 음식 / 음료", zh: "汉堡", py: "hànbǎo", mean: "햄버거" },
        { id: 238, category: "9. 음식 / 음료", zh: "比萨", py: "bǐsà", mean: "피자" },
        { id: 239, category: "9. 음식 / 음료", zh: "炸鸡", py: "zhájī", mean: "치킨" },
        { id: 240, category: "9. 음식 / 음료", zh: "三明治", py: "sānmíngzhì", mean: "샌드위치" },
        { id: 241, category: "9. 음식 / 음료", zh: "牛排", py: "niúpái", mean: "스테이크" },
        { id: 242, category: "9. 음식 / 음료", zh: "方便面", py: "fāngbiànmiàn", mean: "라면" },
        { id: 243, category: "9. 음식 / 음료", zh: "水", py: "shuǐ", mean: "물" },
        { id: 244, category: "9. 음식 / 음료", zh: "矿泉水", py: "kuàngquánshuǐ", mean: "생수" },
        { id: 245, category: "9. 음식 / 음료", zh: "牛奶", py: "niúnǎi", mean: "우유" },
        { id: 246, category: "9. 음식 / 음료", zh: "果汁", py: "guǒzhī", mean: "과일주스" },
        { id: 247, category: "9. 음식 / 음료", zh: "可乐", py: "kělè", mean: "콜라" },
        { id: 248, category: "9. 음식 / 음료", zh: "绿茶", py: "lǜchá", mean: "녹차" },
        { id: 249, category: "9. 음식 / 음료", zh: "啤酒", py: "píjiǔ", mean: "맥주" },

        // --- 10. 취미 / 문화 / 스포츠 ---
        { id: 250, category: "10. 취미 / 스포츠", zh: "电影", py: "diànyǐng", mean: "영화" },
        { id: 251, category: "10. 취미 / 스포츠", zh: "音乐", py: "yīnyuè", mean: "음악" },
        { id: 252, category: "10. 취미 / 스포츠", zh: "钢琴", py: "gāngqín", mean: "피아노" },
        { id: 253, category: "10. 취미 / 스포츠", zh: "吉他", py: "jítā", mean: "기타" },
        { id: 254, category: "10. 취미 / 스포츠", zh: "鼓", py: "gǔ", mean: "북, 드럼" },
        { id: 255, category: "10. 취미 / 스포츠", zh: "小说", py: "xiǎoshuō", mean: "소설" },
        { id: 256, category: "10. 취미 / 스포츠", zh: "节目", py: "jiémù", mean: "프로그램" },
        { id: 257, category: "10. 취미 / 스포츠", zh: "游戏", py: "yóuxì", mean: "게임" },
        { id: 258, category: "10. 취미 / 스포츠", zh: "运动", py: "yùndòng", mean: "운동" },
        { id: 259, category: "10. 취미 / 스포츠", zh: "台球", py: "táiqiú", mean: "당구" },
        { id: 260, category: "10. 취미 / 스포츠", zh: "棒球", py: "bàngqiú", mean: "야구" },
        { id: 261, category: "10. 취미 / 스포츠", zh: "排球", py: "páiqiú", mean: "배구" },
        { id: 262, category: "10. 취미 / 스포츠", zh: "羽毛球", py: "yǔmáoqiú", mean: "배드민턴" },
        { id: 263, category: "10. 취미 / 스포츠", zh: "乒乓球", py: "pīngpāngqiú", mean: "탁구" },
        { id: 264, category: "10. 취미 / 스포츠", zh: "高尔夫球", py: "gāo'ěrfūqiú", mean: "골프" },
        { id: 265, category: "10. 취미 / 스포츠", zh: "滑冰", py: "huábīng", mean: "스케이트" },
        { id: 266, category: "10. 취미 / 스포츠", zh: "滑雪", py: "huáxuě", mean: "스키" },
        { id: 267, category: "10. 취미 / 스포츠", zh: "太极拳", py: "tàijíquán", mean: "태극권" },
        { id: 268, category: "10. 취미 / 스포츠", zh: "跆拳道", py: "táiquándào", mean: "태권도" },
        { id: 269, category: "10. 취미 / 스포츠", zh: "瑜伽", py: "yújiā", mean: "요가" },
        { id: 270, category: "10. 취미 / 스포츠", zh: "马拉松", py: "mǎlāsōng", mean: "마라톤" },

        // --- 11. 동사 / 행동 (일상) ---
        { id: 271, category: "11. 동사 / 행동", zh: "做", py: "zuò", mean: "하다, 만들다" },
        { id: 272, category: "11. 동사 / 행동", zh: "看", py: "kàn", mean: "보다" },
        { id: 273, category: "11. 동사 / 행동", zh: "听", py: "tīng", mean: "듣다" },
        { id: 274, category: "11. 동사 / 행동", zh: "说", py: "shuō", mean: "말하다" },
        { id: 275, category: "11. 동사 / 행동", zh: "读", py: "dú", mean: "읽다" },
        { id: 276, category: "11. 동사 / 행동", zh: "写", py: "xiě", mean: "쓰다" },
        { id: 277, category: "11. 동사 / 행동", zh: "吃", py: "chī", mean: "먹다" },
        { id: 278, category: "11. 동사 / 행동", zh: "喝", py: "hē", mean: "마시다" },
        { id: 279, category: "11. 동사 / 행동", zh: "闻", py: "wén", mean: "냄새 맡다" },
        { id: 280, category: "11. 동사 / 행동", zh: "穿", py: "chuān", mean: "입다, 신다" },
        { id: 281, category: "11. 동사 / 행동", zh: "来", py: "lái", mean: "오다" },
        { id: 282, category: "11. 동사 / 행동", zh: "去", py: "qù", mean: "가다" },
        { id: 283, category: "11. 동사 / 행동", zh: "走", py: "zǒu", mean: "걷다" },
        { id: 284, category: "11. 동사 / 행동", zh: "跑", py: "pǎo", mean: "달리다" },
        { id: 285, category: "11. 동사 / 행동", zh: "坐", py: "zuò", mean: "앉다" },
        { id: 286, category: "11. 동사 / 행동", zh: "站", py: "zhàn", mean: "서다" },
        { id: 287, category: "11. 동사 / 행동", zh: "躺", py: "tǎng", mean: "눕다" },
        { id: 288, category: "11. 동사 / 행동", zh: "进", py: "jìn", mean: "들어가다" },
        { id: 289, category: "11. 동사 / 행동", zh: "出", py: "chū", mean: "나가다" },
        { id: 290, category: "11. 동사 / 행동", zh: "开", py: "kāi", mean: "열다, 켜다" },
        { id: 291, category: "11. 동사 / 행동", zh: "关", py: "guān", mean: "닫다, 끄다" },
        { id: 292, category: "11. 동사 / 행동", zh: "问", py: "wèn", mean: "묻다" },
        { id: 293, category: "11. 동사 / 행동", zh: "回答", py: "huídá", mean: "대답하다" },
        { id: 294, category: "11. 동사 / 행동", zh: "打", py: "dǎ", mean: "치다, 때리다, 하다" },
        { id: 295, category: "11. 동사 / 행동", zh: "给", py: "gěi", mean: "주다" },
        { id: 296, category: "11. 동사 / 행동", zh: "买", py: "mǎi", mean: "사다" },
        { id: 297, category: "11. 동사 / 행동", zh: "学", py: "xué", mean: "배우다" },
        { id: 298, category: "11. 동사 / 행동", zh: "教", py: "jiāo", mean: "가르치다" },
        { id: 299, category: "11. 동사 / 행동", zh: "爱", py: "ài", mean: "사랑하다" },
        { id: 300, category: "11. 동사 / 행동", zh: "喜欢", py: "xǐhuan", mean: "좋아하다" },
        { id: 301, category: "11. 동사 / 행동", zh: "想", py: "xiǎng", mean: "생각하다, ~하고 싶다" },
        { id: 302, category: "11. 동사 / 행동", zh: "觉得", py: "juéde", mean: "느끼다, 생각하다" },
        { id: 303, category: "11. 동사 / 행동", zh: "会", py: "huì", mean: "할 줄 알다" },
        { id: 304, category: "11. 동사 / 행동", zh: "可以", py: "kěyǐ", mean: "할 수 있다" },
        { id: 305, category: "11. 동사 / 행동", zh: "要", py: "yào", mean: "원하다, ~해야 한다" },
        { id: 306, category: "11. 동사 / 행동", zh: "注意", py: "zhùyì", mean: "주의하다" },
        { id: 307, category: "11. 동사 / 행동", zh: "见", py: "jiàn", mean: "만나다" },

        // --- 11-2. 동사 / 행동 (복합어) ---
        { id: 308, category: "11. 동사 / 행동", zh: "起床", py: "qǐchuáng", mean: "일어나다" },
        { id: 309, category: "11. 동사 / 행동", zh: "睡觉", py: "shuìjiào", mean: "자다" },
        { id: 310, category: "11. 동사 / 행동", zh: "上班", py: "shàngbān", mean: "출근하다" },
        { id: 311, category: "11. 동사 / 행동", zh: "下班", py: "xiàbān", mean: "퇴근하다" },
        { id: 312, category: "11. 동사 / 행동", zh: "加班", py: "jiābān", mean: "야근하다" },
        { id: 313, category: "11. 동사 / 행동", zh: "开会", py: "kāihuì", mean: "회의하다" },
        { id: 314, category: "11. 동사 / 행동", zh: "吃饭", py: "chīfàn", mean: "밥을 먹다" },
        { id: 315, category: "11. 동사 / 행동", zh: "做菜", py: "zuòcài", mean: "요리하다" },
        { id: 316, category: "11. 동사 / 행동", zh: "看电影", py: "kàn diànyǐng", mean: "영화를 보다" },
        { id: 317, category: "11. 동사 / 행동", zh: "写字", py: "xiězì", mean: "글씨를 쓰다" },
        { id: 318, category: "11. 동사 / 행동", zh: "画画儿", py: "huàhuàr", mean: "그림을 그리다" },
        { id: 319, category: "11. 동사 / 행동", zh: "唱歌", py: "chànggē", mean: "노래하다" },
        { id: 320, category: "11. 동사 / 행동", zh: "跳舞", py: "tiàowǔ", mean: "춤추다" },
        { id: 321, category: "11. 동사 / 행동", zh: "玩儿", py: "wánr", mean: "놀다" },
        { id: 322, category: "11. 동사 / 행동", zh: "踢足球", py: "tī zúqiú", mean: "축구하다" },
        { id: 323, category: "11. 동사 / 행동", zh: "打篮球", py: "dǎ lánqiú", mean: "농구하다" },
        { id: 324, category: "11. 동사 / 행동", zh: "游泳", py: "yóuyǒng", mean: "수영하다" },
        { id: 325, category: "11. 동사 / 행동", zh: "爬山", py: "páshān", mean: "등산하다" },
        { id: 326, category: "11. 동사 / 행동", zh: "钓鱼", py: "diàoyú", mean: "낚시하다" },
        { id: 327, category: "11. 동사 / 행동", zh: "下围棋", py: "xià wéiqí", mean: "바둑을 두다" },
        { id: 328, category: "11. 동사 / 행동", zh: "打电话", py: "dǎ diànhuà", mean: "전화하다" },
        { id: 329, category: "11. 동사 / 행동", zh: "接电话", py: "jiē diànhuà", mean: "전화를 받다" },
        { id: 330, category: "11. 동사 / 행동", zh: "拍照", py: "pāizhào", mean: "사진을 찍다" },
        { id: 331, category: "11. 동사 / 행동", zh: "开车", py: "kāichē", mean: "운전하다" },
        { id: 332, category: "11. 동사 / 행동", zh: "打扫", py: "dǎsǎo", mean: "청소하다" },
        { id: 333, category: "11. 동사 / 행동", zh: "参加", py: "cānjiā", mean: "참가하다" },
        { id: 334, category: "11. 동사 / 행동", zh: "报名", py: "bàomíng", mean: "신청하다" },
        { id: 335, category: "11. 동사 / 행동", zh: "结婚", py: "jiéhūn", mean: "결혼하다" },
        { id: 336, category: "11. 동사 / 행동", zh: "工作", py: "gōngzuò", mean: "일하다" },
        { id: 337, category: "11. 동사 / 행동", zh: "学习", py: "xuéxí", mean: "학습하다" },

        // --- 12. 형용사 / 감정 / 상태 ---
        { id: 338, category: "12. 형용사 / 상태", zh: "高兴", py: "gāoxìng", mean: "기쁘다" },
        { id: 339, category: "12. 형용사 / 상태", zh: "开心", py: "kāixīn", mean: "즐겁다" },
        { id: 340, category: "12. 형용사 / 상태", zh: "幸福", py: "xìngfú", mean: "행복하다" },
        { id: 341, category: "12. 형용사 / 상태", zh: "难过", py: "nánguò", mean: "슬프다" },
        { id: 342, category: "12. 형용사 / 상태", zh: "紧张", py: "jǐnzhāng", mean: "긴장하다" },
        { id: 343, category: "12. 형용사 / 상태", zh: "无聊", py: "wúliáo", mean: "지루하다" },
        { id: 344, category: "12. 형용사 / 상태", zh: "舒服", py: "shūfu", mean: "편안하다" },
        { id: 345, category: "12. 형용사 / 상태", zh: "忙", py: "máng", mean: "바쁘다" },
        { id: 346, category: "12. 형용사 / 상태", zh: "累", py: "lèi", mean: "피곤하다" },
        { id: 347, category: "12. 형용사 / 상태", zh: "困", py: "kùn", mean: "졸리다" },
        { id: 348, category: "12. 형용사 / 상태", zh: "饿", py: "è", mean: "배고프다" },
        { id: 349, category: "12. 형용사 / 상태", zh: "饱", py: "bǎo", mean: "배부르다" },
        { id: 350, category: "12. 형용사 / 상태", zh: "渴", py: "kě", mean: "목마르다" },
        { id: 351, category: "12. 형용사 / 상태", zh: "高", py: "gāo", mean: "높다" },
        { id: 352, category: "12. 형용사 / 상태", zh: "矮", py: "ǎi", mean: "낮다" },
        { id: 353, category: "12. 형용사 / 상태", zh: "贵", py: "guì", mean: "비싸다" },
        { id: 354, category: "12. 형용사 / 상태", zh: "便宜", py: "piányi", mean: "싸다" },
        { id: 355, category: "12. 형용사 / 상태", zh: "干净", py: "gānjìng", mean: "깨끗하다" },
        { id: 356, category: "12. 형용사 / 상태", zh: "脏", py: "zāng", mean: "더럽다" },
        { id: 357, category: "12. 형용사 / 상태", zh: "难", py: "nán", mean: "어렵다" },
        { id: 358, category: "12. 형용사 / 상태", zh: "容易", py: "róngyì", mean: "쉽다" },
        { id: 359, category: "12. 형용사 / 상태", zh: "坏", py: "huài", mean: "나쁘다, 고장나다" },
        { id: 360, category: "12. 형용사 / 상태", zh: "辣", py: "là", mean: "맵다" },
        { id: 361, category: "12. 형용사 / 상태", zh: "帅", py: "shuài", mean: "멋지다" },
        { id: 362, category: "12. 형용사 / 상태", zh: "漂亮", py: "piàoliang", mean: "예쁘다" },
        { id: 363, category: "12. 형용사 / 상태", zh: "可爱", py: "kě'ài", mean: "귀엽다" },
        { id: 364, category: "12. 형용사 / 상태", zh: "好吃", py: "hǎochī", mean: "맛있다" },
        { id: 365, category: "12. 형용사 / 상태", zh: "不错", py: "búcuò", mean: "훌륭하다" },
        { id: 366, category: "12. 형용사 / 상태", zh: "有意思", py: "yǒuyìsi", mean: "재미있다" },
        { id: 367, category: "12. 형용사 / 상태", zh: "一样", py: "yíyàng", mean: "같다" },
        { id: 368, category: "12. 형용사 / 상태", zh: "了不起", py: "liǎobuqǐ", mean: "대단하다" },
        { id: 369, category: "12. 형용사 / 상태", zh: "厉害", py: "lìhai", mean: "대단하다, 심하다" },
        { id: 370, category: "12. 형용사 / 상태", zh: "骄傲", py: "jiāo'ào", mean: "자랑스럽다" },

        // --- 13. 부사 / 양사 / 기타 ---
        { id: 371, category: "13. 기타 품사", zh: "很", py: "hěn", mean: "매우" },
        { id: 372, category: "13. 기타 품사", zh: "非常", py: "fēicháng", mean: "대단히" },
        { id: 373, category: "13. 기타 품사", zh: "特别", py: "tèbié", mean: "특별히" },
        { id: 374, category: "13. 기타 품사", zh: "最", py: "zuì", mean: "가장" },
        { id: 375, category: "13. 기타 품사", zh: "真", py: "zhēn", mean: "정말" },
        { id: 376, category: "13. 기타 품사", zh: "挺", py: "tǐng", mean: "꽤" },
        { id: 377, category: "13. 기타 품사", zh: "不太", py: "bú tài", mean: "별로 ~않다" },
        { id: 378, category: "13. 기타 품사", zh: "也", py: "yě", mean: "~도" },
        { id: 379, category: "13. 기타 품사", zh: "都", py: "dōu", mean: "모두, 다" },
        { id: 380, category: "13. 기타 품사", zh: "还", py: "hái", mean: "아직, 여전히" },
        { id: 381, category: "13. 기타 품사", zh: "还是", py: "háishì", mean: "아니면, 여전히" },
        { id: 382, category: "13. 기타 품사", zh: "已经", py: "yǐjīng", mean: "이미" },
        { id: 383, category: "13. 기타 품사", zh: "最近", py: "zuìjìn", mean: "최근" },
        { id: 384, category: "13. 기타 품사", zh: "天天", py: "tiāntiān", mean: "매일" },
        { id: 385, category: "13. 기타 품사", zh: "一起", py: "yìqǐ", mean: "같이" },
        { id: 386, category: "13. 기타 품사", zh: "这样", py: "zhèyàng", mean: "이렇게" },
        { id: 387, category: "13. 기타 품사", zh: "一点儿", py: "yìdiǎnr", mean: "조금" },
        { id: 388, category: "13. 기타 품사", zh: "怎么", py: "zěnme", mean: "어떻게" },
        { id: 389, category: "13. 기타 품사", zh: "怎么样", py: "zěnmeyàng", mean: "어때요" },
        { id: 390, category: "13. 기타 품사", zh: "行", py: "xíng", mean: "좋다, 가능하다" },
        { id: 391, category: "13. 기타 품사", zh: "老样子", py: "lǎoyàngzi", mean: "여전하다" },
        { id: 392, category: "13. 기타 품사", zh: "当然", py: "dāngrán", mean: "당연하다" },
        { id: 393, category: "13. 기타 품사", zh: "哪里", py: "nǎli", mean: "별말씀을요" },
        { id: 394, category: "13. 기타 품사", zh: "过奖", py: "guòjiǎng", mean: "과찬이다" },
        { id: 395, category: "13. 기타 품사", zh: "没什么", py: "méi shénme", mean: "별일 아니다" },
        { id: 396, category: "13. 기타 품사", zh: "谢谢", py: "xièxie", mean: "감사합니다" },
        { id: 397, category: "13. 기타 품사", zh: "为", py: "wèi", mean: "~을 위하여" },
        { id: 398, category: "13. 기타 품사", zh: "两", py: "liǎng", mean: "둘, 2" },
        { id: 399, category: "13. 기타 품사", zh: "几", py: "jǐ", mean: "몇" },
        { id: 400, category: "13. 기타 품사", zh: "个", py: "gè", mean: "개, 명 (범용 양사)" },
        { id: 401, category: "13. 기타 품사", zh: "口", py: "kǒu", mean: "식구를 세는 양사" },
        { id: 402, category: "13. 기타 품사", zh: "台", py: "tái", mean: "대 (기계 양사)" },
        { id: 403, category: "13. 기타 품사", zh: "件", py: "jiàn", mean: "벌, 건 (옷, 일)" },
        { id: 404, category: "13. 기타 품사", zh: "条", py: "tiáo", mean: "마리, 가닥" },
        { id: 405, category: "13. 기타 품사", zh: "本", py: "běn", mean: "권" },
        { id: 406, category: "13. 기타 품사", zh: "杯", py: "bēi", mean: "잔, 컵" },
        { id: 407, category: "13. 기타 품사", zh: "只", py: "zhī", mean: "마리, 개" },
        { id: 408, category: "13. 기타 품사", zh: "次", py: "cì", mean: "번, 차례" },
        { id: 409, category: "13. 기타 품사", zh: "遍", py: "biàn", mean: "번 (처음부터 끝까지)" },
        { id: 410, category: "13. 기타 품사", zh: "趟", py: "tàng", mean: "번 (왕복)" },
        { id: 411, category: "13. 기타 품사", zh: "的", py: "de", mean: "~의" },
        { id: 412, category: "13. 기타 품사", zh: "得", py: "de", mean: "~하는 정도가 ~하다" },
        { id: 413, category: "13. 기타 품사", zh: "过", py: "guo", mean: "~한 적이 있다" },
        { id: 414, category: "13. 기타 품사", zh: "了", py: "le", mean: "~했다" },
        { id: 415, category: "13. 기타 품사", zh: "吧", py: "ba", mean: "~하자, ~지?" },
        { id: 416, category: "13. 기타 품사", zh: "吗", py: "ma", mean: "~입니까?" },
        { id: 417, category: "13. 기타 품사", zh: "呢", py: "ne", mean: "~는요?" },
        { id: 418, category: "13. 기타 품사", zh: "中文", py: "Zhōngwén", mean: "중국어" },
        { id: 419, category: "13. 기타 품사", zh: "英文", py: "Yīngwén", mean: "영어" },
        { id: 420, category: "13. 기타 품사", zh: "生意", py: "shēngyi", mean: "장사, 사업" },
        { id: 421, category: "13. 기타 품사", zh: "贸易", py: "màoyì", mean: "무역" },
        { id: 422, category: "13. 기타 품사", zh: "工资", py: "gōngzī", mean: "월급" },
        { id: 423, category: "13. 기타 품사", zh: "价格", py: "jiàgé", mean: "가격" },
        { id: 424, category: "13. 기타 품사", zh: "性格", py: "xìnggé", mean: "성격" },
        { id: 425, category: "13. 기타 품사", zh: "信", py: "xìn", mean: "편지" },
        { id: 426, category: "13. 기타 품사", zh: "钱", py: "qián", mean: "돈" },
        { id: 427, category: "13. 기타 품사", zh: "零钱", py: "língqián", mean: "잔돈" }
    ]
};