vocabData["H31001"] = {
    title: "H31001",
    words: [
        // --- 1. 사람 / 직업 / 관계 ---
        { id: 1, category: "1. 사람/직업/관계", zh: "经理", py: "jīnglǐ", mean: "사장, 매니저" },
        { id: 2, category: "1. 사람/직업/관계", zh: "阿姨", py: "āyí", mean: "이모, 아주머니" },
        { id: 3, category: "1. 사람/직업/관계", zh: "叔叔", py: "shūshu", mean: "삼촌, 아저씨" },
        { id: 4, category: "1. 사람/직업/관계", zh: "同事", py: "tóngshì", mean: "동료" },
        { id: 5, category: "1. 사람/직업/관계", zh: "司机", py: "sījī", mean: "운전기사" },
        { id: 6, category: "1. 사람/직업/관계", zh: "邻居", py: "línjū", mean: "이웃" },
        { id: 7, category: "1. 사람/직업/관계", zh: "小姐", py: "xiǎojiě", mean: "아가씨" },
        { id: 8, category: "1. 사람/직업/관계", zh: "新来的", py: "xīn lái de", mean: "새로 온 사람" },
        { id: 9, category: "1. 사람/직업/관계", zh: "有些人", py: "yǒuxiē rén", mean: "어떤 사람들" },

        // --- 2. 일상 명사 / 장소 / 사물 ---
        { id: 10, category: "2. 일상 명사/장소/사물", zh: "事情", py: "shìqing", mean: " 일, 사건" },
        { id: 11, category: "2. 일상 명사/장소/사물", zh: "办法", py: "bànfǎ", mean: "방법" },
        { id: 12, category: "2. 일상 명사/장소/사물", zh: "自行车", py: "zìxíngchē", mean: "자전거" },
        { id: 13, category: "2. 일상 명사/장소/사물", zh: "电子词典", py: "diànzǐ cídiǎn", mean: "전자사전" },
        { id: 14, category: "2. 일상 명사/장소/사물", zh: "楼", py: "lóu", mean: "건물, 층" },
        { id: 15, category: "2. 일상 명사/장소/사물", zh: "层", py: "céng", mean: "층" },
        { id: 16, category: "2. 일상 명사/장소/사물", zh: "会议室", py: "huìyìshì", mean: "회의실" },
        { id: 17, category: "2. 일상 명사/장소/사물", zh: "会议", py: "huìyì", mean: "회의" },
        { id: 18, category: "2. 일상 명사/장소/사물", zh: "蛋糕", py: "dàngāo", mean: "케이크" },
        { id: 19, category: "2. 일상 명사/장소/사물", zh: "节目", py: "jiémù", mean: "프로그램, 방송" },
        { id: 20, category: "2. 일상 명사/장소/사물", zh: "地方", py: "dìfang", mean: "장소, 곳" },
        { id: 21, category: "2. 일상 명사/장소/사물", zh: "超市", py: "chāoshì", mean: "슈퍼마켓" },
        { id: 22, category: "2. 일상 명사/장소/사물", zh: "面包", py: "miànbāo", mean: "빵" },
        { id: 23, category: "2. 일상 명사/장소/사물", zh: "报纸", py: "bàozhǐ", mean: "신문" },
        { id: 24, category: "2. 일상 명사/장소/사물", zh: "邮件", py: "yóujiàn", mean: "우편, 이메일" },
        { id: 25, category: "2. 일상 명사/장소/사물", zh: "房间", py: "fángjiān", mean: "방" },
        { id: 26, category: "2. 일상 명사/장소/사물", zh: "灯", py: "dēng", mean: "등, 조명" },
        { id: 27, category: "2. 일상 명사/장소/사물", zh: "颜色", py: "yánsè", mean: "색상" },
        { id: 28, category: "2. 일상 명사/장소/사물", zh: "门口", py: "ménkǒu", mean: "문 앞, 입구" },
        { id: 29, category: "2. 일상 명사/장소/사물", zh: "老地方", py: "lǎodìfang", mean: "늘 만나던 곳" },
        { id: 30, category: "2. 일상 명사/장소/사물", zh: "电视", py: "diànshì", mean: "TV" },
        { id: 31, category: "2. 일상 명사/장소/사물", zh: "声音", py: "shēngyīn", mean: "소리, 목소리" },
        { id: 32, category: "2. 일상 명사/장소/사물", zh: "护照", py: "hùzhào", mean: "여권" },
        { id: 33, category: "2. 일상 명사/장소/사물", zh: "衬衫", py: "chènshān", mean: "셔츠" },
        { id: 34, category: "2. 일상 명사/장소/사물", zh: "作业", py: "zuòyè", mean: "숙제" },
        { id: 35, category: "2. 일상 명사/장소/사물", zh: "银行", py: "yínháng", mean: "은행" },
        { id: 36, category: "2. 일상 명사/장소/사물", zh: "菜单儿", py: "càidānr", mean: "메뉴판" },
        { id: 37, category: "2. 일상 명사/장소/사물", zh: "附近", py: "fùjìn", mean: "부근, 근처" },
        { id: 38, category: "2. 일상 명사/장소/사물", zh: "桌子", py: "zhuōzi", mean: "탁자, 테이블" },
        { id: 39, category: "2. 일상 명사/장소/사물", zh: "火车站", py: "huǒchēzhàn", mean: "기차역" },
        { id: 40, category: "2. 일상 명사/amp;사물", zh: "宾馆", py: "bīnguǎn", mean: "호텔, 객방" },
        { id: 41, category: "2. 일상 명사/장소/사물", zh: "厨房", py: "chúfáng", mean: "주방" },
        { id: 42, category: "2. 일상 명사/장소/사물", zh: "鲜花", py: "xiānhuā", mean: "생화, 꽃" },
        { id: 43, category: "2. 일상 명사/장소/사물", zh: "黑板", py: "hēibǎn", mean: "칠판" },
        { id: 44, category: "2. 일상 명사/장소/사물", zh: "词", py: "cí", mean: "단어" },
        { id: 45, category: "2. 일상 명사/장소/사물", zh: "本子", py: "běnzi", mean: "공책" },
        { id: 46, category: "2. 일상 명사/장소/사물", zh: "故事", py: "gùshì", mean: "이야기" },
        { id: 47, category: "2. 일상 명사/장소/사물", zh: "河边", py: "hébiān", mean: "강가" },
        { id: 48, category: "2. 일상 명사/장소/사물", zh: "草地", py: "cǎodì", mean: "풀밭, 잔디" },
        { id: 49, category: "2. 일상 명사/장소/사물", zh: "树", py: "shù", mean: "나무" },
        { id: 50, category: "2. 일상 명사/장소/사물", zh: "鸟", py: "niǎo", mean: "새" },
        { id: 51, category: "2. 일상 명사/장소/사물", zh: "机床", py: "jīchuáng", mean: "공작기계" },
        { id: 52, category: "2. 일상 명사/장소/사물", zh: "街道", py: "jiēdào", mean: "거리" },
        { id: 53, category: "2. 일상 명사/장소/사물", zh: "世界", py: "shìjiè", mean: "세계" },
        { id: 54, category: "2. 일상 명사/장소/사물", zh: "旁边", py: "pángbiān", mean: "옆" },
        { id: 55, category: "2. 일상 명사/장소/사물", zh: "右边", py: "yòubian", mean: "오른쪽" },
        { id: 56, category: "2. 일상 명사/장소/사물", zh: "环境", py: "huánjìng", mean: "환경" },
        { id: 57, category: "2. 일상 명사/장소/사물", zh: "城市", py: "chéngshì", mean: "도시" },
        { id: 58, category: "2. 일상 명사/장소/사물", zh: "出租车", py: "chūzūchē", mean: "택시" },
        { id: 59, category: "2. 일상 명사/장소/사물", zh: "中间", py: "zhōngjiān", mean: "중간, 사이" },
        { id: 60, category: "2. 일상 명사/장소/사물", zh: "裙子", py: "qúnzi", mean: "치마" },
        { id: 61, category: "2. 일상 명사/장소/사물", zh: "鞋", py: "xié", mean: "신발" },
        { id: 62, category: "2. 일상 명사/장소/사물", zh: "碗", py: "wǎn", mean: "그릇" },
        { id: 63, category: "2. 일상 명사/장소/사물", zh: "筷子", py: "kuàizi", mean: "젓가락" },
        { id: 64, category: "2. 일상 명사/장소/사물", zh: "照片", py: "zhàopiàn", mean: "사진" },
        { id: 65, category: "2. 일상 명사/장소/사물", zh: "行李", py: "xíngli", mean: "짐, 수하물" },

        // --- 3. 신체 / 건강 / 의학 ---
        { id: 66, category: "3. 신체/건강/의학", zh: "药", py: "yào", mean: "약" },
        { id: 67, category: "3. 신체/건강/의학", zh: "健康", py: "jiànkāng", mean: "건강" },
        { id: 68, category: "3. 신체/건강/의학", zh: "腿", py: "tuǐ", mean: "다리" },
        { id: 69, category: "3. 신체/건강/의학", zh: "脚", py: "jiǎo", mean: "발" },
        { id: 70, category: "3. 신체/건강/의학", zh: "鼻子", py: "bízi", mean: "코" },
        { id: 71, category: "3. 신체/건강/의학", zh: "眼睛", py: "yǎnjing", mean: "눈" },
        { id: 72, category: "3. 신체/건강/의학", zh: "耳朵", py: "ěrduo", mean: "귀" },

        // --- 4. 시간 / 자연 / 계절 ---
        { id: 73, category: "4. 시간/자연/계절", zh: "以后", py: "yǐhòu", mean: "이후" },
        { id: 74, category: "4. 시간/자연/계절", zh: "上次", py: "shàngcì", mean: "지난번" },
        { id: 75, category: "4. 시간/자연/계절", zh: "时候", py: "shíhou", mean: "때, 시기" },
        { id: 76, category: "4. 시간/자연/계절", zh: "这次", py: "zhècì", mean: "이번" },
        { id: 77, category: "4. 시간/자연/계절", zh: "去年", py: "qùnián", mean: "작년" },
        { id: 78, category: "4. 시간/자연/계절", zh: "白天", py: "báitiān", mean: "낮, 주간" },
        { id: 79, category: "4. 시간/자연/계절", zh: "刚才", py: "gāngcái", mean: "방금, 막" },
        { id: 80, category: "4. 시간/자연/계절", zh: "秋天", py: "qiūtiān", mean: "가을" },
        { id: 81, category: "4. 시간/자연/계절", zh: "季节", py: "jìjié", mean: "계절" },
        { id: 82, category: "4. 시간/자연/계절", zh: "晴天", py: "qíngtiān", mean: "맑은 날" },
        { id: 83, category: "4. 시간/자연/계절", zh: "阴天", py: "yīntiān", mean: "흐린 날" },
        { id: 84, category: "4. 시간/자연/계절", zh: "周末", py: "zhōumò", mean: "주말" },

        // --- 5. 교육 / 시험 / 학업 ---
        { id: 85, category: "5. 교육/시험/학업", zh: "参加", py: "cānjiā", mean: "참가하다" },
        { id: 86, category: "5. 교육/시험/학업", zh: "考试", py: "kǎoshì", mean: "시험" },
        { id: 87, category: "5. 교육/시험/학업", zh: "听力", py: "tīnglì", mean: "청력, 듣기" },
        { id: 88, category: "5. 교육/시험/학업", zh: "部分", py: "bùfen", mean: "부분" },
        { id: 89, category: "5. 교육/시험/학업", zh: "练习", py: "liànxí", mean: "연습하다" },
        { id: 90, category: "5. 교육/시험/학업", zh: "历史", py: "lìshǐ", mean: "역사" },
        { id: 91, category: "5. 교육/시험/학업", zh: "数学", py: "shùxué", mean: "수학" },
        { id: 92, category: "5. 교육/시험/학업", zh: "读书", py: "dúshū", mean: "책을 읽다, 공부하다" },
        { id: 93, category: "5. 교육/시험/학업", zh: "学习", py: "xuéxí", mean: "공부하다" },
        { id: 94, category: "5. 교육/시험/학업", zh: "年级", py: "niánjí", mean: "학년" },
        { id: 95, category: "5. 교육/시험/학업", zh: "课", py: "kè", mean: "과업, 수업" },

        // --- 6. 동사 (행동 / 변화) ---
        { id: 96, category: "6. 동사 (행동/변화)", zh: "喂", py: "wèi", mean: "여보세요, 먹이를 주다" },
        { id: 97, category: "6. 동사 (행동/변화)", zh: "开始", py: "kāishǐ", mean: "시작하다" },
        { id: 98, category: "6. 동사 (행동/변화)", zh: "到", py: "dào", mean: "도착하다, ~까지" },
        { id: 99, category: "6. 동사 (행동/변화)", zh: "结婚", py: "jiéhūn", mean: "결혼하다" },
        { id: 100, category: "6. 동사 (행동/변화)", zh: "穿", py: "chuān", mean: "입다, 신다" },
        { id: 101, category: "6. 동사 (행동/변화)", zh: "出现", py: "chūxiàn", mean: "나타나다, 출현하다" },
        { id: 102, category: "6. 동사 (행동/변화)", zh: "解决", py: "jiějué", mean: "해결하다" },
        { id: 103, category: "6. 동사 (행동/변化)", zh: "哭", py: "kū", mean: "울다" },
        { id: 104, category: "6. 동사 (행동/변화)", zh: "记得", py: "jìde", mean: "기억하다" },
        { id: 105, category: "6. 동사 (행동/변화)", zh: "帮助", py: "bāngzhù", mean: "돕다" },
        { id: 106, category: "6. 동사 (행동/변화)", zh: "帮", py: "bāng", mean: "돕다" },
        { id: 107, category: "6. 동사 (행동/변화)", zh: "准备", py: "zhǔnbèi", mean: "준비하다" },
        { id: 108, category: "6. 동사 (행동/변화)", zh: "告诉", py: "gàosu", mean: "알리다, 말하다" },
        { id: 109, category: "6. 동사 (행동/변화)", zh: "读", py: "dú", mean: "읽다" },
        { id: 110, category: "6. 동사 (행동/변화)", zh: "让", py: "ràng", mean: "~로 하여금 ~하게 하다" },
        { id: 111, category: "6. 동사 (행동/변화)", zh: "花", py: "huā", mean: "돈/시간을 쓰다, 꽃" },
        { id: 112, category: "6. 동사 (행동/변화)", zh: "锻炼", py: "duànliàn", mean: "단련하다, 운동하다" },
        { id: 113, category: "6. 동사 (행동/변화)", zh: "发现", py: "fāxiàn", mean: "발견하다" },
        { id: 114, category: "6. 동사 (행동/변화)", zh: "选择", py: "xuǎnzé", mean: "선택하다" },
        { id: 115, category: "6. 동사 (행동/변화)", zh: "换", py: "huàn", mean: "바꾸다, 교환하다" },
        { id: 116, category: "6. 동사 (행동/변화)", zh: "踢", py: "tī", mean: "차다" },
        { id: 117, category: "6. 동사 (행동/변화)", zh: "足球", py: "zúqiú", mean: "축구하다" },
        { id: 118, category: "6. 동사 (행동/변화)", zh: "照相", py: "zhàoxiàng", mean: "사진을 찍다" },
        { id: 119, category: "6. 동사 (행동/변화)", zh: "找", py: "zhǎo", mean: "찾다" },
        { id: 120, category: "6. 동사 (행동/변화)", zh: "教", py: "jiāo", mean: "가르치다" },
        { id: 121, category: "6. 동사 (행동/변화)", zh: "结束", py: "jiéshù", mean: "끝나다" },
        { id: 122, category: "6. 동사 (행동/변화)", zh: "比赛", py: "bǐsài", mean: "경기하다, 시합" },
        { id: 123, category: "6. 동사 (행동/변화)", zh: "休息", py: "xiūxi", mean: "쉬다" },
        { id: 124, category: "6. 동사 (행동/변화)", zh: "进去", py: "jìnqù", mean: "들어가다" },
        { id: 125, category: "6. 동사 (행동/변화)", zh: "拿", py: "ná", mean: "잡다, 가지다" },
        { id: 126, category: "6. 동사 (행동/변화)", zh: "放", py: "fàng", mean: "놓다, 석방하다" },
        { id: 127, category: "6. 동사 (행동/변화)", zh: "洗澡", py: "xǐzǎo", mean: "목욕하다" },
        { id: 128, category: "6. 동사 (행동/변화)", zh: "完成", py: "wánchéng", mean: "완성하다" },
        { id: 129, category: "6. 동사 (행동/변화)", zh: "搬家", py: "bānjiā", mean: "이사하다" },
        { id: 130, category: "6. 동사 (행동/변화)", zh: "照顾", py: "zhàogù", mean: "돌보다" },
        { id: 131, category: "6. 동사 (행동/변화)", zh: "帮忙", py: "bāngmáng", mean: "도와주다" },
        { id: 132, category: "6. 동사 (행동/변화)", zh: "检查", py: "jiǎnchá", mean: "검사하다" },
        { id: 133, category: "6. 동사 (행동/변화)", zh: "生病", py: "shēngbìng", mean: "병이 나다" },
        { id: 134, category: "6. 동사 (행동/변화)", zh: "带伞", py: "dài sǎn", mean: "우산을 지참하다" },
        { id: 135, category: "6. 동사 (행동/변화)", zh: "关门", py: "guānmén", mean: "문을 닫다" },
        { id: 136, category: "6. 동사 (행동/변화)", zh: "刷牙", py: "shuāyá", mean: "양치질하다" },
        { id: 137, category: "6. 동사 (행동/변화)", zh: "忘", py: "wàng", mean: "잊다" },
        { id: 138, category: "6. 동사 (행동/변화)", zh: "洗脸", py: "xǐliǎn", mean: "세수하다" },
        { id: 139, category: "6. 동사 (행동/변화)", zh: "经过", py: "jīngguò", mean: "지나다, 거치다" },
        { id: 140, category: "6. 동사 (행동/변화)", zh: "遇到", py: "yùdào", mean: "만나다, 부딪히다" },
        { id: 141, category: "6. 동사 (행동/변화)", zh: "讲", py: "jiǎng", mean: "말하다, 강의하다" },
        { id: 142, category: "6. 동사 (행동/변화)", zh: "认识", py: "rènshi", mean: "알다, 인식하다" },
        { id: 143, category: "6. 동사 (행동/변화)", zh: "表演", py: "biǎoyǎn", mean: "연기하다, 공연하다" },
        { id: 144, category: "6. 동사 (행동/변화)", zh: "刮风", py: "guāfēng", mean: "바람이 불다" },
        { id: 145, category: "6. 동사 (행동/변화)", zh: "旅游", py: "lǚyóu", mean: "여행하다" },

        // --- 7. 심리 / 상태 / 형용사 ---
        { id: 146, category: "7. 심리/상태/형용사", zh: "注意", py: "zhùyì", mean: "주의하다" },
        { id: 147, category: "7. 심리/상태/형용사", zh: "着急", py: "zháojí", mean: "조급해하다" },
        { id: 148, category: "7. 심리/상태/형용사", zh: "瘦了", py: "shòule", mean: "살이 빠졌다" },
        { id: 149, category: "7. 심리/상태/형용사", zh: "认真", py: "rènzhēn", mean: "진지하다, 열심히 하다" },
        { id: 150, category: "7. 심리/상태/형용사", zh: "相信", py: "xiāngxìn", mean: "믿다" },
        { id: 151, category: "7. 심리/상태/형용사", zh: "害怕", py: "hàipà", mean: "두려워하다" },
        { id: 152, category: "7. 심리/상태/형용사", zh: "长胖", py: "zhǎng pàng", mean: "살이 찌다" },
        { id: 153, category: "7. 심리/상태/형용사", zh: "愿意", py: "yuànyì", mean: "원하다, 동의하다" },
        { id: 154, category: "7. 심리/상태/형용사", zh: "希望", py: "xīwàng", mean: "희망하다" },
        { id: 155, category: "7. 심리/상태/형용사", zh: "客气", py: "kèqi", mean: "객기 부리다, 예의 바르다" },
        { id: 156, category: "7. 심리/상태/형용사", zh: "认为", py: "rènwéi", mean: "여기다, 생각하다" },
        { id: 157, category: "7. 심리/상태/형용사", zh: "有名", py: "yǒumíng", mean: "유명하다" },
        { id: 158, category: "7. 심리/상태/형용사", zh: "兴趣", py: "xìngqù", mean: "흥미, 관심" },
        { id: 159, category: "7. 심리/상태/형용사", zh: "便宜", py: "piányi", mean: "싸다" },
        { id: 160, category: "7. 심리/상태/형용사", zh: "关心", py: "guānxīn", mean: "관심을 가지다" },
        { id: 161, category: "7. 심리/상태/형용사", zh: "担心", py: "dānxīn", mean: "걱정하다" },
        { id: 162, category: "7. 심리/상태/형용사", zh: "发烧", py: "fāshāo", mean: "열이 나다" },
        { id: 163, category: "7. 심리/상태/형용사", zh: "感冒", py: "gǎnmào", mean: "감기 걸리다" },
        { id: 164, category: "7. 심리/상태/형용사", zh: "奇怪", py: "qíguài", mean: "이상하다, 기이하다" },
        { id: 165, category: "7. 심리/상태/형용사", zh: "安静", py: "ānjìng", mean: "조용하다" },
        { id: 166, category: "7. 심리/상태/형용사", zh: "了解", py: "liǎojiě", mean: "이해하다, 잘 알다" },
        { id: 167, category: "7. 심리/상태/형용사", zh: "意思", py: "yìsi", mean: "뜻, 의미" },
        { id: 168, category: "7. 심리/상태/형용사", zh: "疼", py: "téng", mean: "아프다" },
        { id: 169, category: "7. 심리/상태/형용사", zh: "觉得", py: "juéde", mean: "~라고 생각하다" },
        { id: 170, category: "7. 심리/상태/형용사", zh: "容易", py: "róngyì", mean: "쉽다" },
        { id: 171, category: "7. 심리/상태/형용사", zh: "累", py: "lèi", mean: "피곤하다" },
        { id: 172, category: "7. 심리/상태/형용사", zh: "短", py: "duǎn", mean: "짧다" },
        { id: 173, category: "7. 심리/상태/형용사", zh: "懂", py: "dǒng", mean: "이해하다, 알다" },
        { id: 174, category: "7. 심리/상태/형용사", zh: "明白", py: "míngbai", mean: "명백하다, 알다" },
        { id: 175, category: "7. 심리/상태/형용사", zh: "怕", py: "pà", mean: "무서워하다" },
        { id: 176, category: "7. 심리/상태/형용사", zh: "决定", py: "juédìng", mean: "결정하다" },
        { id: 177, category: "7. 심리/상태/형용사", zh: "敢", py: "gǎn", mean: "감히 ~하다" },
        { id: 178, category: "7. 심리/상태/형용사", zh: "清楚", py: "qīngchu", mean: " 또렷하다, 분명하다" },
        { id: 179, category: "7. 심리/상태/형용사", zh: "饿", py: "è", mean: "배고프다" },
        { id: 180, category: "7. 심리/상태/형용사", zh: "放心", py: "fàngxīn", mean: "안심하다" },
        { id: 181, category: "7. 심리/상태/형용사", zh: "裤子", py: "kùzi", mean: "바지" },
        { id: 182, category: "7. 심리/상태/형용사", zh: "胖", py: "pàng", mean: "뚱뚱하다" },
        { id: 183, category: "7. 심리/상태/형용사", zh: "可爱", py: "kě'ài", mean: "귀엽다" },
        { id: 184, category: "7. 심리/상태/형용사", zh: "渴", py: "kě", mean: "목마르다" },
        { id: 185, category: "7. 심리/상태/형용사", zh: "舒服", py: "shūfu", mean: "편안하다" },
        { id: 186, category: "7. 심리/상태/형용사", zh: "方便", py: "fāngbiàn", mean: "편리하다" },
        { id: 187, category: "7. 심리/상태/형용사", zh: "小心", py: "xiǎoxīn", mean: "조심하다" },
        { id: 188, category: "7. 심리/상태/형용사", zh: "漂亮", py: "piàoliang", mean: "예쁘다" },
        { id: 189, category: "7. 심리/상태/형용사", zh: "聪明", py: "cōngmíng", mean: "똑똑하다" },
        { id: 190, category: "7. 심리/상태/형용사", zh: "重要", py: "zhòngyào", mean: "중요하다" },
        { id: 191, category: "7. 심리/상태/형용사", zh: "快乐", py: "kuàilè", mean: "즐겁다" },
        { id: 192, category: "7. 심리/상태/형용사", zh: "爱好", py: "àihào", mean: "취미" },
        { id: 193, category: "7. 심리/상태/형용사", zh: "慢", py: "màn", mean: "느리다" },
        { id: 194, category: "7. 심리/상태/형용사", zh: "干净", py: "gānjìng", mean: "깨끗하다" },
        { id: 195, category: "7. 심리/상태/형용사", zh: "努力", py: "nǔlì", mean: "노력하다" },
        { id: 196, category: "7. 심리/상태/형용사", zh: "满意", py: "mǎnyì", mean: "만족하다" },
        { id: 197, category: "7. 심리/상태/형용사", zh: "虽然", py: "suīrán", mean: "비록 ~일지라도" },
        { id: 198, category: "7. 심리/상태/형용사", zh: "发现", py: "fāxiàn", mean: "발견하다" },
        { id: 199, category: "7. 심리/상태/형용사", zh: "变化", py: "biànhuà", mean: "변화" },
        { id: 200, category: "7. 심리/상태/형용사", zh: "根据", py: "gēnjù", mean: "~에 근거하다" },
        { id: 201, category: "7. 심리/상태/형용사", zh: "香蕉", py: "xiāngjiāo", mean: "바나나" },
        { id: 202, category: "7. 심리/상태/형용사", zh: "像", py: "xiàng", mean: "닮다, ~와 같다" },
        { id: 203, category: "7. ER/상태/형용사", zh: "葡萄", py: "pútáo", mean: "포도" },
        { id: 204, category: "7. 심리/상태/형용사", zh: "西瓜", py: "xīguā", mean: "수박" },
        { id: 205, category: "7. 심리/상태/형용사", zh: "比较", py: "bǐjiào", mean: "비교적" },
        { id: 206, category: "7. 심리/상태/형용사", zh: "简单", py: "jiǎndān", mean: "간단하다" },
        { id: 207, category: "7. 심리/상태/형용사", zh: "难过", py: "nánguò", mean: "괴롭다, 슬프다" },
        { id: 208, category: "7. 심리/상태/형용사", zh: "红", py: "hóng", mean: "빨갛다" },
        { id: 209, category: "7. 심리/상태/형용사", zh: "饱", py: "bǎo", mean: "배부르다" },
        { id: 210, category: "7. 심리/상태/형용사", zh: "甜", py: "tián", mean: "달다" },
        { id: 211, category: "7. 심리/상태/형용사", zh: "不接", py: "bù jiē", mean: "전화를 받지 않다" },
        { id: 212, category: "7. 심리/상태/형용사", zh: "坏了", py: "huài le", mean: "고장 나다" },

        // --- 8. 대명사 / 부사 / 조동사 ---
        { id: 213, category: "8. 대명사/부사/조동사", zh: "例如", py: "lìrú", mean: "예를 들면" },
        { id: 214, category: "8. 대명사/부사/조동사", zh: "一直", py: "yīzhí", mean: "줄곧, 똑바로" },
        { id: 215, category: "8. 대명사/부사/조동사", zh: "需要", py: "xūyào", mean: "필요하다" },
        { id: 216, category: "8. 대명사/부사/조동사", zh: "必须", py: "bìxū", mean: "반드시" },
        { id: 217, category: "8. 대명사/부사/조동사", zh: "已经", py: "yǐjīng", mean: "이미" },
        { id: 218, category: "8. 대명사/부사/조동사", zh: "只是", py: "zhǐshì", mean: "단지, 다만" },
        { id: 219, category: "8. 대명사/부사/조동사", zh: "总是", py: "zǒngshì", mean: "늘, 언제나" },
        { id: 220, category: "8. 대명사/부사/조동사", zh: "以为", py: "yǐwéi", mean: "~인 줄 알았다" },
        { id: 221, category: "8. 대명사/부사/조동사", zh: "如果", py: "rúguǒ", mean: "만약" },
        { id: 222, category: "8. 대명사/부사/조동사", zh: "还", py: "hái", mean: "아직, 또한" },
        { id: 223, category: "8. 대명사/부사/조동사", zh: "自已", py: "zìjǐ", mean: "자신" },
        { id: 224, category: "8. 대명사/부사/조동사", zh: "更", py: "gèng", mean: "더욱, 더" },
        { id: 225, category: "8. 대명사/부사/조동사", zh: "才", py: "cái", mean: "겨우, 이제야" },
        { id: 226, category: "8. 대명사/부사/조동사", zh: "那块儿", py: "nà kuàir", mean: "그곳, 저기" },
        { id: 227, category: "8. 대명사/부사/조동사", zh: "这样的", py: "zhèyàng de", mean: "이러한" },
        { id: 228, category: "8. 대명사/부사/조동사", zh: "只能", py: "zhǐ néng", mean: "오직 ~할 수밖에 없다" },
        { id: 229, category: "8. 대명사/부사/조동사", zh: "别的", py: "biéde", mean: "다른 것" },
        { id: 230, category: "8. 대명사/부사/조동사", zh: "都会", py: "dōu huì", mean: "모두 ~할 것이다" },
        { id: 231, category: "8. 대명사/부사/조동사", zh: "而且", py: "érqiě", mean: "게다가, 게다가" },
        { id: 232, category: "8. 대명사/부사/조동사", zh: "特别", py: "tèbié", mean: "특히, 특별히" },
        { id: 233, category: "8. 대명사/부사/조동사", zh: "然后", py: "ránhòu", mean: "그러고 나서" },
        { id: 234, category: "8. 대명사/부사/조동사", zh: "不错", py: "búcuò", mean: "좋다, 괜찮다" },
        { id: 235, category: "8. 대명사/부사/조동사", zh: "只要", py: "zhǐyào", mean: "~하기만 하면" },
        { id: 236, category: "8. 대명사/부사/조동사", zh: "好些", py: "hǎoxiē", mean: "제법 많은, 훨씬 나아지다" },
        { id: 237, category: "8. 대명사/부사/조동사", zh: "这么", py: "zhème", mean: "이렇게, 이토록" },
        { id: 238, category: "8. 대명사/부사/조동사", zh: "关于", py: "guānyú", mean: "~에 관하여" },
        { id: 239, category: "8. 대명사/부사/조동사", zh: "没找到", py: "méi zhǎodào", mean: "찾지 못했다" },
        { id: 240, category: "8. 대명사/부사/조동사", zh: "很少", py: "hěn shǎo", mean: "매우 드물다, 적다" },
        { id: 241, category: "8. 대명사/부사/조동사", zh: "旧", py: "jiù", mean: "낡다, 오래되다" },
        { id: 242, category: "8. 대명사/부사/조동사", zh: "应该", py: "yīnggāi", mean: "마땅히 ~해야 한다" },
        { id: 243, category: "8. 대명사/부사/조동사", zh: "当然", py: "dāngrán", mean: "당연히" },
        { id: 244, category: "8. 대명사/부사/조동사", zh: "向", py: "xiàng", mean: "~를 향하여" },
        { id: 245, category: "8. 대명사/부사/조동사", zh: "只有", py: "zhǐyǒu", mean: "오직 ~만이" },
        { id: 246, category: "8. 대명사/부사/조동사", zh: "一些", py: "yìxiē", mean: "조금, 약간" },
        { id: 247, category: "8. 대명사/부사/조동사", zh: "关小", py: "guān xiǎo", mean: "(소리를) 줄이다" },
        { id: 248, category: "8. 대명사/부사/조동사", zh: "终于", py: "zhōngyú", mean: "마침내, 드디어" },
        { id: 249, category: "8. 대명사/부사/조동사", zh: "最好", py: "zuìhǎo", mean: "가장 좋은 것, 가장 좋기는" },
        { id: 250, category: "8. 대명사/부사/조동사", zh: "有些", py: "yǒuxiē", mean: "약간, 조금" },
        { id: 251, category: "8. 대명사/부사/조동사", zh: "其实", py: "qíshí", mean: "사실은, 실제로는" },
        { id: 252, category: "8. 대명사/부사/조동사", zh: "低", py: "dī", mean: "낮다" },
        { id: 253, category: "8. 대명사/부사/조동사", zh: "被", py: "bèi", mean: "~에게 ~를 당하다 (피동)" },
        { id: 254, category: "8. 대명사/부사/조동사", zh: "一定", py: "yídìng", mean: "반드시, 꼭" },
        { id: 255, category: "8. 대명사/부사/조동사", zh: "别忘了", py: "bié wàng le", mean: "잊지 마라" },
        { id: 256, category: "8. 대명사/부사/조동사", zh: "最少", py: "zuìshǎo", mean: "최소한, 적어도" },
        { id: 257, category: "8. 대명사/부사/조동사", zh: "差点儿", py: "chàdiǎnr", mean: "하마터면, 하마터면 면하다" },
        { id: 258, category: "8. 대명사/부사/조동사", zh: "没办法", py: "méi bànfǎ", mean: "할 수 없다, 방법이 없다" },
        { id: 259, category: "8. 대명사/부사/조동사", zh: "几乎", py: "jīhū", mean: "거의" },
        { id: 260, category: "8. 대명사/부사/조동사", zh: "久", py: "jiǔ", mean: "오래다, 오랫동안" },
        { id: 261, category: "8. 대명사/부사/조동사", zh: "一般", py: "yìbān", mean: "일반적으로, 보통" },
        { id: 262, category: "8. 대명사/부사/조동사", zh: "越来越多", py: "yuè lái yuè duō", mean: "갈수록 많아지다" },
        { id: 263, category: "8. 대명사/부사/조동사", zh: "主要", py: "zhǔyào", mean: "주요하다, 주로" },

        // --- 9. 조사 / 접속사 / 수사 / 양사 / 기타 ---
        { id: 264, category: "9. 접속사/수사/양사/기타", zh: "共", py: "gòng", mean: "총, 모두" },
        { id: 265, category: "9. 접속사/수사/양사/기타", zh: "或者", py: "huòzhě", mean: "또는, 혹은" },
        { id: 266, category: "9. 접속사/수사/양사/기타", zh: "从", py: "cóng", mean: "~로부터" },
        { id: 267, category: "9. 접속사/수사/양사/기타", zh: "辆", py: "liàng", mean: "대 (차량을 세는 단위)" },
        { id: 268, category: "9. 접속사/수사/양사/기타", zh: "万", py: "wàn", mean: "만 (10,000)" },
        { id: 269, category: "9. 접속사/수사/양사/기타", zh: "是因为", py: "shì yīnwèi", mean: "~때문이다" },
        { id: 270, category: "9. 접속사/수사/양사/기타", zh: "但", py: "dàn", mean: "그러나, 하지만" },
        { id: 271, category: "9. 접속사/수사/양사/기타", zh: "为了", py: "wèile", mean: "~을 위하여" },
        { id: 272, category: "9. 접속사/수사/양사/기타", zh: "所以", py: "suǒyǐ", mean: "그래서, 그러므로" },
        { id: 273, category: "9. 접속사/수사/양사/기타", zh: "机会", py: "jīhuì", mean: "기회" },
        { id: 274, category: "9. 접속사/수사/양사/기타", zh: "除了", py: "chúle", mean: "~을 제외하고" },
        { id: 275, category: "9. 접속사/수사/양사/기타", zh: "件", py: "jiàn", mean: "벌, 건 (옷이나 사건을 세는 단위)" },
        { id: 276, category: "9. 접속사/수사/양사/기타", zh: "对", py: "duì", mean: "~에 대해, 맞다" },
        { id: 277, category: "9. 접속사/수사/양사/기타", zh: "跟", py: "gēn", mean: "~와, ~를 따라서" },
        { id: 278, category: "9. 접속사/수사/양사/기타", zh: "天黑", py: "tiān hēi", mean: "날이 어둡다" },
        { id: 279, category: "9. 접속사/수사/양사/기타", zh: "表示", py: "biǎoshì", mean: "표시하다, 나타내다" },
        { id: 280, category: "9. 접속사/수사/양사/기타", zh: "票", py: "piào", mean: "표, 티켓" },
        { id: 281, category: "9. 접속사/수사/양사/기타", zh: "左", py: "zuǒ", mean: "왼쪽" },
        { id: 282, category: "9. 접속사/수사/양사/기타", zh: "蓝色", py: "lánsè", mean: "남색, 파란색" },
        { id: 283, category: "9. 접속사/수사/양사/기타", zh: "双", py: "shuāng", mean: "쌍, 켤레" },
        { id: 284, category: "9. 접속사/수사/양사/기타", zh: "关系", py: "guānxi", mean: "관계" },
        { id: 285, category: "9. 접속사/수사/양사/기타", zh: "国外", py: "guówài", mean: "해외, 국외" },
        { id: 286, category: "9. 접속사/수사/양사/기타", zh: "吓走五", py: "xià zǒu wǔ", mean: "위협하여 쫓아내다 (오타 가능성 있음)" },
        { id: 287, category: "9. 접속사/수사/양사/기타", zh: "为什么", py: "wèishénme", mean: "왜, 어째서" },
        { id: 288, category: "9. 접속사/수사/양사/기타", zh: "条", py: "tiáo", mean: "가닥, 조각 (바지/강 등을 세는 단위)" },
        { id: 289, category: "9. 접속사/수사/양사/기타", zh: "把", py: "bǎ", mean: "자루, 개 (손잡이가 있는 사물 또는 가구)" },
        { id: 290, category: "9. 접속사/수사/양사/기타", zh: "节", py: "jié", mean: "마디, 교시 (수업이나 축제를 세는 단위)" },
        { id: 291, category: "9. 접속사/수사/양사/기타", zh: "地", py: "de", mean: "부사격 조사 (~하게)" },
        { id: 292, category: "9. 접속사/수사/양사/기타", zh: "介绍", py: "jièshào", mean: "소개하다" },
        { id: 293, category: "9. 접속사/수사/양사/기타", zh: "作用", py: "zuòyòng", mean: "작용, 역할" }
    ]
};