vocabData["hsk2"] = {
    title: "HSK 2급",
    words: [
        // --- 1. 대명사 / 의문사 ---
        { id: 1, category: "1. 대명사/의문사", zh: "大家", py: "dàjiā", mean: "모두, 여러분" },
        { id: 2, category: "1. 대명사/의문사", zh: "您", py: "nín", mean: "당신 (존칭)" },
        { id: 3, category: "1. 대명사/의문사", zh: "它", py: "tā", mean: "그것 (사물/동물)" },
        { id: 4, category: "1. 대명사/의문사", zh: "为什么", py: "wèishénme", mean: "왜, 어째서" },
        { id: 5, category: "1. 대명사/의문사", zh: "每", py: "měi", mean: "매, 마다" },

        // --- 2. 명사 (사람/가족/직업) ---
        { id: 6, category: "2. 사람/가족", zh: "哥哥", py: "gēge", mean: "형, 오빠" },
        { id: 7, category: "2. 사람/가족", zh: "弟弟", py: "dìdi", mean: "남동생" },
        { id: 8, category: "2. 사람/가족", zh: "妹妹", py: "mèimei", mean: "여동생" },
        { id: 9, category: "2. 사람/가족", zh: "丈夫", py: "zhàngfu", mean: "남편" },
        { id: 10, category: "2. 사람/가족", zh: "妻子", py: "qīzi", mean: "아내" },
        { id: 11, category: "2. 사람/가족", zh: "孩子", py: "háizi", mean: "아이, 자녀" },
        { id: 12, category: "2. 사람/가족", zh: "男人", py: "nánrén", mean: "남자" },
        { id: 13, category: "2. 사람/가족", zh: "女人", py: "nǚrén", mean: "여자" },
        { id: 14, category: "2. 사람/가족", zh: "服务员", py: "fúwùyuán", mean: "종업원, 서비스원" },

        // --- 3. 명사 (사물/장소/시간) ---
        { id: 15, category: "3. 사물/장소", zh: "报纸", py: "bàozhǐ", mean: "신문" },
        { id: 16, category: "3. 사물/장소", zh: "宾馆", py: "bīnguǎn", mean: "호텔, 여관" },
        { id: 17, category: "3. 사물/장소", zh: "房间", py: "fángjiān", mean: "방" },
        { id: 18, category: "3. 사물/장소", zh: "教室", py: "jiàoshì", mean: "교실" },
        { id: 19, category: "3. 사물/장소", zh: "机场", py: "jīchǎng", mean: "공항" },
        { id: 20, category: "3. 사물/장소", zh: "路", py: "lù", mean: "길, 도로" },
        { id: 21, category: "3. 사물/장소", zh: "门", py: "mén", mean: "문" },
        { id: 22, category: "3. 사물/장소", zh: "票", py: "piào", mean: "표, 티켓" },
        { id: 23, category: "3. 사물/장소", zh: "铅笔", py: "qiānbǐ", mean: "연필" },
        { id: 24, category: "3. 사물/장소", zh: "手表", py: "shǒubiǎo", mean: "손목시계" },
        { id: 25, category: "3. 사물/장소", zh: "手机", py: "shǒujī", mean: "휴대폰" },
        { id: 26, category: "3. 사물/장소", zh: "事情", py: "shìqing", mean: "일, 사건" },
        { id: 27, category: "3. 사물/장소", zh: "意思", py: "yìsi", mean: "의미, 뜻" },
        { id: 28, category: "3. 사물/장소", zh: "课", py: "kè", mean: "수업, 과" },
        { id: 29, category: "3. 사물/장소", zh: "题", py: "tí", mean: "문제, 제목" },
        { id: 30, category: "3. 사물/장소", zh: "雪", py: "xuě", mean: "눈(Snow)" },
        { id: 31, category: "3. 사물/장소", zh: "药", py: "yào", mean: "약" },
        { id: 32, category: "3. 사물/장소", zh: "公共汽车", py: "gōnggòng qìchē", mean: "버스" },
        { id: 33, category: "3. 사물/장소", zh: "自行车", py: "zìxíngchē", mean: "자전거" },
        { id: 34, category: "3. 사물/장소", zh: "船", py: "chuán", mean: "배, 선박" },

        // --- 4. 명사 (음식/방위) ---
        { id: 35, category: "4. 음식/방위", zh: "鸡蛋", py: "jīdàn", mean: "계란" },
        { id: 36, category: "4. 음식/방위", zh: "咖啡", py: "kāfēi", mean: "커피" },
        { id: 37, category: "4. 음식/방위", zh: "面条", py: "miàntiáo", mean: "국수" },
        { id: 38, category: "4. 음식/방위", zh: "牛奶", py: "niúnǎi", mean: "우유" },
        { id: 39, category: "4. 음식/방위", zh: "羊肉", py: "yángròu", mean: "양고기" },
        { id: 40, category: "4. 음식/방위", zh: "西瓜", py: "xīguā", mean: "수박" },
        { id: 41, category: "4. 음식/방위", zh: "鱼", py: "yú", mean: "물고기, 생선" },
        { id: 42, category: "4. 음식/방위", zh: "左边", py: "zuǒbiān", mean: "왼쪽" },
        { id: 43, category: "4. 음식/방위", zh: "右边", py: "yòubiān", mean: "오른쪽" },
        { id: 44, category: "4. 음식/방위", zh: "旁边", py: "pángbiān", mean: "옆" },
        { id: 45, category: "4. 음식/방위", zh: "外面", py: "wàimiàn", mean: "밖, 바깥" },

        // --- 5. 동사 (행동/동작) ---
        { id: 46, category: "5. 동사 (동작)", zh: "穿", py: "chuān", mean: "입다, 신다" },
        { id: 47, category: "5. 동사 (동작)", zh: "洗", py: "xǐ", mean: "씻다, 빨다" },
        { id: 48, category: "5. 동사 (동작)", zh: "笑", py: "xiào", mean: "웃다" },
        { id: 49, category: "5. 동사 (동작)", zh: "哭", py: "kū", mean: "울다" },
        { id: 50, category: "5. 동사 (동작)", zh: "找", py: "zhǎo", mean: "찾다, 거슬러 주다" },
        { id: 51, category: "5. 동사 (동작)", zh: "给", py: "gěi", mean: "주다" },
        { id: 52, category: "5. 동사 (동작)", zh: "送", py: "sòng", mean: "보내다, 선물하다" },
        { id: 53, category: "5. 동사 (동작)", zh: "卖", py: "mài", mean: "팔다" },
        { id: 54, category: "5. 동사 (동작)", zh: "让", py: "ràng", mean: "양보하다, ~하게 하다" },
        { id: 55, category: "5. 동사 (동작)", zh: "进", py: "jìn", mean: "들어가다, 들어오다" },
        { id: 56, category: "5. 동사 (동작)", zh: "出", py: "chū", mean: "나가다, 나오다" },
        { id: 57, category: "5. 동사 (동작)", zh: "到", py: "dào", mean: "도착하다" },
        { id: 58, category: "5. 동사 (동작)", zh: "走", py: "zǒu", mean: "걷다, 가다" },
        { id: 59, category: "5. 동사 (동작)", zh: "等", py: "děng", mean: "기다리다" },
        { id: 60, category: "5. 동사 (동작)", zh: "起床", py: "qǐchuáng", mean: "일어나다, 기상하다" },
        { id: 61, category: "5. 동사 (동작)", zh: "上班", py: "shàngbān", mean: "출근하다" },
        { id: 62, category: "5. 동사 (동작)", zh: "休息", py: "xiūxi", mean: "쉬다, 휴식하다" },

        // --- 6. 동사 (인지/소통/기타) ---
        { id: 63, category: "6. 동사 (소통/기타)", zh: "知道", py: "zhīdào", mean: "알다" },
        { id: 64, category: "6. 동사 (소통/기타)", zh: "懂", py: "dǒng", mean: "이해하다, 알다" },
        { id: 65, category: "6. 동사 (소통/기타)", zh: "觉得", py: "juéde", mean: "~라고 생각하다, 느끼다" },
        { id: 66, category: "6. 동사 (소통/기타)", zh: "希望", py: "xīwàng", mean: "희망하다, 바라다" },
        { id: 67, category: "6. 동사 (소통/기타)", zh: "准备", py: "zhǔnbèi", mean: "준비하다" },
        { id: 68, category: "6. 동사 (소통/기타)", zh: "开始", py: "kāishǐ", mean: "시작하다" },
        { id: 69, category: "6. 동사 (소통/기타)", zh: "完", py: "wán", mean: "끝나다, 마치다" },
        { id: 70, category: "6. 동사 (소통/기타)", zh: "帮助", py: "bāngzhù", mean: "돕다" },
        { id: 71, category: "6. 동사 (소통/기타)", zh: "告诉", py: "gàosu", mean: "알려주다, 말하다" },
        { id: 72, category: "6. 동사 (소통/기타)", zh: "回答", py: "huídá", mean: "대답하다" },
        { id: 73, category: "6. 동사 (소통/기타)", zh: "介绍", py: "jièshào", mean: "소개하다" },
        { id: 74, category: "6. 동사 (소통/기타)", zh: "欢迎", py: "huānyíng", mean: "환영하다" },
        { id: 75, category: "6. 동사 (소통/기타)", zh: "生病", py: "shēngbìng", mean: "병에 걸리다" },
        { id: 76, category: "6. 동사 (소통/기타)", zh: "可能", py: "kěnéng", mean: "가능하다, 아마도" },
        { id: 77, category: "6. 동사 (소통/기타)", zh: "可以", py: "kěyǐ", mean: "~할 수 있다, 해도 좋다" },
        { id: 78, category: "6. 동사 (소통/기타)", zh: "要", py: "yào", mean: "원하다, ~해야 한다" },

        // --- 7. 여가 / 스포츠 ---
        { id: 79, category: "7. 여가/스포츠", zh: "唱歌", py: "chànggē", mean: "노래하다" },
        { id: 80, category: "7. 여가/스포츠", zh: "跳舞", py: "tiàowǔ", mean: "춤추다" },
        { id: 81, category: "7. 여가/스포츠", zh: "旅游", py: "lǚyóu", mean: "여행하다" },
        { id: 82, category: "7. 여가/스포츠", zh: "玩", py: "wán", mean: "놀다, 장난하다" },
        { id: 83, category: "7. 여가/스포츠", zh: "运动", py: "yùndòng", mean: "운동하다" },
        { id: 84, category: "7. 여가/스포츠", zh: "跑步", py: "pǎobù", mean: "달리기하다" },
        { id: 85, category: "7. 여가/스포츠", zh: "游泳", py: "yóuyǒng", mean: "수영하다" },
        { id: 86, category: "7. 여가/스포츠", zh: "打篮球", py: "dǎ lánqiú", mean: "농구하다" },
        { id: 87, category: "7. 여가/스포츠", zh: "踢足球", py: "tī zúqiú", mean: "축구하다" },

        // --- 8. 형용사 (상태/성질) ---
        { id: 88, category: "8. 형용사", zh: "好", py: "hǎo", mean: "좋다" },
        { id: 89, category: "8. 형용사", zh: "好吃", py: "hǎochī", mean: "맛있다" },
        { id: 90, category: "8. 형용사", zh: "大", py: "dà", mean: "크다" },
        { id: 91, category: "8. 형용사", zh: "小", py: "xiǎo", mean: "작다" },
        { id: 92, category: "8. 형용사", zh: "长", py: "cháng", mean: "길다" },
        { id: 93, category: "8. 형용사", zh: "高", py: "gāo", mean: "높다, 키가 크다" },
        { id: 94, category: "8. 형용사", zh: "新", py: "xīn", mean: "새롭다" },
        { id: 95, category: "8. 형용사", zh: "贵", py: "guì", mean: "비싸다" },
        { id: 96, category: "8. 형용사", zh: "便宜", py: "piányi", mean: "싸다, 저렴하다" },
        { id: 97, category: "8. 형용사", zh: "远", py: "yuǎn", mean: "멀다" },
        { id: 98, category: "8. 형용사", zh: "近", py: "jìn", mean: "가깝다" },
        { id: 99, category: "8. 형용사", zh: "快", py: "kuài", mean: "빠르다" },
        { id: 100, category: "8. 형용사", zh: "慢", py: "màn", mean: "느리다" },
        { id: 101, category: "8. 형용사", zh: "忙", py: "máng", mean: "바쁘다" },
        { id: 102, category: "8. 형용사", zh: "累", py: "lèi", mean: "피곤하다" },
        { id: 103, category: "8. 형용사", zh: "快乐", py: "kuàilè", mean: "즐겁다, 행복하다" },
        { id: 104, category: "8. 형용사", zh: "对", py: "duì", mean: "맞다, 옳다" },
        { id: 105, category: "8. 형용사", zh: "错", py: "cuò", mean: "틀리다, 잘못되다" },
        { id: 106, category: "8. 형용사", zh: "晴", py: "qíng", mean: "맑다" },
        { id: 107, category: "8. 형용사", zh: "阴", py: "yīn", mean: "흐리다" },

        // --- 9. 색상 ---
        { id: 108, category: "9. 색상", zh: "红", py: "hóng", mean: "붉다, 빨갛다" },
        { id: 109, category: "9. 색상", zh: "白", py: "bái", mean: "희다, 하얗다" },
        { id: 110, category: "9. 색상", zh: "黑", py: "hēi", mean: "검다, 까맣다" },

        // --- 10. 부사 ---
        { id: 111, category: "10. 부사", zh: "非常", py: "fēicháng", mean: "매우, 대단히" },
        { id: 112, category: "10. 부사", zh: "真", py: "zhēn", mean: "정말, 진짜로" },
        { id: 113, category: "10. 부사", zh: "最", py: "zuì", mean: "가장, 제일" },
        { id: 114, category: "10. 부사", zh: "也", py: "yě", mean: "~도 또한" },
        { id: 115, category: "10. 부사", zh: "还", py: "hái", mean: "아직, 여전히, 더" },
        { id: 116, category: "10. 부사", zh: "就", py: "jiù", mean: "곧, 바로" },
        { id: 117, category: "10. 부사", zh: "再", py: "zài", mean: "다시, 또 (미래)" },
        { id: 118, category: "10. 부사", zh: "正在", py: "zhèngzài", mean: "마침 ~하고 있다" },
        { id: 119, category: "10. 부사", zh: "已经", py: "yǐjīng", mean: "이미, 벌써" },
        { id: 120, category: "10. 부사", zh: "别", py: "bié", mean: "~하지 마라" },

        // --- 11. 전치사 / 접속사 ---
        { id: 121, category: "11. 전치사/접속사", zh: "比", py: "bǐ", mean: "~보다 (비교)" },
        { id: 122, category: "11. 전치사/접속사", zh: "从", py: "cóng", mean: "~부터 (기점)" },
        { id: 123, category: "11. 전치사/접속사", zh: "对", py: "duì", mean: "~에게, ~에 대하여" },
        { id: 124, category: "11. 전치사/접속사", zh: "离", py: "lí", mean: "~에서 떨어져 있다" },
        { id: 125, category: "11. 전치사/접속사", zh: "向", py: "xiàng", mean: "~을 향하여" },
        { id: 126, category: "11. 전치사/접속사", zh: "因为", py: "yīnwèi", mean: "왜냐하면, ~때문에" },
        { id: 127, category: "11. 전치사/접속사", zh: "所以", py: "suǒyǐ", mean: "그래서" },
        { id: 128, category: "11. 전치사/접속사", zh: "但是", py: "dànshì", mean: "그러나, 하지만" },

        // --- 12. 수사 / 양사 / 조사 ---
        { id: 129, category: "12. 수사/양사/조사", zh: "两", py: "liǎng", mean: "둘, 2 (양사 앞)" },
        { id: 130, category: "12. 수사/양사/조사", zh: "百", py: "bǎi", mean: "백 (100)" },
        { id: 131, category: "12. 수사/양사/조사", zh: "千", py: "qiān", mean: "천 (1,000)" },
        { id: 132, category: "12. 수사/양사/조사", zh: "第一", py: "dì-yī", mean: "제일, 첫째" },
        { id: 133, category: "12. 수사/양사/조사", zh: "次", py: "cì", mean: "번, 차례 (동량사)" },
        { id: 134, category: "12. 수사/양사/조사", zh: "件", py: "jiàn", mean: "벌, 건 (옷/일 양사)" },
        { id: 135, category: "12. 수사/양사/조사", zh: "公斤", py: "gōngjīn", mean: "킬로그램 (kg)" },
        { id: 136, category: "12. 수사/양사/조사", zh: "元", py: "yuán", mean: "원 (위안, 화폐 단위)" },
        { id: 137, category: "12. 수사/양사/조사", zh: "吧", py: "ba", mean: "~하자, ~지? (청유/추측)" },
        { id: 138, category: "12. 수사/양사/조사", zh: "得", py: "de", mean: "~하는 정도가 ~하다 (정도보어)" },
        { id: 139, category: "12. 수사/양사/조사", zh: "过", py: "guo", mean: "~한 적이 있다 (경험)" },
        { id: 140, category: "12. 수사/양사/조사", zh: "着", py: "zhe", mean: "~하고 있다 (상태 지속)" },

        // --- 13. 기타 기초 명사 (시간/날짜) ---
        { id: 141, category: "13. 기타 기초 단어", zh: "早上", py: "zǎoshang", mean: "아침" },
        { id: 142, category: "13. 기타 기초 단어", zh: "晚上", py: "wǎnshang", mean: "저녁, 밤" },
        { id: 143, category: "13. 기타 기초 단어", zh: "去年", py: "qùnián", mean: "작년" },
        { id: 144, category: "13. 기타 기초 단어", zh: "今年", py: "jīnnián", mean: "올해" },
        { id: 145, category: "13. 기타 기초 단어", zh: "明年", py: "míngnián", mean: "내년" },
        { id: 146, category: "13. 기타 기초 단어", zh: "生日", py: "shēngrì", mean: "생일" },
        { id: 147, category: "13. 기타 기초 단어", zh: "时间", py: "shíjiān", mean: "시간" },
        { id: 148, category: "13. 기타 기초 단어", zh: "小时", py: "xiǎoshí", mean: "시간 (Hour)" },
        { id: 149, category: "13. 기타 기초 단어", zh: "分钟", py: "fēnzhōng", mean: "분 (Minute)" },
        { id: 150, category: "13. 기타 기초 단어", zh: "问题", py: "wèntí", mean: "문제, 질문" }
    ]
};