vocabData["hsk3_past2"] = {
    title: "HSK 3급 기출2",
    words: [
        // --- 1. 사람 / 신체 ---
        { id: 1, category: "1. 사람/신체", zh: "脸", py: "liǎn", mean: "얼굴" },
        { id: 2, category: "1. 사람/신체", zh: "腿", py: "tuǐ", mean: "다리" },
        { id: 3, category: "1. 사람/신체", zh: "眼睛", py: "yǎnjing", mean: "눈" },
        { id: 4, category: "1. 사람/신체", zh: "脚", py: "jiǎo", mean: "발" },
        { id: 5, category: "1. 사람/신체", zh: "胖", py: "pàng", mean: "뚱뚱하다" },
        { id: 6, category: "1. 사람/신체", zh: "矮", py: "ǎi", mean: "키가 작다" },

        // --- 2. 사물 / 음식 / 장소 / 자연 ---
        { id: 7, category: "2. 사물/음식/장소", zh: "空调", py: "kōngtiáo", mean: "에어컨" },
        { id: 8, category: "2. 사물/음식/장소", zh: "蛋糕", py: "dàngāo", mean: "케이크" },
        { id: 9, category: "2. 사물/음식/장소", zh: "香蕉", py: "xiāngjiāo", mean: "바나나" },
        { id: 10, category: "2. 사물/음식/장소", zh: "杯子", py: "bēizi", mean: "컵, 잔" },
        { id: 11, category: "2. 사물/음식/장소", zh: "衬衫", py: "chènshān", mean: "셔츠" },
        { id: 12, category: "2. 사물/음식/장소", zh: "桌子", py: "zhuōzi", mean: "책상, 탁자" },
        { id: 13, category: "2. 사물/음식/장소", zh: "城市", py: "chéngshì", mean: "도시" },
        { id: 14, category: "2. 사물/음식/장소", zh: "地图", py: "dìtú", mean: "지도" },
        { id: 15, category: "2. 사물/음식/장소", zh: "环境", py: "huánjìng", mean: "환경" },
        { id: 16, category: "2. 사물/음식/장소", zh: "作业", py: "zuòyè", mean: "숙제" },
        { id: 17, category: "2. 사물/음식/장소", zh: "声音", py: "shēngyīn", mean: "소리" },
        { id: 18, category: "2. 사물/음식/장소", zh: "黑板", py: "hēibǎn", mean: "칠판" },
        { id: 19, category: "2. 사물/음식/장소", zh: "句子", py: "jùzi", mean: "문장" },
        { id: 20, category: "2. 사물/음식/장소", zh: "饮料", py: "yǐnliào", mean: "음료수" },
        { id: 21, category: "2. 사물/음식/장소", zh: "地铁", py: "dìtiě", mean: "지하철" },
        { id: 22, category: "2. 사물/음식/장소", zh: "鸡蛋", py: "jīdàn", mean: "계란" },
        { id: 23, category: "2. 사물/음식/장소", zh: "礼物", py: "lǐwù", mean: "선물" },
        { id: 24, category: "2. 사물/음식/장소", zh: "报纸", py: "bàozhǐ", mean: "신문" },
        { id: 25, category: "2. 사물/음식/장소", zh: "花瓶", py: "huāpíng", mean: "꽃병" },
        { id: 26, category: "2. 사물/음식/장소", zh: "太阳", py: "tàiyáng", mean: "태양, 해" },
        { id: 27, category: "2. 사물/음식/장소", zh: "铅笔", py: "qiānbǐ", mean: "연필" },
        { id: 28, category: "2. 사물/음식/장소", zh: "信用卡", py: "xìnyòngkǎ", mean: "신용카드" },
        { id: 29, category: "2. 사물/음식/장소", zh: "护照", py: "hùzhào", mean: "여권" },
        { id: 30, category: "2. 사물/음식/장소", zh: "房子", py: "fángzi", mean: "집, 건물" },
        { id: 31, category: "2. 사물/음식/장소", zh: "邮箱", py: "yóuxiāng", mean: "우체통, 메일함" },
        { id: 32, category: "2. 사물/음식/장소", zh: "邮件", py: "yóujiàn", mean: "우편물, 이메일" },
        { id: 33, category: "2. 사물/음식/장소", zh: "菜单", py: "càidān", mean: "메뉴판" },
        { id: 34, category: "2. 사물/음식/장소", zh: "成绩", py: "chéngjì", mean: "성적" },
        { id: 35, category: "2. 사물/음식/장소", zh: "电梯", py: "diàntī", mean: "엘리베이터" },
        { id: 36, category: "2. 사물/음식/장소", zh: "楼梯", py: "lóutī", mean: "계단" },
        { id: 37, category: "2. 사물/음식/장소", zh: "体育", py: "tǐyù", mean: "체육" },
        { id: 38, category: "2. 사물/음식/장소", zh: "街道", py: "jiēdào", mean: "거리, 길거리" },
        { id: 39, category: "2. 사물/음식/장소", zh: "词典", py: "cídiǎn", mean: "사전" },

        // --- 3. 동사 (행동 / 동작) ---
        { id: 40, category: "3. 동사 (행동/동작)", zh: "拿", py: "ná", mean: "들다, 쥐다" },
        { id: 41, category: "3. 동사 (행동/동작)", zh: "练习", py: "liànxí", mean: "연습하다" },
        { id: 42, category: "3. 동사 (행동/동작)", zh: "找", py: "zhǎo", mean: "찾다" },
        { id: 43, category: "3. 동사 (행동/동작)", zh: "叫住", py: "jiàozhù", mean: "불러 세우다" },
        { id: 44, category: "3. 동사 (행동/동작)", zh: "出错", py: "chūcuò", mean: "틀리다, 실수하다" },
        { id: 45, category: "3. 동사 (행동/동작)", zh: "打算", py: "dǎsuàn", mean: "계획하다, ~할 작정이다" },
        { id: 46, category: "3. 동사 (행동/동작)", zh: "留学", py: "liúxué", mean: "유학하다" },
        { id: 47, category: "3. 동사 (행동/동작)", zh: "准备", py: "zhǔnbèi", mean: "준비하다" },
        { id: 48, category: "3. 동사 (행동/동작)", zh: "进", py: "jìn", mean: "들어가다, 들어오다" },
        { id: 49, category: "3. 동사 (행동/동작)", zh: "放", py: "fàng", mean: "놓다, 두다" },
        { id: 50, category: "3. 동사 (행동/동작)", zh: "照顾", py: "zhàogù", mean: "돌보다" },
        { id: 51, category: "3. 동사 (행동/동작)", zh: "发烧", py: "fāshāo", mean: "열이 나다" },
        { id: 52, category: "3. 동사 (행동/동작)", zh: "请假", py: "qǐngjià", mean: "휴가를 내다" },
        { id: 53, category: "3. 동사 (행동/동작)", zh: "聊", py: "liáo", mean: "이야기하다" },
        { id: 54, category: "3. 동사 (행동/동작)", zh: "换", py: "huàn", mean: "바꾸다" },
        { id: 55, category: "3. 동사 (행동/동작)", zh: "游泳", py: "yóuyǒng", mean: "수영하다" },
        { id: 56, category: "3. 동사 (행동/동작)", zh: "带", py: "dài", mean: "챙기다, 데리고 가다" },
        { id: 57, category: "3. 동사 (행동/동작)", zh: "接", py: "jiē", mean: "받다, 마중하다" },
        { id: 58, category: "3. 동사 (행동/동작)", zh: "遇到", py: "yùdào", mean: "마주치다" },
        { id: 59, category: "3. 동사 (행동/동작)", zh: "离开", py: "líkāi", mean: "떠나다" },
        { id: 60, category: "3. 동사 (행동/동작)", zh: "锻炼", py: "duànliàn", mean: "단련하다, 운동하다" },
        { id: 61, category: "3. 동사 (행동/동작)", zh: "跑", py: "pǎo", mean: "달리다, 뛰다" },
        { id: 62, category: "3. 동사 (행동/동작)", zh: "提高", py: "tígāo", mean: "향상시키다, 높이다" },
        { id: 63, category: "3. 동사 (행동/동작)", zh: "决定", py: "juédìng", mean: "결정하다" },
        { id: 64, category: "3. 동사 (행동/동작)", zh: "了解", py: "liǎojiě", mean: "이해하다, 알아보다" },
        { id: 65, category: "3. 동사 (행동/동작)", zh: "经过", py: "jīngguò", mean: "거치다, 지나다" },
        { id: 66, category: "3. 동사 (행동/동작)", zh: "借", py: "jiè", mean: "빌리다" },
        { id: 67, category: "3. 동사 (행동/동작)", zh: "跳舞", py: "tiàowǔ", mean: "춤추다" },
        { id: 68, category: "3. 동사 (행동/동작)", zh: "刮风", py: "guāfēng", mean: "바람이 불다" },
        { id: 69, category: "3. 동사 (행동/동작)", zh: "选择", py: "xuǎnzé", mean: "선택하다" },
        { id: 70, category: "3. 동사 (행동/동작)", zh: "起飞", py: "qǐfēi", mean: "이륙하다" },
        { id: 71, category: "3. 동사 (행동/동작)", zh: "笑", py: "xiào", mean: "웃다" },

        // --- 4. 심리 / 상태 / 형용사 ---
        { id: 72, category: "4. 심리/상태/형용사", zh: "舒服", py: "shūfu", mean: "편안하다" },
        { id: 73, category: "4. 심리/상태/형용사", zh: "易", py: "yì", mean: "쉽다" },
        { id: 74, category: "4. 심리/상태/형용사", zh: "怕", py: "pà", mean: "두려워하다" },
        { id: 75, category: "4. 심리/상태/형용사", zh: "担心", py: "dānxīn", mean: "걱정하다" },
        { id: 76, category: "4. 심리/상태/형용사", zh: "健康", py: "jiànkāng", mean: "건강하다, 건강" },
        { id: 77, category: "4. 심리/상태/형용사", zh: "急", py: "jí", mean: "급하다, 조급하다" },
        { id: 78, category: "4. 심리/상태/형용사", zh: "清楚", py: "qīngchu", mean: "분명하다, 명확하다" },
        { id: 79, category: "4. 심리/상태/형용사", zh: "满意", py: "mǎnyì", mean: "만족하다" },
        { id: 80, category: "4. 심리/상태/형용사", zh: "聪明", py: "cōngmíng", mean: "똑똑하다" },
        { id: 81, category: "4. 심리/상태/형용사", zh: "愿意", py: "yuànyì", mean: "원하다, 기꺼이 ~하다" },
        { id: 82, category: "4. 심리/상태/형용사", zh: "害怕", py: "hàipà", mean: "무서워하다" },
        { id: 83, category: "4. 심리/상태/형용사", zh: "感兴趣", py: "gǎn xìngqù", mean: "흥미를 느끼다" },
        { id: 84, category: "4. 심리/상태/형용사", zh: "相信", py: "xiāngxìn", mean: "믿다" },
        { id: 85, category: "4. 심리/상태/형용사", zh: "容易", py: "róngyì", mean: "쉽다" },
        { id: 86, category: "4. 심리/상태/형용사", zh: "热情", py: "rèqíng", mean: "열정적이다, 친절하다" },
        { id: 87, category: "4. 심리/상태/형용사", zh: "黃", py: "huáng", mean: "노랗다" },
        { id: 88, category: "4. 심리/상태/형용사", zh: "綠色", py: "lǜsè", mean: "녹색" },

        // --- 5. 대명사 / 부사 / 양사 / 기타 ---
        { id: 89, category: "5. 부사/대명사/양사", zh: "但是", py: "dànshì", mean: "그러나" },
        { id: 90, category: "5. 부사/대명사/양사", zh: "几乎", py: "jīhū", mean: "거의" },
        { id: 91, category: "5. 부사/대명사/양사", zh: "经常", py: "jīngcháng", mean: "자주" },
        { id: 92, category: "5. 부사/대명사/양사", zh: "还", py: "hái", mean: "아직, 또 (돌려주다는 뜻도 있음)" },
        { id: 93, category: "5. 부사/대명사/양사", zh: "跟", py: "gēn", mean: "~와 함께, 따르다" },
        { id: 94, category: "5. 부사/대명사/양사", zh: "一定", py: "yídìng", mean: "반드시" },
        { id: 95, category: "5. 부사/대명사/양사", zh: "种", py: "zhǒng", mean: "종류 (양사)" },
        { id: 96, category: "5. 부사/대명사/양사", zh: "要求", py: "yāoqiú", mean: "요구(하다)" },
        { id: 97, category: "5. 부사/대명사/양사", zh: "为", py: "wèi", mean: "~을 위하여" },
        { id: 98, category: "5. 부사/대명사/양사", zh: "差点儿", py: "chàdiǎnr", mean: "하마터면" },
        { id: 99, category: "5. 부사/대명사/양사", zh: "才", py: "cái", mean: "비로소, 겨우" },
        { id: 100, category: "5. 부사/대명사/양사", zh: "所以", py: "suǒyǐ", mean: "그래서" },
        { id: 101, category: "5. 부사/대명사/양사", zh: "过", py: "guo", mean: "~한 적이 있다 (동태조사)" },
        { id: 102, category: "5. 부사/대명사/양사", zh: "认为", py: "rènwéi", mean: "~라고 여기다" },
        { id: 103, category: "5. 부사/대명사/양사", zh: "总是", py: "zǒngshì", mean: "늘, 항상" },
        { id: 104, category: "5. 부사/대명사/양사", zh: "如果", py: "rúguǒ", mean: "만약" },
        { id: 105, category: "5. 부사/대명사/양사", zh: "方便", py: "fāngbiàn", mean: "편리하다" },
        { id: 106, category: "5. 부사/대명사/양사", zh: "总", py: "zǒng", mean: "늘, 총" },
        { id: 107, category: "5. 부사/대명사/양사", zh: "水平", py: "shuǐpíng", mean: "수준" },
        { id: 108, category: "5. 부사/대명사/양사", zh: "往", py: "wǎng", mean: "~를 향하여" },
        { id: 109, category: "5. 부사/대명사/양사", zh: "一直", py: "yìzhí", mean: "줄곧" },
        { id: 110, category: "5. 부사/대명사/양사", zh: "刚才", py: "gāngcái", mean: "방금" },
        { id: 111, category: "5. 부사/대명사/양사", zh: "其实", py: "qíshí", mean: "사실은" },
        { id: 112, category: "5. 부사/대명사/양사", zh: "只是", py: "zhǐshì", mean: "단지 ~일 뿐이다" },
        { id: 113, category: "5. 부사/대명사/양사", zh: "常", py: "cháng", mean: "자주" },
        { id: 114, category: "5. 부사/대명사/양사", zh: "突然", py: "tūrán", mean: "갑자기" },
        { id: 115, category: "5. 부사/대명사/양사", zh: "影响", py: "yǐngxiǎng", mean: "영향(을 주다)" },
        { id: 116, category: "5. 부사/대명사/양사", zh: "段", py: "duàn", mean: "단락, 구간 (양사)" },
        { id: 117, category: "5. 부사/대명사/양사", zh: "根据", py: "gēnjù", mean: "~에 근거하여" },
        { id: 118, category: "5. 부사/대명사/양사", zh: "习惯", py: "xíguàn", mean: "습관" },
        { id: 119, category: "5. 부사/대명사/양사", zh: "应该", py: "yīnggāi", mean: "마땅히 ~해야 한다" },
        { id: 120, category: "5. 부사/대명사/양사", zh: "终于", py: "zhōngyú", mean: "마침내" },
        { id: 121, category: "5. 부사/대명사/양사", zh: "万", py: "wàn", mean: "만 (숫자)" },
        { id: 122, category: "5. 부사/대명사/양사", zh: "除了", py: "chúle", mean: "~을 제외하고" }
    ]
};