vocabData["hsk3"] = {
    title: "HSK 3급",
    words: [
        // --- 1. 명사 (사람/가족/직업) ---
        { id: 1, category: "1. 사람/직업", zh: "阿姨", py: "āyí", mean: "이모, 아주머니" },
        { id: 2, category: "1. 사람/직업", zh: "叔叔", py: "shūshu", mean: "삼촌, 아저씨" },
        { id: 3, category: "1. 사람/직업", zh: "爷爷", py: "yéye", mean: "할아버지" },
        { id: 4, category: "1. 사람/직업", zh: "奶奶", py: "nǎinai", mean: "할머니" },
        { id: 5, category: "1. 사람/직업", zh: "邻居", py: "línjū", mean: "이웃" },
        { id: 6, category: "1. 사람/직업", zh: "同事", py: "tóngshì", mean: "직장 동료" },
        { id: 7, category: "1. 사람/직업", zh: "经理", py: "jīnglǐ", mean: "매니저, 사장" },
        { id: 8, category: "1. 사람/직업", zh: "客人", py: "kèrén", mean: "손님" },
        { id: 9, category: "1. 사람/직업", zh: "司机", py: "sījī", mean: "기사, 운전사" },
        { id: 10, category: "1. 사람/직업", zh: "校长", py: "xiàozhǎng", mean: "교장 총장" },

        // --- 2. 명사 (장소/공간) ---
        { id: 11, category: "2. 장소/공간", zh: "银行", py: "yínháng", mean: "은행" },
        { id: 12, category: "2. 장소/공간", zh: "超市", py: "chāoshì", mean: "슈퍼마켓" },
        { id: 13, category: "2. 장소/공간", zh: "公园", py: "gōngyuán", mean: "공원" },
        { id: 14, category: "2. 장소/공간", zh: "图书馆", py: "túshūguǎn", mean: "도서관" },
        { id: 15, category: "2. 장소/공간", zh: "办公室", py: "bàngōngshì", mean: "사무실" },
        { id: 16, category: "2. 장소/공간", zh: "洗手间", py: "xǐshǒujiān", mean: "화장실" },
        { id: 17, category: "2. 장소/공간", zh: "电梯", py: "diàntī", mean: "엘리베이터" },
        { id: 18, category: "2. 장소/공간", zh: "街道", py: "jiēdào", mean: "거리, 길거리" },
        { id: 19, category: "2. 장소/공간", zh: "城市", py: "chéngshì", mean: "도시" },
        { id: 20, category: "2. 장소/공간", zh: "地方", py: "dìfang", mean: "장소, 곳" },

        // --- 3. 명사 (사물/생활용품) ---
        { id: 21, category: "3. 사물/생활용품", zh: "护照", py: "hùzhào", mean: "여권" },
        { id: 22, category: "3. 사물/생활용품", zh: "信用卡", py: "xìnyòngkǎ", mean: "신용카드" },
        { id: 23, category: "3. 사물/생활용품", zh: "钱包", py: "qiánbāo", mean: "지갑" },
        { id: 24, category: "3. 사물/생활용품", zh: "行李箱", py: "xínglǐxiāng", mean: "캐리어, 트렁크" },
        { id: 25, category: "3. 사물/생활용품", zh: "伞", py: "sǎn", mean: "우산" },
        { id: 26, category: "3. 사물/생활용품", zh: "鞋", py: "xié", mean: "신발" },
        { id: 27, category: "3. 사물/생활용품", zh: "裙子", py: "qúnzi", mean: "치마" },
        { id: 28, category: "3. 사물/생활용품", zh: "裤子", py: "kùzi", mean: "바지" },
        { id: 29, category: "3. 사물/생활용품", zh: "衬衫", py: "chènshān", mean: "셔츠" },
        { id: 30, category: "3. 사물/생활용품", zh: "词典", py: "cídiǎn", mean: "사전" },
        { id: 31, category: "3. 사물/생활용품", zh: "菜单", py: "càidān", mean: "메뉴판" },
        { id: 32, category: "3. 사물/생활용품", zh: "空调", py: "kōngtiáo", mean: "에어컨" },
        { id: 33, category: "3. 사물/생활용품", zh: "冰箱", py: "bīngxiāng", mean: "냉장고" },
        { id: 34, category: "3. 사물/생활용품", zh: "照片", py: "zhàopiàn", mean: "사진" },
        { id: 35, category: "3. 사물/생활용품", zh: "照相机", py: "zhàoxiàngjī", mean: "카메라" },

        // --- 4. 명사 (시간/계절/추상) ---
        { id: 36, category: "4. 시간/계절/추상", zh: "季节", py: "jìjié", mean: "계절" },
        { id: 37, category: "4. 시간/계절/추상", zh: "春", py: "chūn", mean: "봄" },
        { id: 38, category: "4. 시간/계절/추상", zh: "夏", py: "xià", mean: "여름" },
        { id: 39, category: "4. 시간/계절/추상", zh: "秋", py: "qiū", mean: "가을" },
        { id: 40, category: "4. 시간/계절/추상", zh: "冬", py: "dōng", mean: "겨울" },
        { id: 41, category: "4. 시간/계절/추상", zh: "周末", py: "zhōumò", mean: "주말" },
        { id: 42, category: "4. 시간/계절/추상", zh: "节日", py: "jiérì", mean: "명절, 기념일" },
        { id: 43, category: "4. 시간/계절/추상", zh: "历史", py: "lìshǐ", mean: "역사" },
        { id: 44, category: "4. 시간/계절/추상", zh: "故事", py: "gùshi", mean: "이야기" },
        { id: 45, category: "4. 시간/계절/추상", zh: "声音", py: "shēngyīn", mean: "소리, 목소리" },
        { id: 46, category: "4. 시간/계절/추상", zh: "爱好", py: "àihào", mean: "취미" },
        { id: 47, category: "4. 시간/계절/추상", zh: "习惯", py: "xíguàn", mean: "습관" },
        { id: 48, category: "4. 시간/계절/추상", zh: "新闻", py: "xīnwén", mean: "뉴스" },
        { id: 49, category: "4. 시간/계절/추상", zh: "会议", py: "huìyì", mean: "회의" },
        { id: 50, category: "4. 시간/계절/추상", zh: "机会", py: "jīhuì", mean: "기회" },

        // --- 5. 동사 (신체/물리적 동작) ---
        { id: 51, category: "5. 동사 (물리적 동작)", zh: "搬", py: "bān", mean: "옮기다, 이사하다" },
        { id: 52, category: "5. 동사 (물리적 동작)", zh: "帮忙", py: "bāngmáng", mean: "도와주다" },
        { id: 53, category: "5. 동사 (물리적 동작)", zh: "打扫", py: "dǎsǎo", mean: "청소하다" },
        { id: 54, category: "5. 동사 (물리적 동작)", zh: "洗澡", py: "xǐzǎo", mean: "목욕하다, 샤워하다" },
        { id: 55, category: "5. 동사 (물리적 동작)", zh: "刷牙", py: "shuāyá", mean: "양치질하다" },
        { id: 56, category: "5. 동사 (물리적 동작)", zh: "拿", py: "ná", mean: "들다, 쥐다, 가져오다" },
        { id: 57, category: "5. 동사 (물리적 동작)", zh: "放", py: "fàng", mean: "놓다, 두다" },
        { id: 58, category: "5. 동사 (물리적 동작)", zh: "换", py: "huàn", mean: "바꾸다, 교환하다" },
        { id: 59, category: "5. 동사 (물리적 동작)", zh: "借", py: "jiè", mean: "빌리다, 빌려주다" },
        { id: 60, category: "5. 동사 (물리적 동작)", zh: "还", py: "huán", mean: "돌려주다, 반납하다" },
        { id: 61, category: "5. 동사 (물리적 동작)", zh: "爬山", py: "páshān", mean: "등산하다" },
        { id: 62, category: "5. 동사 (물리적 동작)", zh: "骑", py: "qí", mean: "(자전거/말 등을) 타다" },
        { id: 63, category: "5. 동사 (물리적 동작)", zh: "起飞", py: "qǐfēi", mean: "이륙하다" },
        { id: 64, category: "5. 동사 (물리적 동작)", zh: "上网", py: "shàngwǎng", mean: "인터넷을 하다" },
        { id: 65, category: "5. 동사 (물리적 동작)", zh: "发烧", py: "fāshāo", mean: "열이 나다" },

        // --- 6. 동사 (상태/인지/소통) ---
        { id: 66, category: "6. 동사 (인지/소통)", zh: "参加", py: "cānjiā", mean: "참가하다" },
        { id: 67, category: "6. 동사 (인지/소통)", zh: "举行", py: "jǔxíng", mean: "개최하다, 열다" },
        { id: 68, category: "6. 동사 (인지/소통)", zh: "发现", py: "fāxiàn", mean: "발견하다, 알아차리다" },
        { id: 69, category: "6. 동사 (인지/소통)", zh: "解决", py: "jiějué", mean: "해결하다" },
        { id: 70, category: "6. 동사 (인지/소통)", zh: "离开", py: "líkāi", mean: "떠나다, 벗어나다" },
        { id: 71, category: "6. 동사 (인지/소통)", zh: "聊天", py: "liáotiān", mean: "수다 떨다, 채팅하다" },
        { id: 72, category: "6. 동사 (인지/소통)", zh: "必须", py: "bìxū", mean: "반드시 ~해야 한다" },
        { id: 73, category: "6. 동사 (인지/소통)", zh: "需要", py: "xūyào", mean: "필요하다, 요구되다" },
        { id: 74, category: "6. 동사 (인지/소통)", zh: "变化", py: "biànhuà", mean: "변화하다" },
        { id: 75, category: "6. 동사 (인지/소통)", zh: "表示", py: "biǎoshì", mean: "표시하다, 나타내다" },
        { id: 76, category: "6. 동사 (인지/소통)", zh: "担心", py: "dānxīn", mean: "걱정하다" },
        { id: 77, category: "6. 동사 (인지/소통)", zh: "放心", py: "fàngxīn", mean: "안심하다" },
        { id: 78, category: "6. 동사 (인지/소통)", zh: "记得", py: "jìde", mean: "기억하고 있다" },
        { id: 79, category: "6. 동사 (인지/소통)", zh: "忘记", py: "wàngjì", mean: "잊다, 까먹다" },
        { id: 80, category: "6. 동사 (인지/소통)", zh: "决定", py: "juédìng", mean: "결정하다" },
        { id: 81, category: "6. 동사 (인지/소통)", zh: "了解", py: "liǎojiě", mean: "자세히 알다, 이해하다" },
        { id: 82, category: "6. 동사 (인지/소통)", zh: "明白", py: "míngbai", mean: "명백히 알다, 이해하다" },
        { id: 83, category: "6. 동사 (인지/소통)", zh: "认为", py: "rènwéi", mean: "여기다, 생각하다" },
        { id: 84, category: "6. 동사 (인지/소통)", zh: "相信", py: "xiāngxìn", mean: "믿다, 신뢰하다" },
        { id: 85, category: "6. 동사 (인지/소통)", zh: "选择", py: "xuǎnzé", mean: "선택하다" },
        { id: 86, category: "6. 동사 (인지/소통)", zh: "同意", py: "tóngyì", mean: "동의하다" },
        { id: 87, category: "6. 동사 (인지/소통)", zh: "以为", py: "yǐwéi", mean: "~인 줄 알았다 (착각)" },
        { id: 88, category: "6. 동사 (인지/소통)", zh: "遇到", py: "yùdào", mean: "마주치다, 조우하다" },
        { id: 89, category: "6. 동사 (인지/소통)", zh: "照顾", py: "zhàogù", mean: "돌보다, 보살피다" },
        { id: 90, category: "6. 동사 (인지/소통)", zh: "注意", py: "zhùyì", mean: "주의하다, 조심하다" },
        { id: 91, category: "6. 동사 (인지/소통)", zh: "祝", py: "zhù", mean: "축하하다, 기원하다" },
        { id: 92, category: "6. 동사 (인지/소통)", zh: "要求", py: "yāoqiú", mean: "요구하다" },
        { id: 93, category: "6. 동사 (인지/소통)", zh: "影响", py: "yǐngxiǎng", mean: "영향을 주다" },

        // --- 7. 형용사 (외모/상태) ---
        { id: 94, category: "7. 형용사", zh: "胖", py: "pàng", mean: "뚱뚱하다" },
        { id: 95, category: "7. 형용사", zh: "瘦", py: "shòu", mean: "마르다" },
        { id: 96, category: "7. 형용사", zh: "矮", py: "ǎi", mean: "키가 작다" },
        { id: 97, category: "7. 형용사", zh: "旧", py: "jiù", mean: "낡다, 오래되다" },
        { id: 98, category: "7. 형용사", zh: "聪明", py: "cōngming", mean: "똑똑하다" },
        { id: 99, category: "7. 형용사", zh: "可爱", py: "kě'ài", mean: "귀엽다" },
        { id: 100, category: "7. 형용사", zh: "干净", py: "gānjìng", mean: "깨끗하다" },
        { id: 101, category: "7. 형용사", zh: "安静", py: "ānjìng", mean: "조용하다" },
        { id: 102, category: "7. 형용사", zh: "安全", py: "ānquán", mean: "안전하다" },
        { id: 103, category: "7. 형용사", zh: "奇怪", py: "qíguài", mean: "이상하다, 기이하다" },
        { id: 104, category: "7. 형용사", zh: "清楚", py: "qīngchu", mean: "분명하다, 뚜렷하다" },
        { id: 105, category: "7. 형용사", zh: "舒服", py: "shūfu", mean: "편안하다, 기분 좋다" },
        { id: 106, category: "7. 형용사", zh: "容易", py: "róngyì", mean: "쉽다" },
        { id: 107, category: "7. 형용사", zh: "简单", py: "jiǎndān", mean: "간단하다" },
        { id: 108, category: "7. 형용사", zh: "甜", py: "tián", mean: "달다" },
        { id: 109, category: "7. 형용사", zh: "饱", py: "bǎo", mean: "배부르다" },
        { id: 110, category: "7. 형용사", zh: "渴", py: "kě", mean: "목마르다" },
        { id: 111, category: "7. 형용사", zh: "饿", py: "è", mean: "배고프다" },
        { id: 112, category: "7. 형용사", zh: "难过", py: "nánguò", mean: "슬프다, 괴롭다" },
        { id: 113, category: "7. 형용사", zh: "生气", py: "shēngqì", mean: "화나다" },
        { id: 114, category: "7. 형용사", zh: "新鲜", py: "xīnxiān", mean: "신선하다" },
        { id: 115, category: "7. 형용사", zh: "相同", py: "xiāngtóng", mean: "같다, 동일하다" },

        // --- 8. 부사 ---
        { id: 116, category: "8. 부사", zh: "才", py: "cái", mean: "비로소, 겨우" },
        { id: 117, category: "8. 부사", zh: "必须", py: "bìxū", mean: "반드시" },
        { id: 118, category: "8. 부사", zh: "当然", py: "dāngrán", mean: "당연히" },
        { id: 119, category: "8. 부사", zh: "几乎", py: "jīhū", mean: "거의" },
        { id: 120, category: "8. 부사", zh: "经常", py: "jīngcháng", mean: "자주, 늘" },
        { id: 121, category: "8. 부사", zh: "马上", py: "mǎshàng", mean: "즉시, 바로" },
        { id: 122, category: "8. 부사", zh: "其实", py: "qíshí", mean: "사실은, 실제로는" },
        { id: 123, category: "8. 부사", zh: "突然", py: "tūrán", mean: "갑자기" },
        { id: 124, category: "8. 부사", zh: "先", py: "xiān", mean: "먼저, 우선" },
        { id: 125, category: "8. 부사", zh: "一直", py: "yìzhí", mean: "계속, 줄곧" },
        { id: 126, category: "8. 부사", zh: "总是", py: "zǒngshì", mean: "항상, 늘" },
        { id: 127, category: "8. 부사", zh: "终于", py: "zhōngyú", mean: "마침내, 드디어" },
        { id: 128, category: "8. 부사", zh: "特别", py: "tèbié", mean: "특별히, 아주" },
        { id: 129, category: "8. 부사", zh: "更", py: "gèng", mean: "더욱, 한층 더" },
        { id: 130, category: "8. 부사", zh: "极", py: "jí", mean: "극히, 몹시 (~极了)" },

        // --- 9. 전치사/접속사/기타 ---
        { id: 131, category: "9. 접속사/전치사/기타", zh: "或者", py: "huòzhě", mean: "혹은, 아니면 (평서문)" },
        { id: 132, category: "9. 접속사/전치사/기타", zh: "还是", py: "háishì", mean: "아니면 (의문문)" },
        { id: 133, category: "9. 접속사/전치사/기타", zh: "为了", py: "wèile", mean: "~을 위하여" },
        { id: 134, category: "9. 접속사/전치사/기타", zh: "除了", py: "chúle", mean: "~을 제외하고" },
        { id: 135, category: "9. 접속사/전치사/기타", zh: "关于", py: "guānyú", mean: "~에 관하여" },
        { id: 136, category: "9. 접속사/전치사/기타", zh: "如果", py: "rúguǒ", mean: "만약 ~라면" },
        { id: 137, category: "9. 접속사/전치사/기타", zh: "虽然", py: "suīrán", mean: "비록 ~일지라도" },
        { id: 138, category: "9. 접속사/전치사/기타", zh: "只有", py: "zhǐyǒu", mean: "오직 ~해야만" },
        { id: 139, category: "9. 접속사/전치사/기타", zh: "然后", py: "ránhòu", mean: "그러고 나서" },
        { id: 140, category: "9. 접속사/전치사/기타", zh: "根据", py: "gēnjù", mean: "~에 근거하여" },
        
        // --- 10. 양사 ---
        { id: 141, category: "10. 양사", zh: "把", py: "bǎ", mean: "자루 (의자/우산 등 손잡이)" },
        { id: 142, category: "10. 양사", zh: "双", py: "shuāng", mean: "켤레, 쌍 (신발/젓가락 등)" },
        { id: 143, category: "10. 양사", zh: "辆", py: "liàng", mean: "대 (자동차/자전거 등)" },
        { id: 144, category: "10. 양사", zh: "条", py: "tiáo", mean: "마리, 벌 (길고 가느다란 것)" },
        { id: 145, category: "10. 양사", zh: "张", py: "zhāng", mean: "장 (종이/침대/책상 등)" },
        { id: 146, category: "10. 양사", zh: "瓶", py: "píng", mean: "병 (음료수 등)" },
        { id: 147, category: "10. 양사", zh: "层", py: "céng", mean: "층, 겹" },
        { id: 148, category: "10. 양사", zh: "段", py: "duàn", mean: "단락, 구간" },
        { id: 149, category: "10. 양사", zh: "种", py: "zhǒng", mean: "종류" },
        { id: 150, category: "10. 양사", zh: "角", py: "jiǎo", mean: "자오 (화폐 단위, 0.1위안)" }
    ]
};