vocabData["hsk4"] = {
    title: "HSK 4급",
    words: [
        // --- 1. 추상 명사 / 사회 ---
        { id: 1, category: "1. 추상 명사 / 사회", zh: "爱情", py: "àiqíng", mean: "사랑, 애정" },
        { id: 2, category: "1. 추상 명사 / 사회", zh: "标准", py: "biāozhǔn", mean: "표준, 기준" },
        { id: 3, category: "1. 추상 명사 / 사회", zh: "不仅", py: "bùjǐn", mean: "뿐만 아니라" },
        { id: 4, category: "1. 추상 명사 / 사회", zh: "材料", py: "cáiliào", mean: "재료, 데이터" },
        { id: 5, category: "1. 추상 명사 / 사회", zh: "法律", py: "fǎlǜ", mean: "법률" },
        { id: 6, category: "1. 추상 명사 / 사회", zh: "工资", py: "gōngzī", mean: "급여, 월급" },
        { id: 7, category: "1. 추상 명사 / 사회", zh: "好处", py: "hǎochu", mean: "장점, 이로운 점" },
        { id: 8, category: "1. 추상 명사 / 사회", zh: "机会", py: "jīhuì", mean: "기회" },
        { id: 9, category: "1. 추상 명사 / 사회", zh: "经验", py: "jīngyàn", mean: "경험" },
        { id: 10, category: "1. 추상 명사 / 사회", zh: "空气", py: "kōngqì", mean: "공기" },
        { id: 11, category: "1. 추상 명사 / 사회", zh: "困难", py: "kùnnan", mean: "곤란, 어려움" },
        { id: 12, category: "1. 추상 명사 / 사회", zh: "礼모", py: "lǐmào", mean: "예의" },
        { id: 13, category: "1. 추상 명사 / 사회", zh: "能力", py: "nénglì", mean: "능력" },
        { id: 14, category: "1. 추상 명사 / 사회", zh: "题目", py: "tímù", mean: "제목, 주제" },
        { id: 15, category: "1. 추상 명사 / 사회", zh: "艺术", py: "yìshù", mean: "예술" },

        // --- 2. 동사 (심리/사고) ---
        { id: 16, category: "2. 동사 (심리/사고)", zh: "怀疑", py: "huáiyí", mean: "의심하다" },
        { id: 17, category: "2. 동사 (심리/사고)", zh: "解释", py: "jiěshì", mean: "설명하다, 해명하다" },
        { id: 18, category: "2. 동사 (심리/사고)", zh: "考虑", py: "kǎolǜ", mean: "고려하다, 생각하다" },
        { id: 19, category: "2. 동사 (심리/사고)", zh: "其实", py: "qíshí", mean: "사실은" },
        { id: 20, category: "2. 동사 (심리/사고)", zh: "认为", py: "rènwéi", mean: "여기다, 생각하다" },
        { id: 21, category: "2. 동사 (심리/사고)", zh: "适合", py: "shìhé", mean: "적합하다, 알맞다" },
        { id: 22, category: "2. 동사 (심리/사고)", zh: "同意", py: "tóngyì", mean: "동의하다" },
        { id: 23, category: "2. 동사 (심리/사고)", zh: "羡慕", py: "xiànmù", mean: "부러워하다" },
        { id: 24, category: "2. 동사 (심리/사고)", zh: "相信", py: "xiāngxìn", mean: "믿다" },
        { id: 25, category: "2. 동사 (심리/사고)", zh: "允许", py: "yǔnxǔ", mean: "허가하다, 허락하다" },

        // --- 3. 동사 (행동/변화) ---
        { id: 26, category: "3. 동사 (행동/변화)", zh: "安排", py: "ānpái", mean: "배치하다, 안배하다" },
        { id: 27, category: "3. 동사 (행동/변화)", zh: "保护", py: "bǎohù", mean: "보호하다" },
        { id: 28, category: "3. 동사 (행동/변화)", zh: "保证", py: "bǎozhèng", mean: "보증하다" },
        { id: 29, category: "3. 동사 (행동/변화)", zh: "报名", py: "bàomíng", mean: "등록하다, 신청하다" },
        { id: 30, category: "3. 동사 (행동/변화)", zh: "毕业", py: "bìyè", mean: "졸업하다" },
        { id: 31, category: "3. 동사 (행동/변화)", zh: "打扮", py: "dǎban", mean: "차려입다, 꾸미다" },
        { id: 32, category: "3. 동사 (행동/변화)", zh: "道歉", py: "dàoqiàn", mean: "사과하다" },
        { id: 33, category: "3. 동사 (행동/변화)", zh: "发展", py: "fāzhǎn", mean: "발전하다" },
        { id: 34, category: "3. 동사 (행동/변화)", zh: "反对", py: "fǎnduì", mean: "반대하다" },
        { id: 35, category: "3. 동사 (행동/변화)", zh: "改变", py: "gǎibiàn", mean: "변화시키다" },
        { id: 36, category: "3. 동사 (행동/변화)", zh: "管理", py: "guǎnlǐ", mean: "관리하다" },
        { id: 37, category: "3. 동사 (행동/변화)", zh: "坚持", py: "jiānchí", mean: "견지하다, 지속하다" },
        { id: 38, category: "3. 동사 (행동/변화)", zh: "积累", py: "jīlěi", mean: "쌓다, 누적하다" },
        { id: 39, category: "3. 동사 (행동/변화)", zh: "拒绝", py: "jùjué", mean: "거절하다" },
        { id: 40, category: "3. 동사 (행동/변화)", zh: "流泪", py: "liú lèi", mean: "눈물을 흘리다" },

        // --- 4. 형용사 (성격/상태) ---
        { id: 41, category: "4. 형용사", zh: "笨", py: "bèn", mean: "어리석다, 둔하다" },
        { id: 42, category: "4. 형용사", zh: "诚实", py: "chéngshí", mean: "정직하다" },
        { id: 43, category: "4. 형용사", zh: "粗心", py: "cūxīn", mean: "덜렁대다, 소홀하다" },
        { id: 44, category: "4. 형용사", zh: "得意", py: "déyì", mean: "의기양양하다" },
        { id: 45, category: "4. 형용사", zh: "烦恼", py: "fánnǎo", mean: "번뇌하다, 걱정스럽다" },
        { id: 46, category: "4. 형용사", zh: "复杂", py: "fùzá", mean: "복잡하다" },
        { id: 47, category: "4. 형용사", zh: "害羞", py: "hàixiū", mean: "부끄러워하다" },
        { id: 48, category: "4. 형용사", zh: "后悔", py: "hòuhuǐ", mean: "후회하다" },
        { id: 49, category: "4. 형용사", zh: "骄傲", py: "jiāo'ào", mean: "거만하다, 자랑스럽다" },
        { id: 50, category: "4. 형용사", zh: "紧张", py: "jǐnzhāng", mean: "긴장하다" },
        { id: 51, category: "4. 형용사", zh: "精彩", py: "jīngcǎi", mean: "화려하다, 훌륭하다" },
        { id: 52, category: "4. 형용사", zh: "浪漫", py: "làngmàn", mean: "낭만적이다" },
        { id: 53, category: "4. 형용사", zh: "热闹", py: "rènao", mean: "번화하다, 시끌벅적하다" },
        { id: 54, category: "4. 형용사", zh: "伤心", py: "shāngxīn", mean: "슬퍼하다" },
        { id: 55, category: "4. 형용사", zh: "幽默", py: "yōumò", mean: "유머러스하다" },

        // --- 5. 부사 (정도/범위/시간) ---
        { id: 56, category: "5. 부사", zh: "大概", py: "dàgài", mean: "대개, 아마" },
        { id: 57, category: "5. 부사", zh: "到底", py: "dàodǐ", mean: "도대체, 결국" },
        { id: 58, category: "5. 부사", zh: "反而", py: "fǎn'ér", mean: "반대로, 도리어" },
        { id: 59, category: "5. 부사", zh: "刚才", py: "gāngcái", mean: "방금" },
        { id: 60, category: "5. 부사", zh: "果然", py: "guǒrán", mean: "과연" },
        { id: 61, category: "5. 부사", zh: "忽然", py: "hūrán", mean: "갑자기" },
        { id: 62, category: "5. 부사", zh: "互相", py: "hùxiāng", mean: "서로" },
        { id: 63, category: "5. 부사", zh: "即使", py: "jíshǐ", mean: "설령 ~일지라도" },
        { id: 64, category: "5. 부사", zh: "竟然", py: "jìngrán", mean: "뜻밖에도" },
        { id: 65, category: "5. 부사", zh: "偶尔", py: "ǒu'ěr", mean: "어쩌다, 가끔" },
        { id: 66, category: "5. 부사", zh: "千万", py: "qiānwàn", mean: "부디, 제발" },
        { id: 67, category: "5. 부사", zh: "稍微", py: "shāowēi", mean: "약간, 조금" },
        { id: 68, category: "5. 부사", zh: "顺便", py: "shùnbiàn", mean: "기왕 하는 김에" },
        { id: 69, category: "5. 부사", zh: "也许", py: "yěxǔ", mean: "아마도" },
        { id: 70, category: "5. 부사", zh: "尤其", py: "yóuqí", mean: "특히" },

        // --- 6. 접속사 / 기타 ---
        { id: 71, category: "6. 접속사 / 기타", zh: "否则", py: "fǒuzé", mean: "그렇지 않으면" },
        { id: 72, category: "6. 접속사 / 기타", zh: "既然", py: "jìrán", mean: "이미 ~한 이상" },
        { id: 73, category: "6. 접속사 / 기타", zh: "例如", py: "lìrú", mean: "예를 들어" },
        { id: 74, category: "6. 접속사 / 기타", zh: "难道", py: "nándào", mean: "설마 ~하겠는가" },
        { id: 75, category: "6. 접속사 / 기타", zh: "所以", py: "suǒyǐ", mean: "그래서" },
        { id: 76, category: "6. 접속사 / 기타", zh: "不管", py: "bùguǎn", mean: "~에 관계없이" },
        { id: 77, category: "6. 접속사 / 기타", zh: "因此", py: "yīncǐ", mean: "그러므로" },
        { id: 78, category: "6. 접속사 / 기타", zh: "只要", py: "zhǐyào", mean: "오직 ~하기만 하면" },
        { id: 79, category: "6. 접속사 / 기타", zh: "注意", py: "zhùyì", mean: "주의하다" },
        { id: 80, category: "6. 접속사 / 기타", zh: "总是", py: "zǒngshì", mean: "늘, 언제나" },

        // --- (중략: 필수 단어 150개를 위한 추가 목록) ---
        { id: 81, category: "3. 동사 (행동/변화)", zh: "擦", py: "cā", mean: "닦다" },
        { id: 82, category: "3. 동사 (행동/변화)", zh: "猜", py: "cāi", mean: "추측하다" },
        { id: 83, category: "3. 동사 (행동/변화)", zh: "传", py: "chuán", mean: "전하다" },
        { id: 84, category: "3. 동사 (행동/변화)", zh: "存", py: "cún", mean: "보관하다" },
        { id: 85, category: "3. 동사 (행동/변화)", zh: "丢", py: "diū", mean: "잃어버리다" },
        { id: 86, category: "3. 동사 (행동/변화)", zh: "符合", py: "fúhé", mean: "부합하다" },
        { id: 87, category: "3. 동사 (행동/변화)", zh: "复印", py: "fùyìn", mean: "복사하다" },
        { id: 88, category: "3. 동사 (행동/변화)", zh: "估计", py: "gūjì", mean: "추정하다" },
        { id: 89, category: "3. 동사 (행동/변화)", zh: "逛", py: "guàng", mean: "돌아다니다" },
        { id: 90, category: "3. 동사 (행동/변화)", zh: "合格", py: "hégé", mean: "합격하다" },
        { id: 91, category: "4. 형용사", zh: "厚", py: "hòu", mean: "두껍다" },
        { id: 92, category: "4. 형용사", zh: "活跃", py: "huóyuè", mean: "활발하다" },
        { id: 93, category: "1. 추상 명사 / 사회", zh: "基础", py: "jīchǔ", mean: "기초" },
        { id: 94, category: "1. 추상 명사 / 사회", zh: "奖金", py: "jiǎngjīn", mean: "상금, 보너스" },
        { id: 95, category: "3. 동사 (행동/변화)", zh: "降低", py: "jiàngdī", mean: "낮추다" },
        { id: 96, category: "1. 추상 명사 / 사회", zh: "交通", py: "jiāotōng", mean: "교통" },
        { id: 97, category: "3. 동사 (행동/변화)", zh: "接受", py: "jiēshòu", mean: "받아들이다" },
        { id: 98, category: "3. 동사 (행동/변화)", zh: "节约", py: "jiéyuē", mean: "절약하다" },
        { id: 99, category: "4. 형용사", zh: "紧张", py: "jǐnzhāng", mean: "긴장하다" },
        { id: 100, category: "3. 동사 (행동/변화)", zh: "进行", py: "jìnxíng", mean: "진행하다" },
        { id: 101, category: "1. 추상 명사 / 사회", zh: "警察", py: "jǐngchá", mean: "경찰" },
        { id: 102, category: "4. 형용사", zh: "竟然", py: "jìngrán", mean: "뜻밖에도" },
        { id: 103, category: "3. 동사 (행동/변화)", zh: "禁止", py: "jìnzhǐ", mean: "금지하다" },
        { id: 104, category: "1. 추상 명사 / 사회", zh: "看法", py: "kànfǎ", mean: "견해, 관점" },
        { id: 105, category: "4. 형용사", zh: "可怜", py: "kělián", mean: "가련하다" },
        { id: 106, category: "4. 형용사", zh: "可惜", py: "kěxī", mean: "아쉽다" },
        { id: 107, category: "4. 형용사", zh: "肯定", py: "kěndìng", mean: "긍정하다, 확실히" },
        { id: 108, category: "1. 추상 명사 / 사회", zh: "垃圾桶", py: "lājītǒng", mean: "쓰레기통" },
        { id: 109, category: "4. 형용사", zh: "懒", py: "lǎn", mean: "게으르다" },
        { id: 110, category: "4. 형용사", zh: "凉快", py: "liángkuai", mean: "시원하다" },
        { id: 111, category: "3. 동사 (행동/변화)", zh: "联系", py: "liánxì", mean: "연락하다" },
        { id: 112, category: "4. 형용사", zh: "亮", py: "liàng", mean: "밝다" },
        { id: 113, category: "1. 추상 명사 / 사회", zh: "律师", py: "lǜshī", mean: "변호사" },
        { id: 114, category: "4. 형용사", zh: "麻烦", py: "máfan", mean: "번거롭다" },
        { id: 115, category: "4. 형용사", zh: "满", py: "mǎn", mean: "가득 차다" },
        { id: 116, category: "4. 형용사", zh: "满意", py: "mǎnyì", mean: "만족하다" },
        { id: 117, category: "1. 추상 명사 / 사회", zh: "密码", py: "mìmǎ", mean: "비밀번호" },
        { id: 118, category: "1. 추상 명사 / 사회", zh: "免费", py: "miǎnfèi", mean: "무료" },
        { id: 119, category: "1. 추상 명사 / 사회", zh: "民族", py: "mínzú", mean: "민족" },
        { id: 120, category: "1. 추상 명사 / 사회", zh: "目的", py: "mùdì", mean: "목적" },
        { id: 121, category: "4. 형용사", zh: "耐心", py: "nàixīn", mean: "인내심이 있다" },
        { id: 122, category: "4. 형용사", zh: "难受", py: "nánshòu", mean: "괴롭다" },
        { id: 123, category: "1. 추상 명사 / 사회", zh: "农村", py: "nóngcūn", mean: "농촌" },
        { id: 124, category: "3. 동사 (행동/변화)", zh: "弄", py: "nòng", mean: "하다, 만들다" },
        { id: 125, category: "4. 형용사", zh: "暖和", py: "nuǎnhuo", mean: "따뜻하다" },
        { id: 126, category: "3. 동사 (행동/변화)", zh: "排队", py: "páiduì", mean: "줄을 서다" },
        { id: 127, category: "3. 동사 (행동/변화)", zh: "排列", py: "páiliè", mean: "배열하다" },
        { id: 128, category: "3. 동사 (행동/변화)", zh: "判断", py: "pànduàn", mean: "판단하다" },
        { id: 129, category: "3. 동사 (행동/변화)", zh: "陪", py: "péi", mean: "동반하다" },
        { id: 130, category: "3. 동사 (행동/변화)", zh: "批评", py: "pīpíng", mean: "비평하다" },
        { id: 131, category: "1. 추상 명사 / 사회", zh: "皮肤", py: "pífū", mean: "피부" },
        { id: 132, category: "1. 추상 명사 / 사회", zh: "脾气", py: "píqi", mean: "성미, 성격" },
        { id: 133, category: "3. 동사 (행동/변화)", zh: "骗", py: "piàn", mean: "속이다" },
        { id: 134, category: "1. 추상 명사 / 사회", zh: "乒乓球", py: "pīngpāngqiú", mean: "탁구" },
        { id: 135, category: "1. 추상 명사 / 사회", zh: "瓶子", py: "píngzi", mean: "병" },
        { id: 136, category: "4. 형용사", zh: "普遍", py: "pǔbiàn", mean: "보편적이다" },
        { id: 137, category: "3. 동사 (행동/변화)", zh: "敲", py: "qiāo", mean: "두드리다" },
        { id: 138, category: "1. 추상 명사 / 사회", zh: "签证", py: "qiānzhèng", mean: "비자" },
        { id: 139, category: "1. 추상 명사 / 사회", zh: "巧克力", py: "qiǎokèlì", mean: "초콜릿" },
        { id: 140, category: "1. 추상 명사 / 사회", zh: "亲戚", py: "qīnqi", mean: "친척" },
        { id: 141, category: "4. 형용사", zh: "轻", py: "qīng", mean: "가볍다" },
        { id: 142, category: "4. 형용사", zh: "穷", py: "qióng", mean: "가난하다" },
        { id: 143, category: "3. 동사 (행동/변화)", zh: "区别", py: "qūbié", mean: "구별하다" },
        { id: 144, category: "4. 형용사", zh: "缺点", py: "quēdiǎn", mean: "결점" },
        { id: 145, category: "3. 동사 (행동/변화)", zh: "确实", py: "quèshí", mean: "확실하다" },
        { id: 146, category: "4. 형용사", zh: "热闹", py: "rènao", mean: "번화하다" },
        { id: 147, category: "1. 추상 명사 / 사회", zh: "人民币", py: "rénmínbì", mean: "인민폐" },
        { id: 148, category: "4. 형용사", zh: "软", py: "ruǎn", mean: "부드럽다" },
        { id: 149, category: "3. 동사 (행동/변화)", zh: "散步", py: "sànbù", mean: "산책하다" },
        { id: 150, category: "3. 동사 (행동/변화)", zh: "稍微", py: "shāowēi", mean: "약간" }
    ]
};