const vocabData = {
    "windows": {
        title: "Windows OS 필수 단어",
        words: [
            // 1. 기본 Windows UI 및 운영
            { id: 1, category: "1. 기본 Windows UI 및 운영", zh: "操作系统", py: "càozuò xìtǒng", mean: "운영체제 (OS)" },
            { id: 2, category: "1. 기본 Windows UI 및 운영", zh: "桌面", py: "zhuōmiàn", mean: "바탕화면" },
            { id: 3, category: "1. 기본 Windows UI 및 운영", zh: "窗口", py: "chuāngkǒu", mean: "창 (Window)" },
            { id: 4, category: "1. 기본 Windows UI 및 운영", zh: "任务栏", py: "rènwùlán", mean: "작업 표시줄" },
            { id: 5, category: "1. 기본 Windows UI 및 운영", zh: "开始菜单", py: "kāishǐ càidān", mean: "시작 메뉴" },
            { id: 6, category: "1. 기본 Windows UI 및 운영", zh: "设置", py: "shèzhì", mean: "설정" },
            { id: 7, category: "1. 기본 Windows UI 및 운영", zh: "控制面板", py: "kòngzhì miànbǎn", mean: "제어판" },
            { id: 8, category: "1. 기본 Windows UI 및 운영", zh: "属性", py: "shǔxìng", mean: "속성" },
            { id: 9, category: "1. 기본 Windows UI 및 운영", zh: "更新", py: "gēngxīn", mean: "업데이트" },
            { id: 10, category: "1. 기본 Windows UI 및 운영", zh: "重启", py: "chóngqǐ", mean: "재부팅" },
            { id: 11, category: "1. 기본 Windows UI 및 운영", zh: "关机", py: "guānjī", mean: "시스템 종료" },
            { id: 12, category: "1. 기본 Windows UI 및 운영", zh: "注销", py: "zhùxiāo", mean: "로그아웃" },
            { id: 13, category: "1. 기본 Windows UI 및 운영", zh: "快捷方式", py: "kuàijié fāngshì", mean: "바로가기" },
            { id: 14, category: "1. 기본 Windows UI 및 운영", zh: "剪贴板", py: "jiǎntiēbǎn", mean: "클립보드" },
            { id: 15, category: "1. 기본 Windows UI 및 운영", zh: "复制", py: "fùzhì", mean: "복사" },
            { id: 16, category: "1. 기본 Windows UI 및 운영", zh: "粘贴", py: "zhāntiē", mean: "붙여넣기" },
            { id: 17, category: "1. 기본 Windows UI 및 운영", zh: "剪切", py: "jiǎnqiē", mean: "잘라내기" },
            { id: 18, category: "1. 기본 Windows UI 및 운영", zh: "撤销", py: "chèxiāo", mean: "실행 취소" },
            { id: 19, category: "1. 기본 Windows UI 및 운영", zh: "确认", py: "quèrèn", mean: "확인 (OK)" },
            { id: 20, category: "1. 기본 Windows UI 및 운영", zh: "取消", py: "qǔxiāo", mean: "취소 (Cancel)" },

            // 2. 파일 및 디렉토리 관리
            { id: 21, category: "2. 파일 및 디렉토리 관리", zh: "文件", py: "wénjiàn", mean: "파일" },
            { id: 22, category: "2. 파일 및 디렉토리 관리", zh: "文件夹", py: "wénjiànjiā", mean: "폴더" },
            { id: 23, category: "2. 파일 및 디렉토리 관리", zh: "目录", py: "mùlù", mean: "디렉토리" },
            { id: 24, category: "2. 파일 및 디렉토리 관리", zh: "路径", py: "lùjìng", mean: "경로 (Path)" },
            { id: 25, category: "2. 파일 및 디렉토리 관리", zh: "扩展名", py: "kuòzhǎnmíng", mean: "확장자" },
            { id: 26, category: "2. 파일 및 디렉토리 관리", zh: "保存", py: "bǎocún", mean: "저장" },
            { id: 27, category: "2. 파일 및 디렉토리 관리", zh: "另存为", py: "lìng cún wéi", mean: "다른 이름 저장" },
            { id: 28, category: "2. 파일 및 디렉토리 관리", zh: "删除", py: "shānchú", mean: "삭제" },
            { id: 29, category: "2. 파일 및 디렉토리 관리", zh: "回收站", py: "huíshōuzhàn", mean: "휴지통" },
            { id: 30, category: "2. 파일 및 디렉토리 관리", zh: "压缩", py: "yāsuō", mean: "압축" },
            { id: 31, category: "2. 파일 및 디렉토리 관리", zh: "解压", py: "jiěyā", mean: "압축 해제" },
            { id: 32, category: "2. 파일 및 디렉토리 관리", zh: "隐藏", py: "yǐncáng", mean: "숨김" },
            { id: 33, category: "2. 파일 및 디렉토리 관리", zh: "只读", py: "zhǐdú", mean: "읽기 전용" },
            { id: 34, category: "2. 파일 및 디렉토리 관리", zh: "权限", py: "quánxiàn", mean: "권한" },
            { id: 35, category: "2. 파일 및 디렉토리 관리", zh: "共享", py: "gòngxiǎng", mean: "공유" },

            // 3. 하드웨어 및 장치
            { id: 36, category: "3. 하드웨어 및 장치", zh: "硬件", py: "yìngjiàn", mean: "하드웨어" },
            { id: 37, category: "3. 하드웨어 및 장치", zh: "处理器", py: "chǔlǐqì", mean: "프로세서 (CPU)" },
            { id: 38, category: "3. 하드웨어 및 장치", zh: "内存", py: "nèicún", mean: "메모리 (RAM)" },
            { id: 39, category: "3. 하드웨어 및 장치", zh: "显存", py: "xiǎncún", mean: "비디오 메모리" },
            { id: 40, category: "3. 하드웨어 및 장치", zh: "主板", py: "zhǔbǎn", mean: "메인보드" },
            { id: 41, category: "3. 하드웨어 및 장치", zh: "硬盘", py: "yìngpán", mean: "하드디스크" },
            { id: 42, category: "3. 하드웨어 및 장치", zh: "固态硬盘", py: "gùtài yìngpán", mean: "SSD" },
            { id: 43, category: "3. 하드웨어 및 장치", zh: "显卡", py: "xiǎnkǎ", mean: "그래픽 카드" },
            { id: 44, category: "3. 하드웨어 및 장치", zh: "网卡", py: "wǎngkǎ", mean: "네트워크 카드" },
            { id: 45, category: "3. 하드웨어 및 장치", zh: "显示器", py: "xiǎnshìqì", mean: "모니터" },
            { id: 46, category: "3. 하드웨어 및 장치", zh: "键盘", py: "jiànpán", mean: "키보드" },
            { id: 47, category: "3. 하드웨어 및 장치", zh: "鼠标", py: "shǔbiāo", mean: "마우스" },
            { id: 48, category: "3. 하드웨어 및 장치", zh: "驱动程序", py: "qūdòng chéngxù", mean: "장치 드라이버" },
            { id: 49, category: "3. 하드웨어 및 장치", zh: "外设", py: "wàishè", mean: "주변기기" },
            { id: 50, category: "3. 하드웨어 및 장치", zh: "接口", py: "jiēkǒu", mean: "인터페이스" },

            // 4. 네트워크 및 통신
            { id: 51, category: "4. 네트워크 및 통신", zh: "网络", py: "wǎngluò", mean: "네트워크" },
            { id: 52, category: "4. 네트워크 및 통신", zh: "服务器", py: "fúwùqì", mean: "서버" },
            { id: 53, category: "4. 네트워크 및 통신", zh: "客户端", py: "kèhùduān", mean: "클라이언트" },
            { id: 54, category: "4. 네트워크 및 통신", zh: "局域网", py: "júyùwǎng", mean: "LAN" },
            { id: 55, category: "4. 네트워크 및 통신", zh: "路由器", py: "lùyóuqì", mean: "라우터/공유기" },
            { id: 56, category: "4. 네트워크 및 통신", zh: "防火墙", py: "fánghuǒqiáng", mean: "방화벽" },
            { id: 57, category: "4. 네트워크 및 통신", zh: "端口", py: "duānkǒu", mean: "포트 (Port)" },
            { id: 58, category: "4. 네트워크 및 통신", zh: "协议", py: "xiéyì", mean: "프로토콜" },
            { id: 59, category: "4. 네트워크 및 통신", zh: "带宽", py: "dàikuān", mean: "대역폭" },
            { id: 60, category: "4. 네트워크 및 통신", zh: "延迟", py: "yánchí", mean: "지연 (Ping)" },
            { id: 61, category: "4. 네트워크 및 통신", zh: "数据包", py: "shùjùbāo", mean: "데이터 패킷" },
            { id: 62, category: "4. 네트워크 및 통신", zh: "连接", py: "liánjiē", mean: "연결" },
            { id: 63, category: "4. 네트워크 및 통신", zh: "断开", py: "duànkāi", mean: "연결 끊기" },
            { id: 64, category: "4. 네트워크 및 통신", zh: "上传", py: "shàngchuán", mean: "업로드" },
            { id: 65, category: "4. 네트워크 및 통신", zh: "下载", py: "xiàzài", mean: "다운로드" },

            // 5. 시스템 내부 및 보안
            { id: 66, category: "5. 시스템 내부 및 보안", zh: "任务管理器", py: "rènwù guǎnlǐqì", mean: "작업 관리자" },
            { id: 67, category: "5. 시스템 내부 및 보안", zh: "进程", py: "jìnchéng", mean: "프로세스" },
            { id: 68, category: "5. 시스템 내부 및 보안", zh: "线程", py: "xiànchéng", mean: "스레드" },
            { id: 69, category: "5. 시스템 내부 및 보안", zh: "服务", py: "fúwù", mean: "서비스" },
            { id: 70, category: "5. 시스템 내부 및 보안", zh: "注册表", py: "zhùcèbiǎo", mean: "레지스트리" },
            { id: 71, category: "5. 시스템 내부 및 보안", zh: "命令行", py: "mìnglìng háng", mean: "명령 프롬프트" },
            { id: 72, category: "5. 시스템 내부 및 보안", zh: "终端", py: "zhōngduān", mean: "터미널" },
            { id: 73, category: "5. 시스템 내부 및 보안", zh: "虚拟机", py: "xūnǐjī", mean: "가상 머신" },
            { id: 74, category: "5. 시스템 내부 및 보안", zh: "内存泄漏", py: "nèicún xièlòu", mean: "메모리 누수" },
            { id: 75, category: "5. 시스템 내부 및 보안", zh: "蓝屏", py: "lánpíng", mean: "블루스크린" },
            { id: 76, category: "5. 시스템 내부 및 보안", zh: "安全", py: "ānquán", mean: "보안" },
            { id: 77, category: "5. 시스템 내부 및 보안", zh: "漏洞", py: "lòudòng", mean: "취약점" },
            { id: 78, category: "5. 시스템 내부 및 보안", zh: "补丁", py: "bǔdīng", mean: "패치 (Patch)" },
            { id: 79, category: "5. 시스템 내부 및 보안", zh: "杀毒软件", py: "shādú ruǎnjiàn", mean: "백신 프로그램" },
            { id: 80, category: "5. 시스템 내부 및 보안", zh: "拦截", py: "lánjié", mean: "차단/인터셉트" },
            { id: 81, category: "5. 시스템 내부 및 보안", zh: "授权", py: "shòuquán", mean: "권한 부여" },
            { id: 82, category: "5. 시스템 내부 및 보안", zh: "认证", py: "rènzhèng", mean: "인증" },
            { id: 83, category: "5. 시스템 내부 및 보안", zh: "加密", py: "jiāmì", mean: "암호화" },
            { id: 84, category: "5. 시스템 내부 및 보안", zh: "解密", py: "jiěmì", mean: "복호화" },
            { id: 85, category: "5. 시스템 내부 및 보안", zh: "日志", py: "rìzhì", mean: "로그 (Log)" },

            // 6. 개발 및 소프트웨어
            { id: 86, category: "6. 개발 및 소프트웨어", zh: "软件", py: "ruǎnjiàn", mean: "소프트웨어" },
            { id: 87, category: "6. 개발 및 소프트웨어", zh: "源代码", py: "yuándàimǎ", mean: "소스 코드" },
            { id: 88, category: "6. 개발 및 소프트웨어", zh: "编译器", py: "biānyìqì", mean: "컴파일러" },
            { id: 89, category: "6. 개발 및 소프트웨어", zh: "调试", py: "tiáoshì", mean: "디버깅" },
            { id: 90, category: "6. 개발 및 소프트웨어", zh: "变量", py: "biànliàng", mean: "변수" },
            { id: 91, category: "6. 개발 및 소프트웨어", zh: "函数", py: "hánshù", mean: "함수" },
            { id: 92, category: "6. 개발 및 소프트웨어", zh: "应用程序接口", py: "yìngyòng chéngxù jiēkǒu", mean: "API" },
            { id: 93, category: "6. 개발 및 소프트웨어", zh: "脚本", py: "jiǎoběn", mean: "스크립트" },
            { id: 94, category: "6. 개발 및 소프트웨어", zh: "库", py: "kù", mean: "라이브러리" },
            { id: 95, category: "6. 개발 및 소프트웨어", zh: "框架", py: "kuàngjià", mean: "프레임워크" },
            { id: 96, category: "6. 개발 및 소프트웨어", zh: "部署", py: "bùshǔ", mean: "배포" },
            { id: 97, category: "6. 개발 및 소프트웨어", zh: "版本控制", py: "bǎnběn kòngzhì", mean: "버전 관리" },
            { id: 98, category: "6. 개발 및 소프트웨어", zh: "提交", py: "tíjiāo", mean: "커밋 (Commit)" },
            { id: 99, category: "6. 개발 및 소프트웨어", zh: "合并", py: "hébìng", mean: "병합 (Merge)" },
            { id: 100, category: "6. 개발 및 소프트웨어", zh: "错误", py: "cuòwù", mean: "오류 / 버그" },

            // 7. 팝업창 및 공통 버튼 (Dialog & Buttons)
            { id: 101, category: "7. 팝업창 및 공통 버튼", zh: "是", py: "shì", mean: "예 (Yes)" },
            { id: 102, category: "7. 팝업창 및 공통 버튼", zh: "否", py: "fǒu", mean: "아니오 (No)" },
            { id: 103, category: "7. 팝업창 및 공통 버튼", zh: "中止", py: "zhōngzhǐ", mean: "중단 (Abort)" },
            { id: 104, category: "7. 팝업창 및 공통 버튼", zh: "重试", py: "chóngshì", mean: "다시 시도 (Retry)" },
            { id: 105, category: "7. 팝업창 및 공통 버튼", zh: "忽略", py: "hūlüè", mean: "무시 (Ignore)" },
            { id: 106, category: "7. 팝업창 및 공통 버튼", zh: "允许", py: "yǔnxǔ", mean: "허용 (Allow)" },
            { id: 107, category: "7. 팝업창 및 공통 버튼", zh: "拒绝", py: "jùjué", mean: "거부 (Deny)" },
            { id: 108, category: "7. 팝업창 및 공통 버튼", zh: "阻止", py: "zǔzhǐ", mean: "차단 (Block)" },
            { id: 109, category: "7. 팝업창 및 공통 버튼", zh: "继续", py: "jìxù", mean: "계속 (Continue)" },
            { id: 110, category: "7. 팝업창 및 공통 버튼", zh: "确定", py: "quèdìng", mean: "확인 (OK)" },
            { id: 111, category: "7. 팝업창 및 공통 버튼", zh: "应用", py: "yìngyòng", mean: "적용 (Apply)" },
            { id: 112, category: "7. 팝업창 및 공통 버튼", zh: "下一步", py: "xià yí bù", mean: "다음 (Next)" },
            { id: 113, category: "7. 팝업창 및 공통 버튼", zh: "上一步", py: "shàng yí bù", mean: "뒤로 (Back)" },
            { id: 114, category: "7. 팝업창 및 공통 버튼", zh: "完成", py: "wánchéng", mean: "마침 (Finish)" },
            { id: 115, category: "7. 팝업창 및 공통 버튼", zh: "关闭", py: "guānbì", mean: "닫기 (Close)" },
            { id: 116, category: "7. 팝업창 및 공통 버튼", zh: "退出", py: "tuìchū", mean: "종료/나가기 (Exit)" },
            { id: 117, category: "7. 팝업창 및 공통 버튼", zh: "帮助", py: "bāngzhù", mean: "도움말 (Help)" },
            { id: 118, category: "7. 팝업창 및 공통 버튼", zh: "浏览", py: "liúlǎn", mean: "찾아보기(Browse)" },
            { id: 119, category: "7. 팝업창 및 공통 버튼", zh: "默认", py: "mòrèn", mean: "기본값 (Default)" },
            { id: 120, category: "7. 팝업창 및 공통 버튼", zh: "自定义", py: "zìdìngyì", mean: "사용자 지정" },

            // 8. 시스템 및 소프트웨어 설정 메뉴 (Settings Menu)
            { id: 121, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "常规", py: "chángguī", mean: "일반 (General)" },
            { id: 122, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "显示", py: "xiǎnshì", mean: "디스플레이" },
            { id: 123, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "账户", py: "zhànghù", mean: "계정 (Accounts)" },
            { id: 124, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "隐私", py: "yǐnsī", mean: "개인정보 보호" },
            { id: 125, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "语言和区域", py: "yǔyán hé qūyù", mean: "언어 및 지역" },
            { id: 126, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "个性化", py: "gèxìnghuà", mean: "개인 설정" },
            { id: 127, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "网络和互联网", py: "wǎngluò hé h.", mean: "네트워크 및 인터넷" },
            { id: 128, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "更新和安全", py: "gēngxīn hé ānquán", mean: "업데이트 및 보안" },
            { id: 129, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "高级系统设置", py: "gāojí xìtǒng shèzhì", mean: "고급 시스템 설정" },
            { id: 130, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "环境变量", py: "huánjìng biànliàng", mean: "환경 변수" },
            { id: 131, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "开发者选项", py: "kāifāzhě xuǎnxiàng", mean: "개발자 옵션" },
            { id: 132, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "代理", py: "dàilǐ", mean: "프록시 (Proxy)" },
            { id: 133, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "疑难解答", py: "yínán jiědá", mean: "문제 해결" },
            { id: 134, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "恢复", py: "huīfù", mean: "복구 (Recovery)" },
            { id: 135, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "启动", py: "qǐdòng", mean: "시작 프로그램" },
            { id: 136, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "存储", py: "cúnchǔ", mean: "저장소 (Storage)" },
            { id: 137, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "性能", py: "xìngnéng", mean: "성능" },
            { id: 138, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "通知", py: "tōngzhī", mean: "알림" },
            { id: 139, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "声音", py: "shēngyīn", mean: "소리 (Sound)" },
            { id: 140, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "蓝牙和其他设备", py: "lányá hé qítā..", mean: "블루투스 및 장치" }

        ]
    },
    "hsk2": {
        title: "HSK 2급 필수 단어",
        words: [
            { id: 1, category: "1. 인물", zh: "爸爸", py: "bàba", mean: "아빠, 아버지"}
        ]
    }
}