const vocabData = {
    "windows": {
        title: "Windows OS 필수 단어",
        words: [
            // 1. 기본 Windows UI 및 운영
            { id: 1, category: "1. 기본 Windows UI 및 운영", zh: "操作系统", py: "càozuò xìtǒng", mean: "운영체제 (OS)" },
            { id: 2, category: "1. 기본 Windows UI 및 운영", zh: "桌面", py: "zhuōmiàn", mean: "바탕화면" },
            { id: 3, category: "1. 기본 Windows UI 및 운영", zh: "窗口", py: "chuāngkǒu", mean: "창 (Window)" },
            { id: 4, category: "1. 기본 Windows UI 및 운영", zh: "任务栏", py: "rènwùlán", mean: "작업 표시줄" },
            { id: 5, category: "1. 기본 Windows UI 및 운영", zh: "开始菜单", py: "kāishǐ càidān", mean: "시작 메뉴" },
            { id: 6, category: "1. 기본 Windows UI 및 운영", zh: "设置", py: "shèzhì", mean: "설정" },
            { id: 7, category: "1. 기본 Windows UI 및 운영", zh: "控制面板", py: "kòngzhì miànbǎn", mean: "제어판" },
            { id: 8, category: "1. 기본 Windows UI 및 운영", zh: "属性", py: "shǔxìng", mean: "속성" },
            { id: 9, category: "1. 기본 Windows UI 및 운영", zh: "更新", py: "gēngxīn", mean: "업데이트" },
            { id: 10, category: "1. 기본 Windows UI 및 운영", zh: "重启", py: "chóngqǐ", mean: "재부팅" },
            { id: 11, category: "1. 기본 Windows UI 및 운영", zh: "关机", py: "guānjī", mean: "시스템 종료" },
            { id: 12, category: "1. 기본 Windows UI 및 운영", zh: "注销", py: "zhùxiāo", mean: "로그아웃" },
            { id: 13, category: "1. 기본 Windows UI 및 운영", zh: "快捷方式", py: "kuàijié fāngshì", mean: "바로가기" },
            { id: 14, category: "1. 기본 Windows UI 및 운영", zh: "剪贴板", py: "jiǎntiēbǎn", mean: "클립보드" },
            { id: 15, category: "1. 기본 Windows UI 및 운영", zh: "复制", py: "fùzhì", mean: "복사" },
            { id: 16, category: "1. 기본 Windows UI 및 운영", zh: "粘贴", py: "zhāntiē", mean: "붙여넣기" },
            { id: 17, category: "1. 기본 Windows UI 및 운영", zh: "剪切", py: "jiǎnqiē", mean: "잘라내기" },
            { id: 18, category: "1. 기본 Windows UI 및 운영", zh: "撤销", py: "chèxiāo", mean: "실행 취소" },
            { id: 19, category: "1. 기본 Windows UI 및 운영", zh: "确认", py: "quèrèn", mean: "확인 (OK)" },
            { id: 20, category: "1. 기본 Windows UI 및 운영", zh: "取消", py: "qǔxiāo", mean: "취소 (Cancel)" },

            // 2. 파일 및 디렉토리 관리
            { id: 21, category: "2. 파일 및 디렉토리 관리", zh: "文件", py: "wénjiàn", mean: "파일" },
            { id: 22, category: "2. 파일 및 디렉토리 관리", zh: "文件夹", py: "wénjiànjiā", mean: "폴더" },
            { id: 23, category: "2. 파일 및 디렉토리 관리", zh: "目录", py: "mùlù", mean: "디렉토리" },
            { id: 24, category: "2. 파일 및 디렉토리 관리", zh: "路径", py: "lùjìng", mean: "경로 (Path)" },
            { id: 25, category: "2. 파일 및 디렉토리 관리", zh: "扩展名", py: "kuòzhǎnmíng", mean: "확장자" },
            { id: 26, category: "2. 파일 및 디렉토리 관리", zh: "保存", py: "bǎocún", mean: "저장" },
            { id: 27, category: "2. 파일 및 디렉토리 관리", zh: "另存为", py: "lìng cún wéi", mean: "다른 이름 저장" },
            { id: 28, category: "2. 파일 및 디렉토리 관리", zh: "删除", py: "shānchú", mean: "삭제" },
            { id: 29, category: "2. 파일 및 디렉토리 관리", zh: "回收站", py: "huíshōuzhàn", mean: "휴지통" },
            { id: 30, category: "2. 파일 및 디렉토리 관리", zh: "压缩", py: "yāsuō", mean: "압축" },
            { id: 31, category: "2. 파일 및 디렉토리 관리", zh: "解压", py: "jiěyā", mean: "압축 해제" },
            { id: 32, category: "2. 파일 및 디렉토리 관리", zh: "隐藏", py: "yǐncáng", mean: "숨김" },
            { id: 33, category: "2. 파일 및 디렉토리 관리", zh: "只读", py: "zhǐdú", mean: "읽기 전용" },
            { id: 34, category: "2. 파일 및 디렉토리 관리", zh: "权限", py: "quánxiàn", mean: "권한" },
            { id: 35, category: "2. 파일 및 디렉토리 관리", zh: "共享", py: "gòngxiǎng", mean: "공유" },

            // 3. 하드웨어 및 장치
            { id: 36, category: "3. 하드웨어 및 장치", zh: "硬件", py: "yìngjiàn", mean: "하드웨어" },
            { id: 37, category: "3. 하드웨어 및 장치", zh: "处理器", py: "chǔlǐqì", mean: "프로세서 (CPU)" },
            { id: 38, category: "3. 하드웨어 및 장치", zh: "内存", py: "nèicún", mean: "메모리 (RAM)" },
            { id: 39, category: "3. 하드웨어 및 장치", zh: "显存", py: "xiǎncún", mean: "비디오 메모리" },
            { id: 40, category: "3. 하드웨어 및 장치", zh: "主板", py: "zhǔbǎn", mean: "메인보드" },
            { id: 41, category: "3. 하드웨어 및 장치", zh: "硬盘", py: "yìngpán", mean: "하드디스크" },
            { id: 42, category: "3. 하드웨어 및 장치", zh: "固态硬盘", py: "gùtài yìngpán", mean: "SSD" },
            { id: 43, category: "3. 하드웨어 및 장치", zh: "显卡", py: "xiǎnkǎ", mean: "그래픽 카드" },
            { id: 44, category: "3. 하드웨어 및 장치", zh: "网卡", py: "wǎngkǎ", mean: "네트워크 카드" },
            { id: 45, category: "3. 하드웨어 및 장치", zh: "显示器", py: "xiǎnshìqì", mean: "모니터" },
            { id: 46, category: "3. 하드웨어 및 장치", zh: "键盘", py: "jiànpán", mean: "키보드" },
            { id: 47, category: "3. 하드웨어 및 장치", zh: "鼠标", py: "shǔbiāo", mean: "마우스" },
            { id: 48, category: "3. 하드웨어 및 장치", zh: "驱动程序", py: "qūdòng chéngxù", mean: "장치 드라이버" },
            { id: 49, category: "3. 하드웨어 및 장치", zh: "外设", py: "wàishè", mean: "주변기기" },
            { id: 50, category: "3. 하드웨어 및 장치", zh: "接口", py: "jiēkǒu", mean: "인터페이스" },

            // 4. 네트워크 및 통신
            { id: 51, category: "4. 네트워크 및 통신", zh: "网络", py: "wǎngluò", mean: "네트워크" },
            { id: 52, category: "4. 네트워크 및 통신", zh: "服务器", py: "fúwùqì", mean: "서버" },
            { id: 53, category: "4. 네트워크 및 통신", zh: "客户端", py: "kèhùduān", mean: "클라이언트" },
            { id: 54, category: "4. 네트워크 및 통신", zh: "局域网", py: "júyùwǎng", mean: "LAN" },
            { id: 55, category: "4. 네트워크 및 통신", zh: "路由器", py: "lùyóuqì", mean: "라우터/공유기" },
            { id: 56, category: "4. 네트워크 및 통신", zh: "防火墙", py: "fánghuǒqiáng", mean: "방화벽" },
            { id: 57, category: "4. 네트워크 및 통신", zh: "端口", py: "duānkǒu", mean: "포트 (Port)" },
            { id: 58, category: "4. 네트워크 및 통신", zh: "协议", py: "xiéyì", mean: "프로토콜" },
            { id: 59, category: "4. 네트워크 및 통신", zh: "带宽", py: "dàikuān", mean: "대역폭" },
            { id: 60, category: "4. 네트워크 및 통신", zh: "延迟", py: "yánchí", mean: "지연 (Ping)" },
            { id: 61, category: "4. 네트워크 및 통신", zh: "数据包", py: "shùjùbāo", mean: "데이터 패킷" },
            { id: 62, category: "4. 네트워크 및 통신", zh: "连接", py: "liánjiē", mean: "연결" },
            { id: 63, category: "4. 네트워크 및 통신", zh: "断开", py: "duànkāi", mean: "연결 끊기" },
            { id: 64, category: "4. 네트워크 및 통신", zh: "上传", py: "shàngchuán", mean: "업로드" },
            { id: 65, category: "4. 네트워크 및 통신", zh: "下载", py: "xiàzài", mean: "다운로드" },

            // 5. 시스템 내부 및 보안
            { id: 66, category: "5. 시스템 내부 및 보안", zh: "任务管理器", py: "rènwù guǎnlǐqì", mean: "작업 관리자" },
            { id: 67, category: "5. 시스템 내부 및 보안", zh: "进程", py: "jìnchéng", mean: "프로세스" },
            { id: 68, category: "5. 시스템 내부 및 보안", zh: "线程", py: "xiànchéng", mean: "스레드" },
            { id: 69, category: "5. 시스템 내부 및 보안", zh: "服务", py: "fúwù", mean: "서비스" },
            { id: 70, category: "5. 시스템 내부 및 보안", zh: "注册表", py: "zhùcèbiǎo", mean: "레지스트리" },
            { id: 71, category: "5. 시스템 내부 및 보안", zh: "命令行", py: "mìnglìng háng", mean: "명령 프롬프트" },
            { id: 72, category: "5. 시스템 내부 및 보안", zh: "终端", py: "zhōngduān", mean: "터미널" },
            { id: 73, category: "5. 시스템 내부 및 보안", zh: "虚拟机", py: "xūnǐjī", mean: "가상 머신" },
            { id: 74, category: "5. 시스템 내부 및 보안", zh: "内存泄漏", py: "nèicún xièlòu", mean: "메모리 누수" },
            { id: 75, category: "5. 시스템 내부 및 보안", zh: "蓝屏", py: "lánpíng", mean: "블루스크린" },
            { id: 76, category: "5. 시스템 내부 및 보안", zh: "安全", py: "ānquán", mean: "보안" },
            { id: 77, category: "5. 시스템 내부 및 보안", zh: "漏洞", py: "lòudòng", mean: "취약점" },
            { id: 78, category: "5. 시스템 내부 및 보안", zh: "补丁", py: "bǔdīng", mean: "패치 (Patch)" },
            { id: 79, category: "5. 시스템 내부 및 보안", zh: "杀毒软件", py: "shādú ruǎnjiàn", mean: "백신 프로그램" },
            { id: 80, category: "5. 시스템 내부 및 보안", zh: "拦截", py: "lánjié", mean: "차단/인터셉트" },
            { id: 81, category: "5. 시스템 내부 및 보안", zh: "授权", py: "shòuquán", mean: "권한 부여" },
            { id: 82, category: "5. 시스템 내부 및 보안", zh: "认证", py: "rènzhèng", mean: "인증" },
            { id: 83, category: "5. 시스템 내부 및 보안", zh: "加密", py: "jiāmì", mean: "암호화" },
            { id: 84, category: "5. 시스템 내부 및 보안", zh: "解密", py: "jiěmì", mean: "복호화" },
            { id: 85, category: "5. 시스템 내부 및 보안", zh: "日志", py: "rìzhì", mean: "로그 (Log)" },

            // 6. 개발 및 소프트웨어
            { id: 86, category: "6. 개발 및 소프트웨어", zh: "软件", py: "ruǎnjiàn", mean: "소프트웨어" },
            { id: 87, category: "6. 개발 및 소프트웨어", zh: "源代码", py: "yuándàimǎ", mean: "소스 코드" },
            { id: 88, category: "6. 개발 및 소프트웨어", zh: "编译器", py: "biānyìqì", mean: "컴파일러" },
            { id: 89, category: "6. 개발 및 소프트웨어", zh: "调试", py: "tiáoshì", mean: "디버깅" },
            { id: 90, category: "6. 개발 및 소프트웨어", zh: "变量", py: "biànliàng", mean: "변수" },
            { id: 91, category: "6. 개발 및 소프트웨어", zh: "函数", py: "hánshù", mean: "함수" },
            { id: 92, category: "6. 개발 및 소프트웨어", zh: "应用程序接口", py: "yìngyòng chéngxù jiēkǒu", mean: "API" },
            { id: 93, category: "6. 개발 및 소프트웨어", zh: "脚本", py: "jiǎoběn", mean: "스크립트" },
            { id: 94, category: "6. 개발 및 소프트웨어", zh: "库", py: "kù", mean: "라이브러리" },
            { id: 95, category: "6. 개발 및 소프트웨어", zh: "框架", py: "kuàngjià", mean: "프레임워크" },
            { id: 96, category: "6. 개발 및 소프트웨어", zh: "部署", py: "bùshǔ", mean: "배포" },
            { id: 97, category: "6. 개발 및 소프트웨어", zh: "版本控制", py: "bǎnběn kòngzhì", mean: "버전 관리" },
            { id: 98, category: "6. 개발 및 소프트웨어", zh: "提交", py: "tíjiāo", mean: "커밋 (Commit)" },
            { id: 99, category: "6. 개발 및 소프트웨어", zh: "合并", py: "hébìng", mean: "병합 (Merge)" },
            { id: 100, category: "6. 개발 및 소프트웨어", zh: "错误", py: "cuòwù", mean: "오류 / 버그" },

            // 7. 팝업창 및 공통 버튼 (Dialog & Buttons)
            { id: 101, category: "7. 팝업창 및 공통 버튼", zh: "是", py: "shì", mean: "예 (Yes)" },
            { id: 102, category: "7. 팝업창 및 공통 버튼", zh: "否", py: "fǒu", mean: "아니오 (No)" },
            { id: 103, category: "7. 팝업창 및 공통 버튼", zh: "中止", py: "zhōngzhǐ", mean: "중단 (Abort)" },
            { id: 104, category: "7. 팝업창 및 공통 버튼", zh: "重试", py: "chóngshì", mean: "다시 시도 (Retry)" },
            { id: 105, category: "7. 팝업창 및 공통 버튼", zh: "忽略", py: "hūlüè", mean: "무시 (Ignore)" },
            { id: 106, category: "7. 팝업창 및 공통 버튼", zh: "允许", py: "yǔnxǔ", mean: "허용 (Allow)" },
            { id: 107, category: "7. 팝업창 및 공통 버튼", zh: "拒绝", py: "jùjué", mean: "거부 (Deny)" },
            { id: 108, category: "7. 팝업창 및 공통 버튼", zh: "阻止", py: "zǔzhǐ", mean: "차단 (Block)" },
            { id: 109, category: "7. 팝업창 및 공통 버튼", zh: "继续", py: "jìxù", mean: "계속 (Continue)" },
            { id: 110, category: "7. 팝업창 및 공통 버튼", zh: "确定", py: "quèdìng", mean: "확인 (OK)" },
            { id: 111, category: "7. 팝업창 및 공통 버튼", zh: "应用", py: "yìngyòng", mean: "적용 (Apply)" },
            { id: 112, category: "7. 팝업창 및 공통 버튼", zh: "下一步", py: "xià yí bù", mean: "다음 (Next)" },
            { id: 113, category: "7. 팝업창 및 공통 버튼", zh: "上一步", py: "shàng yí bù", mean: "뒤로 (Back)" },
            { id: 114, category: "7. 팝업창 및 공통 버튼", zh: "完成", py: "wánchéng", mean: "마침 (Finish)" },
            { id: 115, category: "7. 팝업창 및 공통 버튼", zh: "关闭", py: "guānbì", mean: "닫기 (Close)" },
            { id: 116, category: "7. 팝업창 및 공통 버튼", zh: "退出", py: "tuìchū", mean: "종료/나가기 (Exit)" },
            { id: 117, category: "7. 팝업창 및 공통 버튼", zh: "帮助", py: "bāngzhù", mean: "도움말 (Help)" },
            { id: 118, category: "7. 팝업창 및 공통 버튼", zh: "浏览", py: "liúlǎn", mean: "찾아보기(Browse)" },
            { id: 119, category: "7. 팝업창 및 공통 버튼", zh: "默认", py: "mòrèn", mean: "기본값 (Default)" },
            { id: 120, category: "7. 팝업창 및 공통 버튼", zh: "自定义", py: "zìdìngyì", mean: "사용자 지정" },

            // 8. 시스템 및 소프트웨어 설정 메뉴 (Settings Menu)
            { id: 121, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "常规", py: "chángguī", mean: "일반 (General)" },
            { id: 122, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "显示", py: "xiǎnshì", mean: "디스플레이" },
            { id: 123, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "账户", py: "zhànghù", mean: "계정 (Accounts)" },
            { id: 124, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "隐私", py: "yǐnsī", mean: "개인정보 보호" },
            { id: 125, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "语言和区域", py: "yǔyán hé qūyù", mean: "언어 및 지역" },
            { id: 126, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "个性化", py: "gèxìnghuà", mean: "개인 설정" },
            { id: 127, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "网络和互联网", py: "wǎngluò hé h.", mean: "네트워크 및 인터넷" },
            { id: 128, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "更新和安全", py: "gēngxīn hé ānquán", mean: "업데이트 및 보안" },
            { id: 129, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "高级系统设置", py: "gāojí xìtǒng shèzhì", mean: "고급 시스템 설정" },
            { id: 130, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "环境变量", py: "huánjìng biànliàng", mean: "환경 변수" },
            { id: 131, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "开发者选项", py: "kāifāzhě xuǎnxiàng", mean: "개발자 옵션" },
            { id: 132, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "代理", py: "dàilǐ", mean: "프록시 (Proxy)" },
            { id: 133, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "疑难解答", py: "yínán jiědá", mean: "문제 해결" },
            { id: 134, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "恢复", py: "huīfù", mean: "복구 (Recovery)" },
            { id: 135, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "启动", py: "qǐdòng", mean: "시작 프로그램" },
            { id: 136, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "存储", py: "cúnchǔ", mean: "저장소 (Storage)" },
            { id: 137, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "性能", py: "xìngnéng", mean: "성능" },
            { id: 138, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "通知", py: "tōngzhī", mean: "알림" },
            { id: 139, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "声音", py: "shēngyīn", mean: "소리 (Sound)" },
            { id: 140, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "蓝牙和其他设备", py: "lányá hé qítā..", mean: "블루투스 및 장치" }

        ]
    },
    // 두 번째 주제: HSK 2급
    "hsk2": {
        title: "HSK 2급 필수 단어",
        words: [
            // --- 1. 대명사 / 의문사 ---
            { id: 1, category: "1. 대명사/의문사", zh: "大家", py: "dàjiā", mean: "모두, 여러분" },
            { id: 2, category: "1. 대명사/의문사", zh: "您", py: "nín", mean: "당신 (존칭)" },
            { id: 3, category: "1. 대명사/의문사", zh: "它", py: "tā", mean: "그것 (사물/동물)" },
            { id: 4, category: "1. 대명사/의문사", zh: "为什么", py: "wèishénme", mean: "왜, 어째서" },
            { id: 5, category: "1. 대명사/의문사", zh: "每", py: "měi", mean: "매, 마다" },

            // --- 2. 명사 (사람/가족/직업) ---
            { id: 6, category: "2. 사람/가족", zh: "哥哥", py: "gēge", mean: "형, 오빠" },
            { id: 7, category: "2. 사람/가족", zh: "弟弟", py: "dìdi", mean: "남동생" },
            { id: 8, category: "2. 사람/가족", zh: "妹妹", py: "mèimei", mean: "여동생" },
            { id: 9, category: "2. 사람/가족", zh: "丈夫", py: "zhàngfu", mean: "남편" },
            { id: 10, category: "2. 사람/가족", zh: "妻子", py: "qīzi", mean: "아내" },
            { id: 11, category: "2. 사람/가족", zh: "孩子", py: "háizi", mean: "아이, 자녀" },
            { id: 12, category: "2. 사람/가족", zh: "男人", py: "nánrén", mean: "남자" },
            { id: 13, category: "2. 사람/가족", zh: "女人", py: "nǚrén", mean: "여자" },
            { id: 14, category: "2. 사람/가족", zh: "服务员", py: "fúwùyuán", mean: "종업원, 서비스원" },

            // --- 3. 명사 (사물/장소/시간) ---
            { id: 15, category: "3. 사물/장소", zh: "报纸", py: "bàozhǐ", mean: "신문" },
            { id: 16, category: "3. 사물/장소", zh: "宾馆", py: "bīnguǎn", mean: "호텔, 여관" },
            { id: 17, category: "3. 사물/장소", zh: "房间", py: "fángjiān", mean: "방" },
            { id: 18, category: "3. 사물/장소", zh: "教室", py: "jiàoshì", mean: "교실" },
            { id: 19, category: "3. 사물/장소", zh: "机场", py: "jīchǎng", mean: "공항" },
            { id: 20, category: "3. 사물/장소", zh: "路", py: "lù", mean: "길, 도로" },
            { id: 21, category: "3. 사물/장소", zh: "门", py: "mén", mean: "문" },
            { id: 22, category: "3. 사물/장소", zh: "票", py: "piào", mean: "표, 티켓" },
            { id: 23, category: "3. 사물/장소", zh: "铅笔", py: "qiānbǐ", mean: "연필" },
            { id: 24, category: "3. 사물/장소", zh: "手表", py: "shǒubiǎo", mean: "손목시계" },
            { id: 25, category: "3. 사물/장소", zh: "手机", py: "shǒujī", mean: "휴대폰" },
            { id: 26, category: "3. 사물/장소", zh: "事情", py: "shìqing", mean: "일, 사건" },
            { id: 27, category: "3. 사물/장소", zh: "意思", py: "yìsi", mean: "의미, 뜻" },
            { id: 28, category: "3. 사물/장소", zh: "课", py: "kè", mean: "수업, 과" },
            { id: 29, category: "3. 사물/장소", zh: "题", py: "tí", mean: "문제, 제목" },
            { id: 30, category: "3. 사물/장소", zh: "雪", py: "xuě", mean: "눈(Snow)" },
            { id: 31, category: "3. 사물/장소", zh: "药", py: "yào", mean: "약" },
            { id: 32, category: "3. 사물/장소", zh: "公共汽车", py: "gōnggòng qìchē", mean: "버스" },
            { id: 33, category: "3. 사물/장소", zh: "自行车", py: "zìxíngchē", mean: "자전거" },
            { id: 34, category: "3. 사물/장소", zh: "船", py: "chuán", mean: "배, 선박" },

            // --- 4. 명사 (음식/방위) ---
            { id: 35, category: "4. 음식/방위", zh: "鸡蛋", py: "jīdàn", mean: "계란" },
            { id: 36, category: "4. 음식/방위", zh: "咖啡", py: "kāfēi", mean: "커피" },
            { id: 37, category: "4. 음식/방위", zh: "面条", py: "miàntiáo", mean: "국수" },
            { id: 38, category: "4. 음식/방위", zh: "牛奶", py: "niúnǎi", mean: "우유" },
            { id: 39, category: "4. 음식/방위", zh: "羊肉", py: "yángròu", mean: "양고기" },
            { id: 40, category: "4. 음식/방위", zh: "西瓜", py: "xīguā", mean: "수박" },
            { id: 41, category: "4. 음식/방위", zh: "鱼", py: "yú", mean: "물고기, 생선" },
            { id: 42, category: "4. 음식/방위", zh: "左边", py: "zuǒbiān", mean: "왼쪽" },
            { id: 43, category: "4. 음식/방위", zh: "右边", py: "yòubiān", mean: "오른쪽" },
            { id: 44, category: "4. 음식/방위", zh: "旁边", py: "pángbiān", mean: "옆" },
            { id: 45, category: "4. 음식/방위", zh: "外面", py: "wàimiàn", mean: "밖, 바깥" },

            // --- 5. 동사 (행동/동작) ---
            { id: 46, category: "5. 동사 (동작)", zh: "穿", py: "chuān", mean: "입다, 신다" },
            { id: 47, category: "5. 동사 (동작)", zh: "洗", py: "xǐ", mean: "씻다, 빨다" },
            { id: 48, category: "5. 동사 (동작)", zh: "笑", py: "xiào", mean: "웃다" },
            { id: 49, category: "5. 동사 (동작)", zh: "哭", py: "kū", mean: "울다" },
            { id: 50, category: "5. 동사 (동작)", zh: "找", py: "zhǎo", mean: "찾다, 거슬러 주다" },
            { id: 51, category: "5. 동사 (동작)", zh: "给", py: "gěi", mean: "주다" },
            { id: 52, category: "5. 동사 (동작)", zh: "送", py: "sòng", mean: "보내다, 선물하다" },
            { id: 53, category: "5. 동사 (동작)", zh: "卖", py: "mài", mean: "팔다" },
            { id: 54, category: "5. 동사 (동작)", zh: "让", py: "ràng", mean: "양보하다, ~하게 하다" },
            { id: 55, category: "5. 동사 (동작)", zh: "进", py: "jìn", mean: "들어가다, 들어오다" },
            { id: 56, category: "5. 동사 (동작)", zh: "出", py: "chū", mean: "나가다, 나오다" },
            { id: 57, category: "5. 동사 (동작)", zh: "到", py: "dào", mean: "도착하다" },
            { id: 58, category: "5. 동사 (동작)", zh: "走", py: "zǒu", mean: "걷다, 가다" },
            { id: 59, category: "5. 동사 (동작)", zh: "等", py: "děng", mean: "기다리다" },
            { id: 60, category: "5. 동사 (동작)", zh: "起床", py: "qǐchuáng", mean: "일어나다, 기상하다" },
            { id: 61, category: "5. 동사 (동작)", zh: "上班", py: "shàngbān", mean: "출근하다" },
            { id: 62, category: "5. 동사 (동작)", zh: "休息", py: "xiūxi", mean: "쉬다, 휴식하다" },

            // --- 6. 동사 (인지/소통/기타) ---
            { id: 63, category: "6. 동사 (소통/기타)", zh: "知道", py: "zhīdào", mean: "알다" },
            { id: 64, category: "6. 동사 (소통/기타)", zh: "懂", py: "dǒng", mean: "이해하다, 알다" },
            { id: 65, category: "6. 동사 (소통/기타)", zh: "觉得", py: "juéde", mean: "~라고 생각하다, 느끼다" },
            { id: 66, category: "6. 동사 (소통/기타)", zh: "希望", py: "xīwàng", mean: "희망하다, 바라다" },
            { id: 67, category: "6. 동사 (소통/기타)", zh: "准备", py: "zhǔnbèi", mean: "준비하다" },
            { id: 68, category: "6. 동사 (소통/기타)", zh: "开始", py: "kāishǐ", mean: "시작하다" },
            { id: 69, category: "6. 동사 (소통/기타)", zh: "完", py: "wán", mean: "끝나다, 마치다" },
            { id: 70, category: "6. 동사 (소통/기타)", zh: "帮助", py: "bāngzhù", mean: "돕다" },
            { id: 71, category: "6. 동사 (소통/기타)", zh: "告诉", py: "gàosu", mean: "알려주다, 말하다" },
            { id: 72, category: "6. 동사 (소통/기타)", zh: "回答", py: "huídá", mean: "대답하다" },
            { id: 73, category: "6. 동사 (소통/기타)", zh: "介绍", py: "jièshào", mean: "소개하다" },
            { id: 74, category: "6. 동사 (소통/기타)", zh: "欢迎", py: "huānyíng", mean: "환영하다" },
            { id: 75, category: "6. 동사 (소통/기타)", zh: "生病", py: "shēngbìng", mean: "병에 걸리다" },
            { id: 76, category: "6. 동사 (소통/기타)", zh: "可能", py: "kěnéng", mean: "가능하다, 아마도" },
            { id: 77, category: "6. 동사 (소통/기타)", zh: "可以", py: "kěyǐ", mean: "~할 수 있다, 해도 좋다" },
            { id: 78, category: "6. 동사 (소통/기타)", zh: "要", py: "yào", mean: "원하다, ~해야 한다" },

            // --- 7. 여가 / 스포츠 ---
            { id: 79, category: "7. 여가/스포츠", zh: "唱歌", py: "chànggē", mean: "노래하다" },
            { id: 80, category: "7. 여가/스포츠", zh: "跳舞", py: "tiàowǔ", mean: "춤추다" },
            { id: 81, category: "7. 여가/스포츠", zh: "旅游", py: "lǚyóu", mean: "여행하다" },
            { id: 82, category: "7. 여가/스포츠", zh: "玩", py: "wán", mean: "놀다, 장난하다" },
            { id: 83, category: "7. 여가/스포츠", zh: "运动", py: "yùndòng", mean: "운동하다" },
            { id: 84, category: "7. 여가/스포츠", zh: "跑步", py: "pǎobù", mean: "달리기하다" },
            { id: 85, category: "7. 여가/스포츠", zh: "游泳", py: "yóuyǒng", mean: "수영하다" },
            { id: 86, category: "7. 여가/스포츠", zh: "打篮球", py: "dǎ lánqiú", mean: "농구하다" },
            { id: 87, category: "7. 여가/스포츠", zh: "踢足球", py: "tī zúqiú", mean: "축구하다" },

            // --- 8. 형용사 (상태/성질) ---
            { id: 88, category: "8. 형용사", zh: "好", py: "hǎo", mean: "좋다" },
            { id: 89, category: "8. 형용사", zh: "好吃", py: "hǎochī", mean: "맛있다" },
            { id: 90, category: "8. 형용사", zh: "大", py: "dà", mean: "크다" },
            { id: 91, category: "8. 형용사", zh: "小", py: "xiǎo", mean: "작다" },
            { id: 92, category: "8. 형용사", zh: "长", py: "cháng", mean: "길다" },
            { id: 93, category: "8. 형용사", zh: "高", py: "gāo", mean: "높다, 키가 크다" },
            { id: 94, category: "8. 형용사", zh: "新", py: "xīn", mean: "새롭다" },
            { id: 95, category: "8. 형용사", zh: "贵", py: "guì", mean: "비싸다" },
            { id: 96, category: "8. 형용사", zh: "便宜", py: "piányi", mean: "싸다, 저렴하다" },
            { id: 97, category: "8. 형용사", zh: "远", py: "yuǎn", mean: "멀다" },
            { id: 98, category: "8. 형용사", zh: "近", py: "jìn", mean: "가깝다" },
            { id: 99, category: "8. 형용사", zh: "快", py: "kuài", mean: "빠르다" },
            { id: 100, category: "8. 형용사", zh: "慢", py: "màn", mean: "느리다" },
            { id: 101, category: "8. 형용사", zh: "忙", py: "máng", mean: "바쁘다" },
            { id: 102, category: "8. 형용사", zh: "累", py: "lèi", mean: "피곤하다" },
            { id: 103, category: "8. 형용사", zh: "快乐", py: "kuàilè", mean: "즐겁다, 행복하다" },
            { id: 104, category: "8. 형용사", zh: "对", py: "duì", mean: "맞다, 옳다" },
            { id: 105, category: "8. 형용사", zh: "错", py: "cuò", mean: "틀리다, 잘못되다" },
            { id: 106, category: "8. 형용사", zh: "晴", py: "qíng", mean: "맑다" },
            { id: 107, category: "8. 형용사", zh: "阴", py: "yīn", mean: "흐리다" },

            // --- 9. 색상 ---
            { id: 108, category: "9. 색상", zh: "红", py: "hóng", mean: "붉다, 빨갛다" },
            { id: 109, category: "9. 색상", zh: "白", py: "bái", mean: "희다, 하얗다" },
            { id: 110, category: "9. 색상", zh: "黑", py: "hēi", mean: "검다, 까맣다" },

            // --- 10. 부사 ---
            { id: 111, category: "10. 부사", zh: "非常", py: "fēicháng", mean: "매우, 대단히" },
            { id: 112, category: "10. 부사", zh: "真", py: "zhēn", mean: "정말, 진짜로" },
            { id: 113, category: "10. 부사", zh: "最", py: "zuì", mean: "가장, 제일" },
            { id: 114, category: "10. 부사", zh: "也", py: "yě", mean: "~도 또한" },
            { id: 115, category: "10. 부사", zh: "还", py: "hái", mean: "아직, 여전히, 더" },
            { id: 116, category: "10. 부사", zh: "就", py: "jiù", mean: "곧, 바로" },
            { id: 117, category: "10. 부사", zh: "再", py: "zài", mean: "다시, 또 (미래)" },
            { id: 118, category: "10. 부사", zh: "正在", py: "zhèngzài", mean: "마침 ~하고 있다" },
            { id: 119, category: "10. 부사", zh: "已经", py: "yǐjīng", mean: "이미, 벌써" },
            { id: 120, category: "10. 부사", zh: "别", py: "bié", mean: "~하지 마라" },

            // --- 11. 전치사 / 접속사 ---
            { id: 121, category: "11. 전치사/접속사", zh: "比", py: "bǐ", mean: "~보다 (비교)" },
            { id: 122, category: "11. 전치사/접속사", zh: "从", py: "cóng", mean: "~부터 (기점)" },
            { id: 123, category: "11. 전치사/접속사", zh: "对", py: "duì", mean: "~에게, ~에 대하여" },
            { id: 124, category: "11. 전치사/접속사", zh: "离", py: "lí", mean: "~에서 떨어져 있다" },
            { id: 125, category: "11. 전치사/접속사", zh: "向", py: "xiàng", mean: "~을 향하여" },
            { id: 126, category: "11. 전치사/접속사", zh: "因为", py: "yīnwèi", mean: "왜냐하면, ~때문에" },
            { id: 127, category: "11. 전치사/접속사", zh: "所以", py: "suǒyǐ", mean: "그래서" },
            { id: 128, category: "11. 전치사/접속사", zh: "但是", py: "dànshì", mean: "그러나, 하지만" },

            // --- 12. 수사 / 양사 / 조사 ---
            { id: 129, category: "12. 수사/양사/조사", zh: "两", py: "liǎng", mean: "둘, 2 (양사 앞)" },
            { id: 130, category: "12. 수사/양사/조사", zh: "百", py: "bǎi", mean: "백 (100)" },
            { id: 131, category: "12. 수사/양사/조사", zh: "千", py: "qiān", mean: "천 (1,000)" },
            { id: 132, category: "12. 수사/양사/조사", zh: "第一", py: "dì-yī", mean: "제일, 첫째" },
            { id: 133, category: "12. 수사/양사/조사", zh: "次", py: "cì", mean: "번, 차례 (동량사)" },
            { id: 134, category: "12. 수사/양사/조사", zh: "件", py: "jiàn", mean: "벌, 건 (옷/일 양사)" },
            { id: 135, category: "12. 수사/양사/조사", zh: "公斤", py: "gōngjīn", mean: "킬로그램 (kg)" },
            { id: 136, category: "12. 수사/양사/조사", zh: "元", py: "yuán", mean: "원 (위안, 화폐 단위)" },
            { id: 137, category: "12. 수사/양사/조사", zh: "吧", py: "ba", mean: "~하자, ~지? (청유/추측)" },
            { id: 138, category: "12. 수사/양사/조사", zh: "得", py: "de", mean: "~하는 정도가 ~하다 (정도보어)" },
            { id: 139, category: "12. 수사/양사/조사", zh: "过", py: "guo", mean: "~한 적이 있다 (경험)" },
            { id: 140, category: "12. 수사/양사/조사", zh: "着", py: "zhe", mean: "~하고 있다 (상태 지속)" },

            // --- 13. 기타 기초 명사 (시간/날짜) ---
            { id: 141, category: "13. 기타 기초 단어", zh: "早上", py: "zǎoshang", mean: "아침" },
            { id: 142, category: "13. 기타 기초 단어", zh: "晚上", py: "wǎnshang", mean: "저녁, 밤" },
            { id: 143, category: "13. 기타 기초 단어", zh: "去年", py: "qùnián", mean: "작년" },
            { id: 144, category: "13. 기타 기초 단어", zh: "今年", py: "jīnnián", mean: "올해" },
            { id: 145, category: "13. 기타 기초 단어", zh: "明年", py: "míngnián", mean: "내년" },
            { id: 146, category: "13. 기타 기초 단어", zh: "生日", py: "shēngrì", mean: "생일" },
            { id: 147, category: "13. 기타 기초 단어", zh: "时间", py: "shíjiān", mean: "시간" },
            { id: 148, category: "13. 기타 기초 단어", zh: "小时", py: "xiǎoshí", mean: "시간 (Hour)" },
            { id: 149, category: "13. 기타 기초 단어", zh: "分钟", py: "fēnzhōng", mean: "분 (Minute)" },
            { id: 150, category: "13. 기타 기초 단어", zh: "问题", py: "wèntí", mean: "문제, 질문" }
        ]
    },
    // 세 번째 주제: HSK 3급
    "hsk3": {
        title: "HSK 3급 필수 단어",
        words: [
            // --- 1. 명사 (사람/가족/직업) ---
            { id: 1, category: "1. 사람/직업", zh: "阿姨", py: "āyí", mean: "이모, 아주머니" },
            { id: 2, category: "1. 사람/직업", zh: "叔叔", py: "shūshu", mean: "삼촌, 아저씨" },
            { id: 3, category: "1. 사람/직업", zh: "爷爷", py: "yéye", mean: "할아버지" },
            { id: 4, category: "1. 사람/직업", zh: "奶奶", py: "nǎinai", mean: "할머니" },
            { id: 5, category: "1. 사람/직업", zh: "邻居", py: "línjū", mean: "이웃" },
            { id: 6, category: "1. 사람/직업", zh: "同事", py: "tóngshì", mean: "직장 동료" },
            { id: 7, category: "1. 사람/직업", zh: "经理", py: "jīnglǐ", mean: "매니저, 사장" },
            { id: 8, category: "1. 사람/직업", zh: "客人", py: "kèrén", mean: "손님" },
            { id: 9, category: "1. 사람/직업", zh: "司机", py: "sījī", mean: "기사, 운전사" },
            { id: 10, category: "1. 사람/직업", zh: "校长", py: "xiàozhǎng", mean: "교장 총장" },

            // --- 2. 명사 (장소/공간) ---
            { id: 11, category: "2. 장소/공간", zh: "银行", py: "yínháng", mean: "은행" },
            { id: 12, category: "2. 장소/공간", zh: "超市", py: "chāoshì", mean: "슈퍼마켓" },
            { id: 13, category: "2. 장소/공간", zh: "公园", py: "gōngyuán", mean: "공원" },
            { id: 14, category: "2. 장소/공간", zh: "图书馆", py: "túshūguǎn", mean: "도서관" },
            { id: 15, category: "2. 장소/공간", zh: "办公室", py: "bàngōngshì", mean: "사무실" },
            { id: 16, category: "2. 장소/공간", zh: "洗手间", py: "xǐshǒujiān", mean: "화장실" },
            { id: 17, category: "2. 장소/공간", zh: "电梯", py: "diàntī", mean: "엘리베이터" },
            { id: 18, category: "2. 장소/공간", zh: "街道", py: "jiēdào", mean: "거리, 길거리" },
            { id: 19, category: "2. 장소/공간", zh: "城市", py: "chéngshì", mean: "도시" },
            { id: 20, category: "2. 장소/공간", zh: "地方", py: "dìfang", mean: "장소, 곳" },

            // --- 3. 명사 (사물/생활용품) ---
            { id: 21, category: "3. 사물/생활용품", zh: "护照", py: "hùzhào", mean: "여권" },
            { id: 22, category: "3. 사물/생활용품", zh: "信用卡", py: "xìnyòngkǎ", mean: "신용카드" },
            { id: 23, category: "3. 사물/생활용품", zh: "钱包", py: "qiánbāo", mean: "지갑" },
            { id: 24, category: "3. 사물/생활용품", zh: "行李箱", py: "xínglǐxiāng", mean: "캐리어, 트렁크" },
            { id: 25, category: "3. 사물/생활용품", zh: "伞", py: "sǎn", mean: "우산" },
            { id: 26, category: "3. 사물/생활용품", zh: "鞋", py: "xié", mean: "신발" },
            { id: 27, category: "3. 사물/생활용품", zh: "裙子", py: "qúnzi", mean: "치마" },
            { id: 28, category: "3. 사물/생활용품", zh: "裤子", py: "kùzi", mean: "바지" },
            { id: 29, category: "3. 사물/생활용품", zh: "衬衫", py: "chènshān", mean: "셔츠" },
            { id: 30, category: "3. 사물/생활용품", zh: "词典", py: "cídiǎn", mean: "사전" },
            { id: 31, category: "3. 사물/생활용품", zh: "菜单", py: "càidān", mean: "메뉴판" },
            { id: 32, category: "3. 사물/생활용품", zh: "空调", py: "kōngtiáo", mean: "에어컨" },
            { id: 33, category: "3. 사물/생활용품", zh: "冰箱", py: "bīngxiāng", mean: "냉장고" },
            { id: 34, category: "3. 사물/생활용품", zh: "照片", py: "zhàopiàn", mean: "사진" },
            { id: 35, category: "3. 사물/생활용품", zh: "照相机", py: "zhàoxiàngjī", mean: "카메라" },

            // --- 4. 명사 (시간/계절/추상) ---
            { id: 36, category: "4. 시간/계절/추상", zh: "季节", py: "jìjié", mean: "계절" },
            { id: 37, category: "4. 시간/계절/추상", zh: "春", py: "chūn", mean: "봄" },
            { id: 38, category: "4. 시간/계절/추상", zh: "夏", py: "xià", mean: "여름" },
            { id: 39, category: "4. 시간/계절/추상", zh: "秋", py: "qiū", mean: "가을" },
            { id: 40, category: "4. 시간/계절/추상", zh: "冬", py: "dōng", mean: "겨울" },
            { id: 41, category: "4. 시간/계절/추상", zh: "周末", py: "zhōumò", mean: "주말" },
            { id: 42, category: "4. 시간/계절/추상", zh: "节日", py: "jiérì", mean: "명절, 기념일" },
            { id: 43, category: "4. 시간/계절/추상", zh: "历史", py: "lìshǐ", mean: "역사" },
            { id: 44, category: "4. 시간/계절/추상", zh: "故事", py: "gùshi", mean: "이야기" },
            { id: 45, category: "4. 시간/계절/추상", zh: "声音", py: "shēngyīn", mean: "소리, 목소리" },
            { id: 46, category: "4. 시간/계절/추상", zh: "爱好", py: "àihào", mean: "취미" },
            { id: 47, category: "4. 시간/계절/추상", zh: "习惯", py: "xíguàn", mean: "습관" },
            { id: 48, category: "4. 시간/계절/추상", zh: "新闻", py: "xīnwén", mean: "뉴스" },
            { id: 49, category: "4. 시간/계절/추상", zh: "会议", py: "huìyì", mean: "회의" },
            { id: 50, category: "4. 시간/계절/추상", zh: "机会", py: "jīhuì", mean: "기회" },

            // --- 5. 동사 (신체/물리적 동작) ---
            { id: 51, category: "5. 동사 (물리적 동작)", zh: "搬", py: "bān", mean: "옮기다, 이사하다" },
            { id: 52, category: "5. 동사 (물리적 동작)", zh: "帮忙", py: "bāngmáng", mean: "도와주다" },
            { id: 53, category: "5. 동사 (물리적 동작)", zh: "打扫", py: "dǎsǎo", mean: "청소하다" },
            { id: 54, category: "5. 동사 (물리적 동작)", zh: "洗澡", py: "xǐzǎo", mean: "목욕하다, 샤워하다" },
            { id: 55, category: "5. 동사 (물리적 동작)", zh: "刷牙", py: "shuāyá", mean: "양치질하다" },
            { id: 56, category: "5. 동사 (물리적 동작)", zh: "拿", py: "ná", mean: "들다, 쥐다, 가져오다" },
            { id: 57, category: "5. 동사 (물리적 동작)", zh: "放", py: "fàng", mean: "놓다, 두다" },
            { id: 58, category: "5. 동사 (물리적 동작)", zh: "换", py: "huàn", mean: "바꾸다, 교환하다" },
            { id: 59, category: "5. 동사 (물리적 동작)", zh: "借", py: "jiè", mean: "빌리다, 빌려주다" },
            { id: 60, category: "5. 동사 (물리적 동작)", zh: "还", py: "huán", mean: "돌려주다, 반납하다" },
            { id: 61, category: "5. 동사 (물리적 동작)", zh: "爬山", py: "páshān", mean: "등산하다" },
            { id: 62, category: "5. 동사 (물리적 동작)", zh: "骑", py: "qí", mean: "(자전거/말 등을) 타다" },
            { id: 63, category: "5. 동사 (물리적 동작)", zh: "起飞", py: "qǐfēi", mean: "이륙하다" },
            { id: 64, category: "5. 동사 (물리적 동작)", zh: "上网", py: "shàngwǎng", mean: "인터넷을 하다" },
            { id: 65, category: "5. 동사 (물리적 동작)", zh: "发烧", py: "fāshāo", mean: "열이 나다" },

            // --- 6. 동사 (상태/인지/소통) ---
            { id: 66, category: "6. 동사 (인지/소통)", zh: "参加", py: "cānjiā", mean: "참가하다" },
            { id: 67, category: "6. 동사 (인지/소통)", zh: "举行", py: "jǔxíng", mean: "개최하다, 열다" },
            { id: 68, category: "6. 동사 (인지/소통)", zh: "发现", py: "fāxiàn", mean: "발견하다, 알아차리다" },
            { id: 69, category: "6. 동사 (인지/소통)", zh: "解决", py: "jiějué", mean: "해결하다" },
            { id: 70, category: "6. 동사 (인지/소통)", zh: "离开", py: "líkāi", mean: "떠나다, 벗어나다" },
            { id: 71, category: "6. 동사 (인지/소통)", zh: "聊天", py: "liáotiān", mean: "수다 떨다, 채팅하다" },
            { id: 72, category: "6. 동사 (인지/소통)", zh: "必须", py: "bìxū", mean: "반드시 ~해야 한다" },
            { id: 73, category: "6. 동사 (인지/소통)", zh: "需要", py: "xūyào", mean: "필요하다, 요구되다" },
            { id: 74, category: "6. 동사 (인지/소통)", zh: "变化", py: "biànhuà", mean: "변화하다" },
            { id: 75, category: "6. 동사 (인지/소통)", zh: "表示", py: "biǎoshì", mean: "표시하다, 나타내다" },
            { id: 76, category: "6. 동사 (인지/소통)", zh: "担心", py: "dānxīn", mean: "걱정하다" },
            { id: 77, category: "6. 동사 (인지/소통)", zh: "放心", py: "fàngxīn", mean: "안심하다" },
            { id: 78, category: "6. 동사 (인지/소통)", zh: "记得", py: "jìde", mean: "기억하고 있다" },
            { id: 79, category: "6. 동사 (인지/소통)", zh: "忘记", py: "wàngjì", mean: "잊다, 까먹다" },
            { id: 80, category: "6. 동사 (인지/소통)", zh: "决定", py: "juédìng", mean: "결정하다" },
            { id: 81, category: "6. 동사 (인지/소통)", zh: "了解", py: "liǎojiě", mean: "자세히 알다, 이해하다" },
            { id: 82, category: "6. 동사 (인지/소통)", zh: "明白", py: "míngbai", mean: "명백히 알다, 이해하다" },
            { id: 83, category: "6. 동사 (인지/소통)", zh: "认为", py: "rènwéi", mean: "여기다, 생각하다" },
            { id: 84, category: "6. 동사 (인지/소통)", zh: "相信", py: "xiāngxìn", mean: "믿다, 신뢰하다" },
            { id: 85, category: "6. 동사 (인지/소통)", zh: "选择", py: "xuǎnzé", mean: "선택하다" },
            { id: 86, category: "6. 동사 (인지/소통)", zh: "同意", py: "tóngyì", mean: "동의하다" },
            { id: 87, category: "6. 동사 (인지/소통)", zh: "以为", py: "yǐwéi", mean: "~인 줄 알았다 (착각)" },
            { id: 88, category: "6. 동사 (인지/소통)", zh: "遇到", py: "yùdào", mean: "마주치다, 조우하다" },
            { id: 89, category: "6. 동사 (인지/소통)", zh: "照顾", py: "zhàogù", mean: "돌보다, 보살피다" },
            { id: 90, category: "6. 동사 (인지/소통)", zh: "注意", py: "zhùyì", mean: "주의하다, 조심하다" },
            { id: 91, category: "6. 동사 (인지/소통)", zh: "祝", py: "zhù", mean: "축하하다, 기원하다" },
            { id: 92, category: "6. 동사 (인지/소통)", zh: "要求", py: "yāoqiú", mean: "요구하다" },
            { id: 93, category: "6. 동사 (인지/소통)", zh: "影响", py: "yǐngxiǎng", mean: "영향을 주다" },

            // --- 7. 형용사 (외모/상태) ---
            { id: 94, category: "7. 형용사", zh: "胖", py: "pàng", mean: "뚱뚱하다" },
            { id: 95, category: "7. 형용사", zh: "瘦", py: "shòu", mean: "마르다" },
            { id: 96, category: "7. 형용사", zh: "矮", py: "ǎi", mean: "키가 작다" },
            { id: 97, category: "7. 형용사", zh: "旧", py: "jiù", mean: "낡다, 오래되다" },
            { id: 98, category: "7. 형용사", zh: "聪明", py: "cōngming", mean: "똑똑하다" },
            { id: 99, category: "7. 형용사", zh: "可爱", py: "kě'ài", mean: "귀엽다" },
            { id: 100, category: "7. 형용사", zh: "干净", py: "gānjìng", mean: "깨끗하다" },
            { id: 101, category: "7. 형용사", zh: "安静", py: "ānjìng", mean: "조용하다" },
            { id: 102, category: "7. 형용사", zh: "安全", py: "ānquán", mean: "안전하다" },
            { id: 103, category: "7. 형용사", zh: "奇怪", py: "qíguài", mean: "이상하다, 기이하다" },
            { id: 104, category: "7. 형용사", zh: "清楚", py: "qīngchu", mean: "분명하다, 뚜렷하다" },
            { id: 105, category: "7. 형용사", zh: "舒服", py: "shūfu", mean: "편안하다, 기분 좋다" },
            { id: 106, category: "7. 형용사", zh: "容易", py: "róngyì", mean: "쉽다" },
            { id: 107, category: "7. 형용사", zh: "简单", py: "jiǎndān", mean: "간단하다" },
            { id: 108, category: "7. 형용사", zh: "甜", py: "tián", mean: "달다" },
            { id: 109, category: "7. 형용사", zh: "饱", py: "bǎo", mean: "배부르다" },
            { id: 110, category: "7. 형용사", zh: "渴", py: "kě", mean: "목마르다" },
            { id: 111, category: "7. 형용사", zh: "饿", py: "è", mean: "배고프다" },
            { id: 112, category: "7. 형용사", zh: "难过", py: "nánguò", mean: "슬프다, 괴롭다" },
            { id: 113, category: "7. 형용사", zh: "生气", py: "shēngqì", mean: "화나다" },
            { id: 114, category: "7. 형용사", zh: "新鲜", py: "xīnxiān", mean: "신선하다" },
            { id: 115, category: "7. 형용사", zh: "相同", py: "xiāngtóng", mean: "같다, 동일하다" },

            // --- 8. 부사 ---
            { id: 116, category: "8. 부사", zh: "才", py: "cái", mean: "비로소, 겨우" },
            { id: 117, category: "8. 부사", zh: "必须", py: "bìxū", mean: "반드시" },
            { id: 118, category: "8. 부사", zh: "当然", py: "dāngrán", mean: "당연히" },
            { id: 119, category: "8. 부사", zh: "几乎", py: "jīhū", mean: "거의" },
            { id: 120, category: "8. 부사", zh: "经常", py: "jīngcháng", mean: "자주, 늘" },
            { id: 121, category: "8. 부사", zh: "马上", py: "mǎshàng", mean: "즉시, 바로" },
            { id: 122, category: "8. 부사", zh: "其实", py: "qíshí", mean: "사실은, 실제로는" },
            { id: 123, category: "8. 부사", zh: "突然", py: "tūrán", mean: "갑자기" },
            { id: 124, category: "8. 부사", zh: "先", py: "xiān", mean: "먼저, 우선" },
            { id: 125, category: "8. 부사", zh: "一直", py: "yìzhí", mean: "계속, 줄곧" },
            { id: 126, category: "8. 부사", zh: "总是", py: "zǒngshì", mean: "항상, 늘" },
            { id: 127, category: "8. 부사", zh: "终于", py: "zhōngyú", mean: "마침내, 드디어" },
            { id: 128, category: "8. 부사", zh: "特别", py: "tèbié", mean: "특별히, 아주" },
            { id: 129, category: "8. 부사", zh: "更", py: "gèng", mean: "더욱, 한층 더" },
            { id: 130, category: "8. 부사", zh: "极", py: "jí", mean: "극히, 몹시 (~极了)" },

            // --- 9. 전치사/접속사/기타 ---
            { id: 131, category: "9. 접속사/전치사/기타", zh: "或者", py: "huòzhě", mean: "혹은, 아니면 (평서문)" },
            { id: 132, category: "9. 접속사/전치사/기타", zh: "还是", py: "háishì", mean: "아니면 (의문문)" },
            { id: 133, category: "9. 접속사/전치사/기타", zh: "为了", py: "wèile", mean: "~을 위하여" },
            { id: 134, category: "9. 접속사/전치사/기타", zh: "除了", py: "chúle", mean: "~을 제외하고" },
            { id: 135, category: "9. 접속사/전치사/기타", zh: "关于", py: "guānyú", mean: "~에 관하여" },
            { id: 136, category: "9. 접속사/전치사/기타", zh: "如果", py: "rúguǒ", mean: "만약 ~라면" },
            { id: 137, category: "9. 접속사/전치사/기타", zh: "虽然", py: "suīrán", mean: "비록 ~일지라도" },
            { id: 138, category: "9. 접속사/전치사/기타", zh: "只有", py: "zhǐyǒu", mean: "오직 ~해야만" },
            { id: 139, category: "9. 접속사/전치사/기타", zh: "然后", py: "ránhòu", mean: "그러고 나서" },
            { id: 140, category: "9. 접속사/전치사/기타", zh: "根据", py: "gēnjù", mean: "~에 근거하여" },
            
            // --- 10. 양사 ---
            { id: 141, category: "10. 양사", zh: "把", py: "bǎ", mean: "자루 (의자/우산 등 손잡이)" },
            { id: 142, category: "10. 양사", zh: "双", py: "shuāng", mean: "켤레, 쌍 (신발/젓가락 등)" },
            { id: 143, category: "10. 양사", zh: "辆", py: "liàng", mean: "대 (자동차/자전거 등)" },
            { id: 144, category: "10. 양사", zh: "条", py: "tiáo", mean: "마리, 벌 (길고 가느다란 것)" },
            { id: 145, category: "10. 양사", zh: "张", py: "zhāng", mean: "장 (종이/침대/책상 등)" },
            { id: 146, category: "10. 양사", zh: "瓶", py: "píng", mean: "병 (음료수 등)" },
            { id: 147, category: "10. 양사", zh: "层", py: "céng", mean: "층, 겹" },
            { id: 148, category: "10. 양사", zh: "段", py: "duàn", mean: "단락, 구간" },
            { id: 149, category: "10. 양사", zh: "种", py: "zhǒng", mean: "종류" },
            { id: 150, category: "10. 양사", zh: "角", py: "jiǎo", mean: "자오 (화폐 단위, 0.1위안)" }
        ]
    }
}