const vocabData = {
    "windows": {
        title: "Windows OS 필수 단어",
        words: [
            // 1. 기본 Windows UI 및 운영
            { id: 1, category: "1. 기본 Windows UI 및 운영", zh: "操作系统", py: "càozuò xìtǒng", mean: "운영체제 (OS)" },
            { id: 2, category: "1. 기본 Windows UI 및 운영", zh: "桌面", py: "zhuōmiàn", mean: "바탕화면" },
            { id: 3, category: "1. 기본 Windows UI 및 운영", zh: "窗口", py: "chuāngkǒu", mean: "창 (Window)" },
            { id: 4, category: "1. 기본 Windows UI 및 운영", zh: "任务栏", py: "rènwùlán", mean: "작업 표시줄" },
            { id: 5, category: "1. 기본 Windows UI 및 운영", zh: "开始菜单", py: "kāishǐ càidān", mean: "시작 메뉴" },
            { id: 6, category: "1. 기본 Windows UI 및 운영", zh: "设置", py: "shèzhì", mean: "설정" },
            { id: 7, category: "1. 기본 Windows UI 및 운영", zh: "控制面板", py: "kòngzhì miànbǎn", mean: "제어판" },
            { id: 8, category: "1. 기본 Windows UI 및 운영", zh: "属性", py: "shǔxìng", mean: "속성" },
            { id: 9, category: "1. 기본 Windows UI 및 운영", zh: "更新", py: "gēngxīn", mean: "업데이트" },
            { id: 10, category: "1. 기본 Windows UI 및 운영", zh: "重启", py: "chóngqǐ", mean: "재부팅" },
            { id: 11, category: "1. 기본 Windows UI 및 운영", zh: "关机", py: "guānjī", mean: "시스템 종료" },
            { id: 12, category: "1. 기본 Windows UI 및 운영", zh: "注销", py: "zhùxiāo", mean: "로그아웃" },
            { id: 13, category: "1. 기본 Windows UI 및 운영", zh: "快捷方式", py: "kuàijié fāngshì", mean: "바로가기" },
            { id: 14, category: "1. 기본 Windows UI 및 운영", zh: "剪贴板", py: "jiǎntiēbǎn", mean: "클립보드" },
            { id: 15, category: "1. 기본 Windows UI 및 운영", zh: "复制", py: "fùzhì", mean: "복사" },
            { id: 16, category: "1. 기본 Windows UI 및 운영", zh: "粘贴", py: "zhāntiē", mean: "붙여넣기" },
            { id: 17, category: "1. 기본 Windows UI 및 운영", zh: "剪切", py: "jiǎnqiē", mean: "잘라내기" },
            { id: 18, category: "1. 기본 Windows UI 및 운영", zh: "撤销", py: "chèxiāo", mean: "실행 취소" },
            { id: 19, category: "1. 기본 Windows UI 및 운영", zh: "确认", py: "quèrèn", mean: "확인 (OK)" },
            { id: 20, category: "1. 기본 Windows UI 및 운영", zh: "取消", py: "qǔxiāo", mean: "취소 (Cancel)" },

            // 2. 파일 및 디렉토리 관리
            { id: 21, category: "2. 파일 및 디렉토리 관리", zh: "文件", py: "wénjiàn", mean: "파일" },
            { id: 22, category: "2. 파일 및 디렉토리 관리", zh: "文件夹", py: "wénjiànjiā", mean: "폴더" },
            { id: 23, category: "2. 파일 및 디렉토리 관리", zh: "目录", py: "mùlù", mean: "디렉토리" },
            { id: 24, category: "2. 파일 및 디렉토리 관리", zh: "路径", py: "lùjìng", mean: "경로 (Path)" },
            { id: 25, category: "2. 파일 및 디렉토리 관리", zh: "扩展名", py: "kuòzhǎnmíng", mean: "확장자" },
            { id: 26, category: "2. 파일 및 디렉토리 관리", zh: "保存", py: "bǎocún", mean: "저장" },
            { id: 27, category: "2. 파일 및 디렉토리 관리", zh: "另存为", py: "lìng cún wéi", mean: "다른 이름 저장" },
            { id: 28, category: "2. 파일 및 디렉토리 관리", zh: "删除", py: "shānchú", mean: "삭제" },
            { id: 29, category: "2. 파일 및 디렉토리 관리", zh: "回收站", py: "huíshōuzhàn", mean: "휴지통" },
            { id: 30, category: "2. 파일 및 디렉토리 관리", zh: "压缩", py: "yāsuō", mean: "압축" },
            { id: 31, category: "2. 파일 및 디렉토리 관리", zh: "解压", py: "jiěyā", mean: "압축 해제" },
            { id: 32, category: "2. 파일 및 디렉토리 관리", zh: "隐藏", py: "yǐncáng", mean: "숨김" },
            { id: 33, category: "2. 파일 및 디렉토리 관리", zh: "只读", py: "zhǐdú", mean: "읽기 전용" },
            { id: 34, category: "2. 파일 및 디렉토리 관리", zh: "权限", py: "quánxiàn", mean: "권한" },
            { id: 35, category: "2. 파일 및 디렉토리 관리", zh: "共享", py: "gòngxiǎng", mean: "공유" },

            // 3. 하드웨어 및 장치
            { id: 36, category: "3. 하드웨어 및 장치", zh: "硬件", py: "yìngjiàn", mean: "하드웨어" },
            { id: 37, category: "3. 하드웨어 및 장치", zh: "处理器", py: "chǔlǐqì", mean: "프로세서 (CPU)" },
            { id: 38, category: "3. 하드웨어 및 장치", zh: "内存", py: "nèicún", mean: "메모리 (RAM)" },
            { id: 39, category: "3. 하드웨어 및 장치", zh: "显存", py: "xiǎncún", mean: "비디오 메모리" },
            { id: 40, category: "3. 하드웨어 및 장치", zh: "主板", py: "zhǔbǎn", mean: "메인보드" },
            { id: 41, category: "3. 하드웨어 및 장치", zh: "硬盘", py: "yìngpán", mean: "하드디스크" },
            { id: 42, category: "3. 하드웨어 및 장치", zh: "固态硬盘", py: "gùtài yìngpán", mean: "SSD" },
            { id: 43, category: "3. 하드웨어 및 장치", zh: "显卡", py: "xiǎnkǎ", mean: "그래픽 카드" },
            { id: 44, category: "3. 하드웨어 및 장치", zh: "网卡", py: "wǎngkǎ", mean: "네트워크 카드" },
            { id: 45, category: "3. 하드웨어 및 장치", zh: "显示器", py: "xiǎnshìqì", mean: "모니터" },
            { id: 46, category: "3. 하드웨어 및 장치", zh: "键盘", py: "jiànpán", mean: "키보드" },
            { id: 47, category: "3. 하드웨어 및 장치", zh: "鼠标", py: "shǔbiāo", mean: "마우스" },
            { id: 48, category: "3. 하드웨어 및 장치", zh: "驱动程序", py: "qūdòng chéngxù", mean: "장치 드라이버" },
            { id: 49, category: "3. 하드웨어 및 장치", zh: "外设", py: "wàishè", mean: "주변기기" },
            { id: 50, category: "3. 하드웨어 및 장치", zh: "接口", py: "jiēkǒu", mean: "인터페이스" },

            // 4. 네트워크 및 통신
            { id: 51, category: "4. 네트워크 및 통신", zh: "网络", py: "wǎngluò", mean: "네트워크" },
            { id: 52, category: "4. 네트워크 및 통신", zh: "服务器", py: "fúwùqì", mean: "서버" },
            { id: 53, category: "4. 네트워크 및 통신", zh: "客户端", py: "kèhùduān", mean: "클라이언트" },
            { id: 54, category: "4. 네트워크 및 통신", zh: "局域网", py: "júyùwǎng", mean: "LAN" },
            { id: 55, category: "4. 네트워크 및 통신", zh: "路由器", py: "lùyóuqì", mean: "라우터/공유기" },
            { id: 56, category: "4. 네트워크 및 통신", zh: "防火墙", py: "fánghuǒqiáng", mean: "방화벽" },
            { id: 57, category: "4. 네트워크 및 통신", zh: "端口", py: "duānkǒu", mean: "포트 (Port)" },
            { id: 58, category: "4. 네트워크 및 통신", zh: "协议", py: "xiéyì", mean: "프로토콜" },
            { id: 59, category: "4. 네트워크 및 통신", zh: "带宽", py: "dàikuān", mean: "대역폭" },
            { id: 60, category: "4. 네트워크 및 통신", zh: "延迟", py: "yánchí", mean: "지연 (Ping)" },
            { id: 61, category: "4. 네트워크 및 통신", zh: "数据包", py: "shùjùbāo", mean: "데이터 패킷" },
            { id: 62, category: "4. 네트워크 및 통신", zh: "连接", py: "liánjiē", mean: "연결" },
            { id: 63, category: "4. 네트워크 및 통신", zh: "断开", py: "duànkāi", mean: "연결 끊기" },
            { id: 64, category: "4. 네트워크 및 통신", zh: "上传", py: "shàngchuán", mean: "업로드" },
            { id: 65, category: "4. 네트워크 및 통신", zh: "下载", py: "xiàzài", mean: "다운로드" },

            // 5. 시스템 내부 및 보안
            { id: 66, category: "5. 시스템 내부 및 보안", zh: "任务管理器", py: "rènwù guǎnlǐqì", mean: "작업 관리자" },
            { id: 67, category: "5. 시스템 내부 및 보안", zh: "进程", py: "jìnchéng", mean: "프로세스" },
            { id: 68, category: "5. 시스템 내부 및 보안", zh: "线程", py: "xiànchéng", mean: "스레드" },
            { id: 69, category: "5. 시스템 내부 및 보안", zh: "服务", py: "fúwù", mean: "서비스" },
            { id: 70, category: "5. 시스템 내부 및 보안", zh: "注册表", py: "zhùcèbiǎo", mean: "레지스트리" },
            { id: 71, category: "5. 시스템 내부 및 보안", zh: "命令行", py: "mìnglìng háng", mean: "명령 프롬프트" },
            { id: 72, category: "5. 시스템 내부 및 보안", zh: "终端", py: "zhōngduān", mean: "터미널" },
            { id: 73, category: "5. 시스템 내부 및 보안", zh: "虚拟机", py: "xūnǐjī", mean: "가상 머신" },
            { id: 74, category: "5. 시스템 내부 및 보안", zh: "内存泄漏", py: "nèicún xièlòu", mean: "메모리 누수" },
            { id: 75, category: "5. 시스템 내부 및 보안", zh: "蓝屏", py: "lánpíng", mean: "블루스크린" },
            { id: 76, category: "5. 시스템 내부 및 보안", zh: "安全", py: "ānquán", mean: "보안" },
            { id: 77, category: "5. 시스템 내부 및 보안", zh: "漏洞", py: "lòudòng", mean: "취약점" },
            { id: 78, category: "5. 시스템 내부 및 보안", zh: "补丁", py: "bǔdīng", mean: "패치 (Patch)" },
            { id: 79, category: "5. 시스템 내부 및 보안", zh: "杀毒软件", py: "shādú ruǎnjiàn", mean: "백신 프로그램" },
            { id: 80, category: "5. 시스템 내부 및 보안", zh: "拦截", py: "lánjié", mean: "차단/인터셉트" },
            { id: 81, category: "5. 시스템 내부 및 보안", zh: "授权", py: "shòuquán", mean: "권한 부여" },
            { id: 82, category: "5. 시스템 내부 및 보안", zh: "认证", py: "rènzhèng", mean: "인증" },
            { id: 83, category: "5. 시스템 내부 및 보안", zh: "加密", py: "jiāmì", mean: "암호화" },
            { id: 84, category: "5. 시스템 내부 및 보안", zh: "解密", py: "jiěmì", mean: "복호화" },
            { id: 85, category: "5. 시스템 내부 및 보안", zh: "日志", py: "rìzhì", mean: "로그 (Log)" },

            // 6. 개발 및 소프트웨어
            { id: 86, category: "6. 개발 및 소프트웨어", zh: "软件", py: "ruǎnjiàn", mean: "소프트웨어" },
            { id: 87, category: "6. 개발 및 소프트웨어", zh: "源代码", py: "yuándàimǎ", mean: "소스 코드" },
            { id: 88, category: "6. 개발 및 소프트웨어", zh: "编译器", py: "biānyìqì", mean: "컴파일러" },
            { id: 89, category: "6. 개발 및 소프트웨어", zh: "调试", py: "tiáoshì", mean: "디버깅" },
            { id: 90, category: "6. 개발 및 소프트웨어", zh: "变量", py: "biànliàng", mean: "변수" },
            { id: 91, category: "6. 개발 및 소프트웨어", zh: "函数", py: "hánshù", mean: "함수" },
            { id: 92, category: "6. 개발 및 소프트웨어", zh: "应用程序接口", py: "yìngyòng chéngxù jiēkǒu", mean: "API" },
            { id: 93, category: "6. 개발 및 소프트웨어", zh: "脚本", py: "jiǎoběn", mean: "스크립트" },
            { id: 94, category: "6. 개발 및 소프트웨어", zh: "库", py: "kù", mean: "라이브러리" },
            { id: 95, category: "6. 개발 및 소프트웨어", zh: "框架", py: "kuàngjià", mean: "프레임워크" },
            { id: 96, category: "6. 개발 및 소프트웨어", zh: "部署", py: "bùshǔ", mean: "배포" },
            { id: 97, category: "6. 개발 및 소프트웨어", zh: "版本控制", py: "bǎnběn kòngzhì", mean: "버전 관리" },
            { id: 98, category: "6. 개발 및 소프트웨어", zh: "提交", py: "tíjiāo", mean: "커밋 (Commit)" },
            { id: 99, category: "6. 개발 및 소프트웨어", zh: "合并", py: "hébìng", mean: "병합 (Merge)" },
            { id: 100, category: "6. 개발 및 소프트웨어", zh: "错误", py: "cuòwù", mean: "오류 / 버그" },

            // 7. 팝업창 및 공통 버튼 (Dialog & Buttons)
            { id: 101, category: "7. 팝업창 및 공통 버튼", zh: "是", py: "shì", mean: "예 (Yes)" },
            { id: 102, category: "7. 팝업창 및 공통 버튼", zh: "否", py: "fǒu", mean: "아니오 (No)" },
            { id: 103, category: "7. 팝업창 및 공통 버튼", zh: "中止", py: "zhōngzhǐ", mean: "중단 (Abort)" },
            { id: 104, category: "7. 팝업창 및 공통 버튼", zh: "重试", py: "chóngshì", mean: "다시 시도 (Retry)" },
            { id: 105, category: "7. 팝업창 및 공통 버튼", zh: "忽略", py: "hūlüè", mean: "무시 (Ignore)" },
            { id: 106, category: "7. 팝업창 및 공통 버튼", zh: "允许", py: "yǔnxǔ", mean: "허용 (Allow)" },
            { id: 107, category: "7. 팝업창 및 공통 버튼", zh: "拒绝", py: "jùjué", mean: "거부 (Deny)" },
            { id: 108, category: "7. 팝업창 및 공통 버튼", zh: "阻止", py: "zǔzhǐ", mean: "차단 (Block)" },
            { id: 109, category: "7. 팝업창 및 공통 버튼", zh: "继续", py: "jìxù", mean: "계속 (Continue)" },
            { id: 110, category: "7. 팝업창 및 공통 버튼", zh: "确定", py: "quèdìng", mean: "확인 (OK)" },
            { id: 111, category: "7. 팝업창 및 공통 버튼", zh: "应用", py: "yìngyòng", mean: "적용 (Apply)" },
            { id: 112, category: "7. 팝업창 및 공통 버튼", zh: "下一步", py: "xià yí bù", mean: "다음 (Next)" },
            { id: 113, category: "7. 팝업창 및 공통 버튼", zh: "上一步", py: "shàng yí bù", mean: "뒤로 (Back)" },
            { id: 114, category: "7. 팝업창 및 공통 버튼", zh: "完成", py: "wánchéng", mean: "마침 (Finish)" },
            { id: 115, category: "7. 팝업창 및 공통 버튼", zh: "关闭", py: "guānbì", mean: "닫기 (Close)" },
            { id: 116, category: "7. 팝업창 및 공통 버튼", zh: "退出", py: "tuìchū", mean: "종료/나가기 (Exit)" },
            { id: 117, category: "7. 팝업창 및 공통 버튼", zh: "帮助", py: "bāngzhù", mean: "도움말 (Help)" },
            { id: 118, category: "7. 팝업창 및 공통 버튼", zh: "浏览", py: "liúlǎn", mean: "찾아보기(Browse)" },
            { id: 119, category: "7. 팝업창 및 공통 버튼", zh: "默认", py: "mòrèn", mean: "기본값 (Default)" },
            { id: 120, category: "7. 팝업창 및 공통 버튼", zh: "自定义", py: "zìdìngyì", mean: "사용자 지정" },

            // 8. 시스템 및 소프트웨어 설정 메뉴 (Settings Menu)
            { id: 121, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "常规", py: "chángguī", mean: "일반 (General)" },
            { id: 122, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "显示", py: "xiǎnshì", mean: "디스플레이" },
            { id: 123, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "账户", py: "zhànghù", mean: "계정 (Accounts)" },
            { id: 124, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "隐私", py: "yǐnsī", mean: "개인정보 보호" },
            { id: 125, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "语言和区域", py: "yǔyán hé qūyù", mean: "언어 및 지역" },
            { id: 126, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "个性化", py: "gèxìnghuà", mean: "개인 설정" },
            { id: 127, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "网络和互联网", py: "wǎngluò hé h.", mean: "네트워크 및 인터넷" },
            { id: 128, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "更新和安全", py: "gēngxīn hé ānquán", mean: "업데이트 및 보안" },
            { id: 129, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "高级系统设置", py: "gāojí xìtǒng shèzhì", mean: "고급 시스템 설정" },
            { id: 130, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "环境变量", py: "huánjìng biànliàng", mean: "환경 변수" },
            { id: 131, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "开发者选项", py: "kāifāzhě xuǎnxiàng", mean: "개발자 옵션" },
            { id: 132, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "代理", py: "dàilǐ", mean: "프록시 (Proxy)" },
            { id: 133, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "疑难解答", py: "yínán jiědá", mean: "문제 해결" },
            { id: 134, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "恢复", py: "huīfù", mean: "복구 (Recovery)" },
            { id: 135, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "启动", py: "qǐdòng", mean: "시작 프로그램" },
            { id: 136, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "存储", py: "cúnchǔ", mean: "저장소 (Storage)" },
            { id: 137, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "性能", py: "xìngnéng", mean: "성능" },
            { id: 138, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "通知", py: "tōngzhī", mean: "알림" },
            { id: 139, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "声音", py: "shēngyīn", mean: "소리 (Sound)" },
            { id: 140, category: "8. 시스템 및 소프트웨어 설정 메뉴", zh: "蓝牙和其他设备", py: "lányá hé qítā..", mean: "블루투스 및 장치" }

        ]
    },
    "chaihong": {
        title: "차이홍 단어(주황)",
        words: [
            // --- 1. 인사 / 대명사 ---
            { id: 1, category: "1. 인사 / 대명사", zh: "你好", py: "nǐ hǎo", mean: "안녕" },
            { id: 2, category: "1. 인사 / 대명사", zh: "初次见面", py: "chūcì jiànmiàn", mean: "처음 뵙겠습니다" },
            { id: 3, category: "1. 인사 / 대명사", zh: "我们", py: "wǒmen", mean: "우리" },
            { id: 4, category: "1. 인사 / 대명사", zh: "你们", py: "nǐmen", mean: "너희들" },
            { id: 5, category: "1. 인사 / 대명사", zh: "他", py: "tā", mean: "그" },
            { id: 6, category: "1. 인사 / 대명사", zh: "她", py: "tā", mean: "그녀" },
            { id: 7, category: "1. 인사 / 대명사", zh: "它", py: "tā", mean: "그것 (사물/동물)" },
            { id: 8, category: "1. 인사 / 대명사", zh: "晚安", py: "wǎn'ān", mean: "안녕히 주무세요" },
            { id: 9, category: "1. 인사 / 대명사", zh: "再见", py: "zàijiàn", mean: "안녕히 가세요" },
            { id: 10, category: "1. 인사 / 대명사", zh: "慢走", py: "màn zǒu", mean: "조심히 가세요" },
            { id: 11, category: "1. 인사 / 대명사", zh: "明天见", py: "míngtiān jiàn", mean: "내일 봐요" },
            { id: 12, category: "1. 인사 / 대명사", zh: "贵姓", py: "guìxìng", mean: "성함이 어떻게 되십니까" },
            { id: 13, category: "1. 인사 / 대명사", zh: "叫", py: "jiào", mean: "~라고 부르다" },
            { id: 14, category: "1. 인사 / 대명사", zh: "什么", py: "shénme", mean: "무엇" },
            { id: 15, category: "1. 인사 / 대명사", zh: "名字", py: "míngzi", mean: "이름" },
            { id: 16, category: "1. 인사 / 대명사", zh: "认识", py: "rènshi", mean: "알다" },
            { id: 17, category: "1. 인사 / 대명사", zh: "多多关照", py: "duōduō guānzhào", mean: "잘 부탁드립니다" },
            { id: 18, category: "1. 인사 / 대명사", zh: "这", py: "zhè", mean: "이것" },
            { id: 19, category: "1. 인사 / 대명사", zh: "这儿", py: "zhèr", mean: "여기" },
            { id: 20, category: "1. 인사 / 대명사", zh: "那", py: "nà", mean: "저것" },
            { id: 21, category: "1. 인사 / 대명사", zh: "谁", py: "shéi", mean: "누구" },
            { id: 22, category: "1. 인사 / 대명사", zh: "哪", py: "nǎ", mean: "어느" },
            { id: 23, category: "1. 인사 / 대명사", zh: "哪儿", py: "nǎr", mean: "어디" },
            { id: 24, category: "1. 인사 / 대명사", zh: "先生", py: "xiānsheng", mean: "선생님, 미스터" },
            { id: 25, category: "1. 인사 / 대명사", zh: "怎么", py: "zěnme", mean: "어떻게, 왜" },

            // --- 2. 사물 / 전자기기 ---
            { id: 26, category: "2. 사물 / 전자기기", zh: "电话", py: "diànhuà", mean: "전화" },
            { id: 27, category: "2. 사물 / 전자기기", zh: "电脑", py: "diànnǎo", mean: "컴퓨터" },
            { id: 28, category: "2. 사물 / 전자기기", zh: "笔记本电脑", py: "bǐjìběn diànnǎo", mean: "노트북" },
            { id: 29, category: "2. 사물 / 전자기기", zh: "平板电脑", py: "píngbǎn diànnǎo", mean: "태블릿 PC" },
            { id: 30, category: "2. 사물 / 전자기기", zh: "手机", py: "shǒujī", mean: "휴대폰" },
            { id: 31, category: "2. 사물 / 전자기기", zh: "充电器", py: "chōngdiànqì", mean: "충전기" },
            { id: 32, category: "2. 사물 / 전자기기", zh: "耳机", py: "ěrjī", mean: "이어폰" },
            { id: 33, category: "2. 사물 / 전자기기", zh: "电视", py: "diànshì", mean: "TV" },
            { id: 34, category: "2. 사물 / 전자기기", zh: "空调", py: "kōngtiáo", mean: "에어컨" },
            { id: 35, category: "2. 사물 / 전자기기", zh: "冰箱", py: "bīngxiāng", mean: "냉장고" },
            { id: 36, category: "2. 사물 / 전자기기", zh: "洗衣机", py: "xǐyījī", mean: "세탁기" },
            { id: 37, category: "2. 사물 / 전자기기", zh: "微波炉", py: "wēibōlú", mean: "전자레인지" },
            { id: 38, category: "2. 사물 / 전자기기", zh: "照相机", py: "zhàoxiàngjī", mean: "카메라" },
            { id: 39, category: "2. 사물 / 전자기기", zh: "吹风机", py: "chuīfēngjī", mean: "헤어드라이어" },
            { id: 40, category: "2. 사물 / 전자기기", zh: "打印机", py: "dǎyìnjī", mean: "프린터" },
            { id: 41, category: "2. 사물 / 전자기기", zh: "书", py: "shū", mean: "책" },
            { id: 42, category: "2. 사물 / 전자기기", zh: "桌子", py: "zhuōzi", mean: "책상" },
            { id: 43, category: "2. 사물 / 전자기기", zh: "椅子", py: "yǐzi", mean: "의자" },
            { id: 44, category: "2. 사물 / 전자기기", zh: "铅笔", py: "qiānbǐ", mean: "연필" },
            { id: 45, category: "2. 사물 / 전자기기", zh: "笔", py: "bǐ", mean: "펜" },
            { id: 46, category: "2. 사물 / 전자기기", zh: "书包", py: "shūbāo", mean: "책가방" },
            { id: 47, category: "2. 사물 / 전자기기", zh: "手表", py: "shǒubiǎo", mean: "손목시계" },
            { id: 48, category: "2. 사물 / 전자기기", zh: "钱包", py: "qiánbāo", mean: "지갑" },
            { id: 49, category: "2. 사물 / 전자기기", zh: "手绢", py: "shǒujuàn", mean: "손수건" },
            { id: 50, category: "2. 사물 / 전자기기", zh: "口罩", py: "kǒuzhào", mean: "마스크" },
            { id: 51, category: "2. 사물 / 전자기기", zh: "镜子", py: "jìngzi", mean: "거울" },
            { id: 52, category: "2. 사물 / 전자기기", zh: "梳子", py: "shūzi", mean: "빗" },
            { id: 53, category: "2. 사물 / 전자기기", zh: "名片", py: "míngpiàn", mean: "명함" },
            { id: 54, category: "2. 사물 / 전자기기", zh: "纸巾", py: "zhǐjīn", mean: "휴지" },
            { id: 55, category: "2. 사물 / 전자기기", zh: "雨伞", py: "yǔsǎn", mean: "우산" },
            { id: 56, category: "2. 사물 / 전자기기", zh: "照片", py: "zhàopiàn", mean: "사진" },

            // --- 3. 의류 / 패션 ---
            { id: 57, category: "3. 의류 / 패션", zh: "帽子", py: "màozi", mean: "모자" },
            { id: 58, category: "3. 의류 / 패션", zh: "皮鞋", py: "píxié", mean: "구두" },
            { id: 59, category: "3. 의류 / 패션", zh: "运动鞋", py: "yùndòngxié", mean: "운동화" },
            { id: 60, category: "3. 의류 / 패션", zh: "裤子", py: "kùzi", mean: "바지" },
            { id: 61, category: "3. 의류 / 패션", zh: "牛仔裤", py: "niúzǎikù", mean: "청바지" },
            { id: 62, category: "3. 의류 / 패션", zh: "裙子", py: "qúnzi", mean: "치마" },
            { id: 63, category: "3. 의류 / 패션", zh: "连衣裙", py: "liányīqún", mean: "원피스" },
            { id: 64, category: "3. 의류 / 패션", zh: "大衣", py: "dàyī", mean: "외투, 코트" },
            { id: 65, category: "3. 의류 / 패션", zh: "衬衫", py: "chènshān", mean: "셔츠" },
            { id: 66, category: "3. 의류 / 패션", zh: "袜子", py: "wàzi", mean: "양말" },
            { id: 67, category: "3. 의류 / 패션", zh: "手套", py: "shǒutào", mean: "장갑" },

            // --- 4. 시간 / 날짜 / 날씨 ---
            { id: 68, category: "4. 시간 / 날짜 / 날씨", zh: "时间", py: "shíjiān", mean: "시간" },
            { id: 69, category: "4. 시간 / 날짜 / 날씨", zh: "岁", py: "suì", mean: "살, 세 (나이)" },
            { id: 70, category: "4. 시간 / 날짜 / 날씨", zh: "年纪", py: "niánjì", mean: "연세" },
            { id: 71, category: "4. 시간 / 날짜 / 날씨", zh: "今天", py: "jīntiān", mean: "오늘" },
            { id: 72, category: "4. 시간 / 날짜 / 날씨", zh: "前天", py: "qiántiān", mean: "그제" },
            { id: 73, category: "4. 시간 / 날짜 / 날씨", zh: "昨天", py: "zuótiān", mean: "어제" },
            { id: 74, category: "4. 시간 / 날짜 / 날씨", zh: "明天", py: "míngtiān", mean: "내일" },
            { id: 75, category: "4. 시간 / 날짜 / 날씨", zh: "后天", py: "hòutiān", mean: "모레" },
            { id: 76, category: "4. 시간 / 날짜 / 날씨", zh: "现在", py: "xiànzài", mean: "지금" },
            { id: 77, category: "4. 시간 / 날짜 / 날씨", zh: "早上", py: "zǎoshang", mean: "아침" },
            { id: 78, category: "4. 시간 / 날짜 / 날씨", zh: "上午", py: "shàngwǔ", mean: "오전" },
            { id: 79, category: "4. 시간 / 날짜 / 날씨", zh: "中午", py: "zhōngwǔ", mean: "정오, 점심" },
            { id: 80, category: "4. 시간 / 날짜 / 날씨", zh: "下午", py: "xiàwǔ", mean: "오후" },
            { id: 81, category: "4. 시간 / 날짜 / 날씨", zh: "晚上", py: "wǎnshang", mean: "저녁" },
            { id: 82, category: "4. 시간 / 날짜 / 날씨", zh: "夜晚", py: "yèwǎn", mean: "밤, 야간" },
            { id: 83, category: "4. 시간 / 날짜 / 날씨", zh: "凌晨", py: "língchén", mean: "새벽" },
            { id: 84, category: "4. 시간 / 날짜 / 날씨", zh: "月", py: "yuè", mean: "월, 달" },
            { id: 85, category: "4. 시간 / 날짜 / 날씨", zh: "号", py: "hào", mean: "일(날짜), 번호" },
            { id: 86, category: "4. 시간 / 날짜 / 날씨", zh: "星期", py: "xīngqī", mean: "요일" },
            { id: 87, category: "4. 시간 / 날짜 / 날씨", zh: "星期天", py: "xīngqītiān", mean: "일요일" },
            { id: 88, category: "4. 시간 / 날짜 / 날씨", zh: "周", py: "zhōu", mean: "주" },
            { id: 89, category: "4. 시간 / 날짜 / 날씨", zh: "点", py: "diǎn", mean: "시" },
            { id: 90, category: "4. 시간 / 날짜 / 날씨", zh: "分", py: "fēn", mean: "분" },
            { id: 91, category: "4. 시간 / 날짜 / 날씨", zh: "刻", py: "kè", mean: "15분" },
            { id: 92, category: "4. 시간 / 날짜 / 날씨", zh: "半", py: "bàn", mean: "반, 30분" },
            { id: 93, category: "4. 시간 / 날짜 / 날씨", zh: "差", py: "chà", mean: "~전이다, 부족하다" },
            { id: 94, category: "4. 시간 / 날짜 / 날씨", zh: "天气", py: "tiānqì", mean: "날씨" },
            { id: 95, category: "4. 시간 / 날짜 / 날씨", zh: "暖和", py: "nuǎnhuo", mean: "따뜻하다" },
            { id: 96, category: "4. 시간 / 날짜 / 날씨", zh: "热", py: "rè", mean: "덥다" },
            { id: 97, category: "4. 시간 / 날짜 / 날씨", zh: "冷", py: "lěng", mean: "춥다" },
            { id: 98, category: "4. 시간 / 날짜 / 날씨", zh: "凉快", py: "liángkuai", mean: "시원하다" },
            { id: 99, category: "4. 시간 / 날짜 / 날씨", zh: "干燥", py: "gānzào", mean: "건조하다" },
            { id: 100, category: "4. 시간 / 날짜 / 날씨", zh: "晴", py: "qíng", mean: "맑다" },
            { id: 101, category: "4. 시간 / 날짜 / 날씨", zh: "阴", py: "yīn", mean: "흐리다" },
            { id: 102, category: "4. 시간 / 날짜 / 날씨", zh: "多云", py: "duōyún", mean: "구름이 많다" },
            { id: 103, category: "4. 시간 / 날짜 / 날씨", zh: "下雨", py: "xiàyǔ", mean: "비가 오다" },
            { id: 104, category: "4. 시간 / 날짜 / 날씨", zh: "下雪", py: "xiàxuě", mean: "눈이 오다" },
            { id: 105, category: "4. 시간 / 날짜 / 날씨", zh: "刮风", py: "guāfēng", mean: "바람이 불다" },

            // --- 5. 사람 / 직업 / 가족 ---
            { id: 106, category: "5. 사람 / 직업 / 가족", zh: "老师", py: "lǎoshī", mean: "선생님" },
            { id: 107, category: "5. 사람 / 직업 / 가족", zh: "学生", py: "xuésheng", mean: "학생" },
            { id: 108, category: "5. 사람 / 직업 / 가족", zh: "老板", py: "lǎobǎn", mean: "사장님" },
            { id: 109, category: "5. 사람 / 직업 / 가족", zh: "同事", py: "tóngshì", mean: "동료" },
            { id: 110, category: "5. 사람 / 직업 / 가족", zh: "客户", py: "kèhù", mean: "거래처, 고객" },
            { id: 111, category: "5. 사람 / 직업 / 가족", zh: "顾客", py: "gùkè", mean: "손님" },
            { id: 112, category: "5. 사람 / 직업 / 가족", zh: "朋友", py: "péngyou", mean: "친구" },
            { id: 113, category: "5. 사람 / 직업 / 가족", zh: "同学", py: "tóngxué", mean: "반 친구" },
            { id: 114, category: "5. 사람 / 직업 / 가족", zh: "室友", py: "shìyǒu", mean: "룸메이트" },
            { id: 115, category: "5. 사람 / 직업 / 가족", zh: "同桌", py: "tóngzhuō", mean: "짝꿍" },
            { id: 116, category: "5. 사람 / 직업 / 가족", zh: "邻居", py: "línjū", mean: "이웃" },
            { id: 117, category: "5. 사람 / 직업 / 가족", zh: "房东", py: "fángdōng", mean: "집주인" },
            { id: 118, category: "5. 사람 / 직업 / 가족", zh: "上班族", py: "shàngbānzú", mean: "직장인" },
            { id: 119, category: "5. 사람 / 직업 / 가족", zh: "公务员", py: "gōngwùyuán", mean: "공무원" },
            { id: 120, category: "5. 사람 / 직업 / 가족", zh: "演员", py: "yǎnyuán", mean: "배우" },
            { id: 121, category: "5. 사람 / 직업 / 가족", zh: "歌手", py: "gēshǒu", mean: "가수" },
            { id: 122, category: "5. 사람 / 직업 / 가족", zh: "医生", py: "yīshēng", mean: "의사" },
            { id: 123, category: "5. 사람 / 직업 / 가족", zh: "护士", py: "hùshi", mean: "간호사" },
            { id: 124, category: "5. 사람 / 직업 / 가족", zh: "厨师", py: "chúshī", mean: "요리사" },
            { id: 125, category: "5. 사람 / 직업 / 가족", zh: "警察", py: "jǐngchá", mean: "경찰" },
            { id: 126, category: "5. 사람 / 직업 / 가족", zh: "消防员", py: "xiāofángyuán", mean: "소방관" },
            { id: 127, category: "5. 사람 / 직업 / 가족", zh: "飞行员", py: "fēixíngyuán", mean: "조종사" },
            { id: 128, category: "5. 사람 / 직업 / 가족", zh: "设计师", py: "shèjìshī", mean: "디자이너" },
            { id: 129, category: "5. 사람 / 직업 / 가족", zh: "作家", py: "zuòjiā", mean: "작가" },
            { id: 130, category: "5. 사람 / 직업 / 가족", zh: "播音员", py: "bōyīnyuán", mean: "아나운서" },
            { id: 131, category: "5. 사람 / 직업 / 가족", zh: "推销员", py: "tuīxiāoyuán", mean: "세일즈맨" },
            { id: 132, category: "5. 사람 / 직업 / 가족", zh: "家人", py: "jiārén", mean: "가족" },
            { id: 133, category: "5. 사람 / 직업 / 가족", zh: "亲戚", py: "qīnqi", mean: "친척" },
            { id: 134, category: "5. 사람 / 직업 / 가족", zh: "兄弟姐妹", py: "xiōngdì jiěmèi", mean: "형제자매" },
            { id: 135, category: "5. 사람 / 직업 / 가족", zh: "爷爷", py: "yéye", mean: "할아버지" },
            { id: 136, category: "5. 사람 / 직업 / 가족", zh: "奶奶", py: "nǎinai", mean: "할머니" },
            { id: 137, category: "5. 사람 / 직업 / 가족", zh: "外公", py: "wàigōng", mean: "외할아버지" },
            { id: 138, category: "5. 사람 / 직업 / 가족", zh: "外婆", py: "wàipó", mean: "외할머니" },
            { id: 139, category: "5. 사람 / 직업 / 가족", zh: "爸爸", py: "bàba", mean: "아빠" },
            { id: 140, category: "5. 사람 / 직업 / 가족", zh: "妈妈", py: "māma", mean: "엄마" },
            { id: 141, category: "5. 사람 / 직업 / 가족", zh: "哥哥", py: "gēge", mean: "형, 오빠" },
            { id: 142, category: "5. 사람 / 직업 / 가족", zh: "姐姐", py: "jiějie", mean: "누나, 언니" },
            { id: 143, category: "5. 사람 / 직업 / 가족", zh: "弟弟", py: "dìdi", mean: "남동생" },
            { id: 144, category: "5. 사람 / 직업 / 가족", zh: "妹妹", py: "mèimei", mean: "여동생" },
            { id: 145, category: "5. 사람 / 직업 / 가족", zh: "儿子", py: "érzi", mean: "아들" },
            { id: 146, category: "5. 사람 / 직업 / 가족", zh: "女儿", py: "nǚ'ér", mean: "딸" },
            { id: 147, category: "5. 사람 / 직업 / 가족", zh: "孙子", py: "sūnzi", mean: "손자" },
            { id: 148, category: "5. 사람 / 직업 / 가족", zh: "孙女", py: "sūnnǚ", mean: "손녀" },
            { id: 149, category: "5. 사람 / 직업 / 가족", zh: "丈夫", py: "zhàngfu", mean: "남편" },
            { id: 150, category: "5. 사람 / 직업 / 가족", zh: "妻子", py: "qīzi", mean: "아내" },
            { id: 151, category: "5. 사람 / 직업 / 가족", zh: "孩子", py: "háizi", mean: "아이" },

            // --- 6. 장소 / 교통 / 위치 ---
            { id: 152, category: "6. 장소 / 교통 / 위치", zh: "国", py: "guó", mean: "나라" },
            { id: 153, category: "6. 장소 / 교통 / 위치", zh: "中国", py: "Zhōngguó", mean: "중국" },
            { id: 154, category: "6. 장소 / 교통 / 위치", zh: "美国", py: "Měiguó", mean: "미국" },
            { id: 155, category: "6. 장소 / 교통 / 위치", zh: "日本", py: "Rìběn", mean: "일본" },
            { id: 156, category: "6. 장소 / 교통 / 위치", zh: "北京", py: "Běijīng", mean: "베이징" },
            { id: 157, category: "6. 장소 / 교통 / 위치", zh: "上海", py: "Shànghǎi", mean: "상하이" },
            { id: 158, category: "6. 장소 / 교통 / 위치", zh: "公司", py: "gōngsī", mean: "회사" },
            { id: 159, category: "6. 장소 / 교통 / 위치", zh: "学校", py: "xuéxiào", mean: "학교" },
            { id: 160, category: "6. 장소 / 교통 / 위치", zh: "医院", py: "yīyuàn", mean: "병원" },
            { id: 161, category: "6. 장소 / 교통 / 위치", zh: "银行", py: "yínháng", mean: "은행" },
            { id: 162, category: "6. 장소 / 교통 / 위치", zh: "邮局", py: "yóujú", mean: "우체국" },
            { id: 163, category: "6. 장소 / 교통 / 위치", zh: "商店", py: "shāngdiàn", mean: "상점" },
            { id: 164, category: "6. 장소 / 교통 / 위치", zh: "超市", py: "chāoshì", mean: "슈퍼마켓" },
            { id: 165, category: "6. 장소 / 교통 / 위치", zh: "饭馆", py: "fànguǎn", mean: "식당" },
            { id: 166, category: "6. 장소 / 교통 / 위치", zh: "咖啡", py: "kāfēi", mean: "커피(숍)" },
            { id: 167, category: "6. 장소 / 교통 / 위치", zh: "图书馆", py: "túshūguǎn", mean: "도서관" },
            { id: 168, category: "6. 장소 / 교통 / 위치", zh: "书店", py: "shūdiàn", mean: "서점" },
            { id: 169, category: "6. 장소 / 교통 / 위치", zh: "电影院", py: "diànyǐngyuàn", mean: "영화관" },
            { id: 170, category: "6. 장소 / 교통 / 위치", zh: "公安局", py: "gōng'ānjú", mean: "공안국, 경찰서" },
            { id: 171, category: "6. 장소 / 교통 / 위치", zh: "机场", py: "jīchǎng", mean: "공항" },
            { id: 172, category: "6. 장소 / 교통 / 위치", zh: "地铁站", py: "dìtiězhàn", mean: "지하철역" },
            { id: 173, category: "6. 장소 / 교통 / 위치", zh: "停车场", py: "tíngchēchǎng", mean: "주차장" },
            { id: 174, category: "6. 장소 / 교통 / 위치", zh: "公园", py: "gōngyuán", mean: "공원" },
            { id: 175, category: "6. 장소 / 교통 / 위치", zh: "动物园", py: "dòngwùyuán", mean: "동물원" },
            { id: 176, category: "6. 장소 / 교통 / 위치", zh: "游乐场", py: "yóulèchǎng", mean: "놀이공원" },
            { id: 177, category: "6. 장소 / 교통 / 위치", zh: "网吧", py: "wǎngbā", mean: "PC방" },
            { id: 178, category: "6. 장소 / 교통 / 위치", zh: "购物中心", py: "gòuwù zhōngxīn", mean: "쇼핑센터" },
            { id: 179, category: "6. 장소 / 교통 / 위치", zh: "家", py: "jiā", mean: "집" },
            { id: 180, category: "6. 장소 / 교통 / 위치", zh: "宿舍", py: "sùshè", mean: "기숙사" },
            { id: 181, category: "6. 장소 / 교통 / 위치", zh: "房间", py: "fángjiān", mean: "방" },
            { id: 182, category: "6. 장소 / 교통 / 위치", zh: "卧室", py: "wòshì", mean: "침실" },
            { id: 183, category: "6. 장소 / 교통 / 위치", zh: "客厅", py: "kètīng", mean: "거실" },
            { id: 184, category: "6. 장소 / 교통 / 위치", zh: "厨房", py: "chúfáng", mean: "주방" },
            { id: 185, category: "6. 장소 / 교통 / 위치", zh: "洗手间", py: "xǐshǒujiān", mean: "화장실" },
            { id: 186, category: "6. 장소 / 교통 / 위치", zh: "阳台", py: "yángtái", mean: "베란다" },
            { id: 187, category: "6. 장소 / 교통 / 위치", zh: "办公室", py: "bàngōngshì", mean: "사무실" },
            { id: 188, category: "6. 장소 / 교통 / 위치", zh: "教室", py: "jiàoshì", mean: "교실" },
            { id: 189, category: "6. 장소 / 교통 / 위치", zh: "操场", py: "cāochǎng", mean: "운동장" },
            { id: 190, category: "6. 장소 / 교통 / 위치", zh: "里", py: "lǐ", mean: "안, 속" },
            { id: 191, category: "6. 장소 / 교통 / 위치", zh: "在", py: "zài", mean: "~에 있다, ~에서" },

            // --- 7. 신체 / 건강 ---
            { id: 192, category: "7. 신체 / 건강", zh: "身体", py: "shēntǐ", mean: "신체, 몸" },
            { id: 193, category: "7. 신체 / 건강", zh: "头", py: "tóu", mean: "머리" },
            { id: 194, category: "7. 신체 / 건강", zh: "脸", py: "liǎn", mean: "얼굴" },
            { id: 195, category: "7. 신체 / 건강", zh: "眼睛", py: "yǎnjing", mean: "눈" },
            { id: 196, category: "7. 신체 / 건강", zh: "鼻子", py: "bízi", mean: "코" },
            { id: 197, category: "7. 신체 / 건강", zh: "耳朵", py: "ěrduo", mean: "귀" },
            { id: 198, category: "7. 신체 / 건강", zh: "嘴", py: "zuǐ", mean: "입" },
            { id: 199, category: "7. 신체 / 건강", zh: "牙", py: "yá", mean: "치아" },
            { id: 200, category: "7. 신체 / 건강", zh: "脖子", py: "bózi", mean: "목" },
            { id: 201, category: "7. 신체 / 건강", zh: "嗓子", py: "sǎngzi", mean: "목구멍, 목소리" },
            { id: 202, category: "7. 신체 / 건강", zh: "肩膀", py: "jiānbǎng", mean: "어깨" },
            { id: 203, category: "7. 신체 / 건강", zh: "胳膊", py: "gēbo", mean: "팔" },
            { id: 204, category: "7. 신체 / 건강", zh: "手", py: "shǒu", mean: "손" },
            { id: 205, category: "7. 신체 / 건강", zh: "腰", py: "yāo", mean: "허리" },
            { id: 206, category: "7. 신체 / 건강", zh: "肚子", py: "dùzi", mean: "배" },
            { id: 207, category: "7. 신체 / 건강", zh: "屁股", py: "pìgu", mean: "엉덩이" },
            { id: 208, category: "7. 신체 / 건강", zh: "腿", py: "tuǐ", mean: "다리" },
            { id: 209, category: "7. 신체 / 건강", zh: "膝盖", py: "xīgài", mean: "무릎" },
            { id: 210, category: "7. 신체 / 건강", zh: "脚", py: "jiǎo", mean: "발" },
            { id: 211, category: "7. 신체 / 건강", zh: "力气", py: "lìqi", mean: "힘, 기운" },
            { id: 212, category: "7. 신체 / 건강", zh: "个子", py: "gèzi", mean: "키, 체격" },
            { id: 213, category: "7. 신체 / 건강", zh: "感冒", py: "gǎnmào", mean: "감기" },
            { id: 214, category: "7. 신체 / 건강", zh: "发烧", py: "fāshāo", mean: "열이 나다" },
            { id: 215, category: "7. 신체 / 건강", zh: "咳嗽", py: "késou", mean: "기침하다" },
            { id: 216, category: "7. 신체 / 건강", zh: "流", py: "liú", mean: "흐르다" },
            { id: 217, category: "7. 신체 / 건강", zh: "鼻涕", py: "bítì", mean: "콧물" },
            { id: 218, category: "7. 신체 / 건강", zh: "拉肚子", py: "lādùzi", mean: "설사하다" },
            { id: 219, category: "7. 신체 / 건강", zh: "疼", py: "téng", mean: "아프다" },

            // --- 8. 동식물 / 띠 ---
            { id: 220, category: "8. 동식물 / 띠", zh: "小狗", py: "xiǎogǒu", mean: "강아지" },
            { id: 221, category: "8. 동식물 / 띠", zh: "属", py: "shǔ", mean: "(띠가) ~이다" },
            { id: 222, category: "8. 동식물 / 띠", zh: "鼠", py: "shǔ", mean: "쥐" },
            { id: 223, category: "8. 동식물 / 띠", zh: "牛", py: "niú", mean: "소" },
            { id: 224, category: "8. 동식물 / 띠", zh: "虎", py: "hǔ", mean: "호랑이" },
            { id: 225, category: "8. 동식물 / 띠", zh: "兔", py: "tù", mean: "토끼" },
            { id: 226, category: "8. 동식물 / 띠", zh: "龙", py: "lóng", mean: "용" },
            { id: 227, category: "8. 동식물 / 띠", zh: "蛇", py: "shé", mean: "뱀" },
            { id: 228, category: "8. 동식물 / 띠", zh: "猴", py: "hóu", mean: "원숭이" },
            { id: 229, category: "8. 동식물 / 띠", zh: "鸡", py: "jī", mean: "닭" },
            { id: 230, category: "8. 동식물 / 띠", zh: "狗", py: "gǒu", mean: "개" },
            { id: 231, category: "8. 동식물 / 띠", zh: "猪", py: "zhū", mean: "돼지" },

            // --- 9. 음식 / 음료 ---
            { id: 232, category: "9. 음식 / 음료", zh: "菜", py: "cài", mean: "요리, 반찬" },
            { id: 233, category: "9. 음식 / 음료", zh: "火锅", py: "huǒguō", mean: "훠궈" },
            { id: 234, category: "9. 음식 / 음료", zh: "烤鸭", py: "kǎoyā", mean: "카오야 (오리구이)" },
            { id: 235, category: "9. 음식 / 음료", zh: "炸酱面", py: "zhájiàngmiàn", mean: "짜장면" },
            { id: 236, category: "9. 음식 / 음료", zh: "麻辣烫", py: "málàtàng", mean: "마라탕" },
            { id: 237, category: "9. 음식 / 음료", zh: "汉堡", py: "hànbǎo", mean: "햄버거" },
            { id: 238, category: "9. 음식 / 음료", zh: "比萨", py: "bǐsà", mean: "피자" },
            { id: 239, category: "9. 음식 / 음료", zh: "炸鸡", py: "zhájī", mean: "치킨" },
            { id: 240, category: "9. 음식 / 음료", zh: "三明治", py: "sānmíngzhì", mean: "샌드위치" },
            { id: 241, category: "9. 음식 / 음료", zh: "牛排", py: "niúpái", mean: "스테이크" },
            { id: 242, category: "9. 음식 / 음료", zh: "方便面", py: "fāngbiànmiàn", mean: "라면" },
            { id: 243, category: "9. 음식 / 음료", zh: "水", py: "shuǐ", mean: "물" },
            { id: 244, category: "9. 음식 / 음료", zh: "矿泉水", py: "kuàngquánshuǐ", mean: "생수" },
            { id: 245, category: "9. 음식 / 음료", zh: "牛奶", py: "niúnǎi", mean: "우유" },
            { id: 246, category: "9. 음식 / 음료", zh: "果汁", py: "guǒzhī", mean: "과일주스" },
            { id: 247, category: "9. 음식 / 음료", zh: "可乐", py: "kělè", mean: "콜라" },
            { id: 248, category: "9. 음식 / 음료", zh: "绿茶", py: "lǜchá", mean: "녹차" },
            { id: 249, category: "9. 음식 / 음료", zh: "啤酒", py: "píjiǔ", mean: "맥주" },

            // --- 10. 취미 / 문화 / 스포츠 ---
            { id: 250, category: "10. 취미 / 스포츠", zh: "电影", py: "diànyǐng", mean: "영화" },
            { id: 251, category: "10. 취미 / 스포츠", zh: "音乐", py: "yīnyuè", mean: "음악" },
            { id: 252, category: "10. 취미 / 스포츠", zh: "钢琴", py: "gāngqín", mean: "피아노" },
            { id: 253, category: "10. 취미 / 스포츠", zh: "吉他", py: "jítā", mean: "기타" },
            { id: 254, category: "10. 취미 / 스포츠", zh: "鼓", py: "gǔ", mean: "북, 드럼" },
            { id: 255, category: "10. 취미 / 스포츠", zh: "小说", py: "xiǎoshuō", mean: "소설" },
            { id: 256, category: "10. 취미 / 스포츠", zh: "节目", py: "jiémù", mean: "프로그램" },
            { id: 257, category: "10. 취미 / 스포츠", zh: "游戏", py: "yóuxì", mean: "게임" },
            { id: 258, category: "10. 취미 / 스포츠", zh: "运动", py: "yùndòng", mean: "운동" },
            { id: 259, category: "10. 취미 / 스포츠", zh: "台球", py: "táiqiú", mean: "당구" },
            { id: 260, category: "10. 취미 / 스포츠", zh: "棒球", py: "bàngqiú", mean: "야구" },
            { id: 261, category: "10. 취미 / 스포츠", zh: "排球", py: "páiqiú", mean: "배구" },
            { id: 262, category: "10. 취미 / 스포츠", zh: "羽毛球", py: "yǔmáoqiú", mean: "배드민턴" },
            { id: 263, category: "10. 취미 / 스포츠", zh: "乒乓球", py: "pīngpāngqiú", mean: "탁구" },
            { id: 264, category: "10. 취미 / 스포츠", zh: "高尔夫球", py: "gāo'ěrfūqiú", mean: "골프" },
            { id: 265, category: "10. 취미 / 스포츠", zh: "滑冰", py: "huábīng", mean: "스케이트" },
            { id: 266, category: "10. 취미 / 스포츠", zh: "滑雪", py: "huáxuě", mean: "스키" },
            { id: 267, category: "10. 취미 / 스포츠", zh: "太极拳", py: "tàijíquán", mean: "태극권" },
            { id: 268, category: "10. 취미 / 스포츠", zh: "跆拳道", py: "táiquándào", mean: "태권도" },
            { id: 269, category: "10. 취미 / 스포츠", zh: "瑜伽", py: "yújiā", mean: "요가" },
            { id: 270, category: "10. 취미 / 스포츠", zh: "马拉松", py: "mǎlāsōng", mean: "마라톤" },

            // --- 11. 동사 / 행동 (일상) ---
            { id: 271, category: "11. 동사 / 행동", zh: "做", py: "zuò", mean: "하다, 만들다" },
            { id: 272, category: "11. 동사 / 행동", zh: "看", py: "kàn", mean: "보다" },
            { id: 273, category: "11. 동사 / 행동", zh: "听", py: "tīng", mean: "듣다" },
            { id: 274, category: "11. 동사 / 행동", zh: "说", py: "shuō", mean: "말하다" },
            { id: 275, category: "11. 동사 / 행동", zh: "读", py: "dú", mean: "읽다" },
            { id: 276, category: "11. 동사 / 행동", zh: "写", py: "xiě", mean: "쓰다" },
            { id: 277, category: "11. 동사 / 행동", zh: "吃", py: "chī", mean: "먹다" },
            { id: 278, category: "11. 동사 / 행동", zh: "喝", py: "hē", mean: "마시다" },
            { id: 279, category: "11. 동사 / 행동", zh: "闻", py: "wén", mean: "냄새 맡다" },
            { id: 280, category: "11. 동사 / 행동", zh: "穿", py: "chuān", mean: "입다, 신다" },
            { id: 281, category: "11. 동사 / 행동", zh: "来", py: "lái", mean: "오다" },
            { id: 282, category: "11. 동사 / 행동", zh: "去", py: "qù", mean: "가다" },
            { id: 283, category: "11. 동사 / 행동", zh: "走", py: "zǒu", mean: "걷다" },
            { id: 284, category: "11. 동사 / 행동", zh: "跑", py: "pǎo", mean: "달리다" },
            { id: 285, category: "11. 동사 / 행동", zh: "坐", py: "zuò", mean: "앉다" },
            { id: 286, category: "11. 동사 / 행동", zh: "站", py: "zhàn", mean: "서다" },
            { id: 287, category: "11. 동사 / 행동", zh: "躺", py: "tǎng", mean: "눕다" },
            { id: 288, category: "11. 동사 / 행동", zh: "进", py: "jìn", mean: "들어가다" },
            { id: 289, category: "11. 동사 / 행동", zh: "出", py: "chū", mean: "나가다" },
            { id: 290, category: "11. 동사 / 행동", zh: "开", py: "kāi", mean: "열다, 켜다" },
            { id: 291, category: "11. 동사 / 행동", zh: "关", py: "guān", mean: "닫다, 끄다" },
            { id: 292, category: "11. 동사 / 행동", zh: "问", py: "wèn", mean: "묻다" },
            { id: 293, category: "11. 동사 / 행동", zh: "回答", py: "huídá", mean: "대답하다" },
            { id: 294, category: "11. 동사 / 행동", zh: "打", py: "dǎ", mean: "치다, 때리다, 하다" },
            { id: 295, category: "11. 동사 / 행동", zh: "给", py: "gěi", mean: "주다" },
            { id: 296, category: "11. 동사 / 행동", zh: "买", py: "mǎi", mean: "사다" },
            { id: 297, category: "11. 동사 / 행동", zh: "学", py: "xué", mean: "배우다" },
            { id: 298, category: "11. 동사 / 행동", zh: "教", py: "jiāo", mean: "가르치다" },
            { id: 299, category: "11. 동사 / 행동", zh: "爱", py: "ài", mean: "사랑하다" },
            { id: 300, category: "11. 동사 / 행동", zh: "喜欢", py: "xǐhuan", mean: "좋아하다" },
            { id: 301, category: "11. 동사 / 행동", zh: "想", py: "xiǎng", mean: "생각하다, ~하고 싶다" },
            { id: 302, category: "11. 동사 / 행동", zh: "觉得", py: "juéde", mean: "느끼다, 생각하다" },
            { id: 303, category: "11. 동사 / 행동", zh: "会", py: "huì", mean: "할 줄 알다" },
            { id: 304, category: "11. 동사 / 행동", zh: "可以", py: "kěyǐ", mean: "할 수 있다" },
            { id: 305, category: "11. 동사 / 행동", zh: "要", py: "yào", mean: "원하다, ~해야 한다" },
            { id: 306, category: "11. 동사 / 행동", zh: "注意", py: "zhùyì", mean: "주의하다" },
            { id: 307, category: "11. 동사 / 행동", zh: "见", py: "jiàn", mean: "만나다" },

            // --- 11-2. 동사 / 행동 (복합어) ---
            { id: 308, category: "11. 동사 / 행동", zh: "起床", py: "qǐchuáng", mean: "일어나다" },
            { id: 309, category: "11. 동사 / 행동", zh: "睡觉", py: "shuìjiào", mean: "자다" },
            { id: 310, category: "11. 동사 / 행동", zh: "上班", py: "shàngbān", mean: "출근하다" },
            { id: 311, category: "11. 동사 / 행동", zh: "下班", py: "xiàbān", mean: "퇴근하다" },
            { id: 312, category: "11. 동사 / 행동", zh: "加班", py: "jiābān", mean: "야근하다" },
            { id: 313, category: "11. 동사 / 행동", zh: "开会", py: "kāihuì", mean: "회의하다" },
            { id: 314, category: "11. 동사 / 행동", zh: "吃饭", py: "chīfàn", mean: "밥을 먹다" },
            { id: 315, category: "11. 동사 / 행동", zh: "做菜", py: "zuòcài", mean: "요리하다" },
            { id: 316, category: "11. 동사 / 행동", zh: "看电影", py: "kàn diànyǐng", mean: "영화를 보다" },
            { id: 317, category: "11. 동사 / 행동", zh: "写字", py: "xiězì", mean: "글씨를 쓰다" },
            { id: 318, category: "11. 동사 / 행동", zh: "画画儿", py: "huàhuàr", mean: "그림을 그리다" },
            { id: 319, category: "11. 동사 / 행동", zh: "唱歌", py: "chànggē", mean: "노래하다" },
            { id: 320, category: "11. 동사 / 행동", zh: "跳舞", py: "tiàowǔ", mean: "춤추다" },
            { id: 321, category: "11. 동사 / 행동", zh: "玩儿", py: "wánr", mean: "놀다" },
            { id: 322, category: "11. 동사 / 행동", zh: "踢足球", py: "tī zúqiú", mean: "축구하다" },
            { id: 323, category: "11. 동사 / 행동", zh: "打篮球", py: "dǎ lánqiú", mean: "농구하다" },
            { id: 324, category: "11. 동사 / 행동", zh: "游泳", py: "yóuyǒng", mean: "수영하다" },
            { id: 325, category: "11. 동사 / 행동", zh: "爬山", py: "páshān", mean: "등산하다" },
            { id: 326, category: "11. 동사 / 행동", zh: "钓鱼", py: "diàoyú", mean: "낚시하다" },
            { id: 327, category: "11. 동사 / 행동", zh: "下围棋", py: "xià wéiqí", mean: "바둑을 두다" },
            { id: 328, category: "11. 동사 / 행동", zh: "打电话", py: "dǎ diànhuà", mean: "전화하다" },
            { id: 329, category: "11. 동사 / 행동", zh: "接电话", py: "jiē diànhuà", mean: "전화를 받다" },
            { id: 330, category: "11. 동사 / 행동", zh: "拍照", py: "pāizhào", mean: "사진을 찍다" },
            { id: 331, category: "11. 동사 / 행동", zh: "开车", py: "kāichē", mean: "운전하다" },
            { id: 332, category: "11. 동사 / 행동", zh: "打扫", py: "dǎsǎo", mean: "청소하다" },
            { id: 333, category: "11. 동사 / 행동", zh: "参加", py: "cānjiā", mean: "참가하다" },
            { id: 334, category: "11. 동사 / 행동", zh: "报名", py: "bàomíng", mean: "신청하다" },
            { id: 335, category: "11. 동사 / 행동", zh: "结婚", py: "jiéhūn", mean: "결혼하다" },
            { id: 336, category: "11. 동사 / 행동", zh: "工作", py: "gōngzuò", mean: "일하다" },
            { id: 337, category: "11. 동사 / 행동", zh: "学习", py: "xuéxí", mean: "학습하다" },

            // --- 12. 형용사 / 감정 / 상태 ---
            { id: 338, category: "12. 형용사 / 상태", zh: "高兴", py: "gāoxìng", mean: "기쁘다" },
            { id: 339, category: "12. 형용사 / 상태", zh: "开心", py: "kāixīn", mean: "즐겁다" },
            { id: 340, category: "12. 형용사 / 상태", zh: "幸福", py: "xìngfú", mean: "행복하다" },
            { id: 341, category: "12. 형용사 / 상태", zh: "难过", py: "nánguò", mean: "슬프다" },
            { id: 342, category: "12. 형용사 / 상태", zh: "紧张", py: "jǐnzhāng", mean: "긴장하다" },
            { id: 343, category: "12. 형용사 / 상태", zh: "无聊", py: "wúliáo", mean: "지루하다" },
            { id: 344, category: "12. 형용사 / 상태", zh: "舒服", py: "shūfu", mean: "편안하다" },
            { id: 345, category: "12. 형용사 / 상태", zh: "忙", py: "máng", mean: "바쁘다" },
            { id: 346, category: "12. 형용사 / 상태", zh: "累", py: "lèi", mean: "피곤하다" },
            { id: 347, category: "12. 형용사 / 상태", zh: "困", py: "kùn", mean: "졸리다" },
            { id: 348, category: "12. 형용사 / 상태", zh: "饿", py: "è", mean: "배고프다" },
            { id: 349, category: "12. 형용사 / 상태", zh: "饱", py: "bǎo", mean: "배부르다" },
            { id: 350, category: "12. 형용사 / 상태", zh: "渴", py: "kě", mean: "목마르다" },
            { id: 351, category: "12. 형용사 / 상태", zh: "高", py: "gāo", mean: "높다" },
            { id: 352, category: "12. 형용사 / 상태", zh: "矮", py: "ǎi", mean: "낮다" },
            { id: 353, category: "12. 형용사 / 상태", zh: "贵", py: "guì", mean: "비싸다" },
            { id: 354, category: "12. 형용사 / 상태", zh: "便宜", py: "piányi", mean: "싸다" },
            { id: 355, category: "12. 형용사 / 상태", zh: "干净", py: "gānjìng", mean: "깨끗하다" },
            { id: 356, category: "12. 형용사 / 상태", zh: "脏", py: "zāng", mean: "더럽다" },
            { id: 357, category: "12. 형용사 / 상태", zh: "难", py: "nán", mean: "어렵다" },
            { id: 358, category: "12. 형용사 / 상태", zh: "容易", py: "róngyì", mean: "쉽다" },
            { id: 359, category: "12. 형용사 / 상태", zh: "坏", py: "huài", mean: "나쁘다, 고장나다" },
            { id: 360, category: "12. 형용사 / 상태", zh: "辣", py: "là", mean: "맵다" },
            { id: 361, category: "12. 형용사 / 상태", zh: "帅", py: "shuài", mean: "멋지다" },
            { id: 362, category: "12. 형용사 / 상태", zh: "漂亮", py: "piàoliang", mean: "예쁘다" },
            { id: 363, category: "12. 형용사 / 상태", zh: "可爱", py: "kě'ài", mean: "귀엽다" },
            { id: 364, category: "12. 형용사 / 상태", zh: "好吃", py: "hǎochī", mean: "맛있다" },
            { id: 365, category: "12. 형용사 / 상태", zh: "不错", py: "búcuò", mean: "훌륭하다" },
            { id: 366, category: "12. 형용사 / 상태", zh: "有意思", py: "yǒuyìsi", mean: "재미있다" },
            { id: 367, category: "12. 형용사 / 상태", zh: "一样", py: "yíyàng", mean: "같다" },
            { id: 368, category: "12. 형용사 / 상태", zh: "了不起", py: "liǎobuqǐ", mean: "대단하다" },
            { id: 369, category: "12. 형용사 / 상태", zh: "厉害", py: "lìhai", mean: "대단하다, 심하다" },
            { id: 370, category: "12. 형용사 / 상태", zh: "骄傲", py: "jiāo'ào", mean: "자랑스럽다" },

            // --- 13. 부사 / 양사 / 기타 ---
            { id: 371, category: "13. 기타 품사", zh: "很", py: "hěn", mean: "매우" },
            { id: 372, category: "13. 기타 품사", zh: "非常", py: "fēicháng", mean: "대단히" },
            { id: 373, category: "13. 기타 품사", zh: "特别", py: "tèbié", mean: "특별히" },
            { id: 374, category: "13. 기타 품사", zh: "最", py: "zuì", mean: "가장" },
            { id: 375, category: "13. 기타 품사", zh: "真", py: "zhēn", mean: "정말" },
            { id: 376, category: "13. 기타 품사", zh: "挺", py: "tǐng", mean: "꽤" },
            { id: 377, category: "13. 기타 품사", zh: "不太", py: "bú tài", mean: "별로 ~않다" },
            { id: 378, category: "13. 기타 품사", zh: "也", py: "yě", mean: "~도" },
            { id: 379, category: "13. 기타 품사", zh: "都", py: "dōu", mean: "모두, 다" },
            { id: 380, category: "13. 기타 품사", zh: "还", py: "hái", mean: "아직, 여전히" },
            { id: 381, category: "13. 기타 품사", zh: "还是", py: "háishì", mean: "아니면, 여전히" },
            { id: 382, category: "13. 기타 품사", zh: "已经", py: "yǐjīng", mean: "이미" },
            { id: 383, category: "13. 기타 품사", zh: "最近", py: "zuìjìn", mean: "최근" },
            { id: 384, category: "13. 기타 품사", zh: "天天", py: "tiāntiān", mean: "매일" },
            { id: 385, category: "13. 기타 품사", zh: "一起", py: "yìqǐ", mean: "같이" },
            { id: 386, category: "13. 기타 품사", zh: "这样", py: "zhèyàng", mean: "이렇게" },
            { id: 387, category: "13. 기타 품사", zh: "一点儿", py: "yìdiǎnr", mean: "조금" },
            { id: 388, category: "13. 기타 품사", zh: "怎么", py: "zěnme", mean: "어떻게" },
            { id: 389, category: "13. 기타 품사", zh: "怎么样", py: "zěnmeyàng", mean: "어때요" },
            { id: 390, category: "13. 기타 품사", zh: "行", py: "xíng", mean: "좋다, 가능하다" },
            { id: 391, category: "13. 기타 품사", zh: "老样子", py: "lǎoyàngzi", mean: "여전하다" },
            { id: 392, category: "13. 기타 품사", zh: "当然", py: "dāngrán", mean: "당연하다" },
            { id: 393, category: "13. 기타 품사", zh: "哪里", py: "nǎli", mean: "별말씀을요" },
            { id: 394, category: "13. 기타 품사", zh: "过奖", py: "guòjiǎng", mean: "과찬이다" },
            { id: 395, category: "13. 기타 품사", zh: "没什么", py: "méi shénme", mean: "별일 아니다" },
            { id: 396, category: "13. 기타 품사", zh: "谢谢", py: "xièxie", mean: "감사합니다" },
            { id: 397, category: "13. 기타 품사", zh: "为", py: "wèi", mean: "~을 위하여" },
            { id: 398, category: "13. 기타 품사", zh: "两", py: "liǎng", mean: "둘, 2" },
            { id: 399, category: "13. 기타 품사", zh: "几", py: "jǐ", mean: "몇" },
            { id: 400, category: "13. 기타 품사", zh: "个", py: "gè", mean: "개, 명 (범용 양사)" },
            { id: 401, category: "13. 기타 품사", zh: "口", py: "kǒu", mean: "식구를 세는 양사" },
            { id: 402, category: "13. 기타 품사", zh: "台", py: "tái", mean: "대 (기계 양사)" },
            { id: 403, category: "13. 기타 품사", zh: "件", py: "jiàn", mean: "벌, 건 (옷, 일)" },
            { id: 404, category: "13. 기타 품사", zh: "条", py: "tiáo", mean: "마리, 가닥" },
            { id: 405, category: "13. 기타 품사", zh: "本", py: "běn", mean: "권" },
            { id: 406, category: "13. 기타 품사", zh: "杯", py: "bēi", mean: "잔, 컵" },
            { id: 407, category: "13. 기타 품사", zh: "只", py: "zhī", mean: "마리, 개" },
            { id: 408, category: "13. 기타 품사", zh: "次", py: "cì", mean: "번, 차례" },
            { id: 409, category: "13. 기타 품사", zh: "遍", py: "biàn", mean: "번 (처음부터 끝까지)" },
            { id: 410, category: "13. 기타 품사", zh: "趟", py: "tàng", mean: "번 (왕복)" },
            { id: 411, category: "13. 기타 품사", zh: "的", py: "de", mean: "~의" },
            { id: 412, category: "13. 기타 품사", zh: "得", py: "de", mean: "~하는 정도가 ~하다" },
            { id: 413, category: "13. 기타 품사", zh: "过", py: "guo", mean: "~한 적이 있다" },
            { id: 414, category: "13. 기타 품사", zh: "了", py: "le", mean: "~했다" },
            { id: 415, category: "13. 기타 품사", zh: "吧", py: "ba", mean: "~하자, ~지?" },
            { id: 416, category: "13. 기타 품사", zh: "吗", py: "ma", mean: "~입니까?" },
            { id: 417, category: "13. 기타 품사", zh: "呢", py: "ne", mean: "~는요?" },
            { id: 418, category: "13. 기타 품사", zh: "中文", py: "Zhōngwén", mean: "중국어" },
            { id: 419, category: "13. 기타 품사", zh: "英文", py: "Yīngwén", mean: "영어" },
            { id: 420, category: "13. 기타 품사", zh: "生意", py: "shēngyi", mean: "장사, 사업" },
            { id: 421, category: "13. 기타 품사", zh: "贸易", py: "màoyì", mean: "무역" },
            { id: 422, category: "13. 기타 품사", zh: "工资", py: "gōngzī", mean: "월급" },
            { id: 423, category: "13. 기타 품사", zh: "价格", py: "jiàgé", mean: "가격" },
            { id: 424, category: "13. 기타 품사", zh: "性格", py: "xìnggé", mean: "성격" },
            { id: 425, category: "13. 기타 품사", zh: "信", py: "xìn", mean: "편지" },
            { id: 426, category: "13. 기타 품사", zh: "钱", py: "qián", mean: "돈" },
            { id: 427, category: "13. 기타 품사", zh: "零钱", py: "língqián", mean: "잔돈" }
        ]
    },
    // 두 번째 주제: HSK 2급
    "hsk2": {
        title: "HSK 2급",
        words: [
            // --- 1. 대명사 / 의문사 ---
            { id: 1, category: "1. 대명사/의문사", zh: "大家", py: "dàjiā", mean: "모두, 여러분" },
            { id: 2, category: "1. 대명사/의문사", zh: "您", py: "nín", mean: "당신 (존칭)" },
            { id: 3, category: "1. 대명사/의문사", zh: "它", py: "tā", mean: "그것 (사물/동물)" },
            { id: 4, category: "1. 대명사/의문사", zh: "为什么", py: "wèishénme", mean: "왜, 어째서" },
            { id: 5, category: "1. 대명사/의문사", zh: "每", py: "měi", mean: "매, 마다" },

            // --- 2. 명사 (사람/가족/직업) ---
            { id: 6, category: "2. 사람/가족", zh: "哥哥", py: "gēge", mean: "형, 오빠" },
            { id: 7, category: "2. 사람/가족", zh: "弟弟", py: "dìdi", mean: "남동생" },
            { id: 8, category: "2. 사람/가족", zh: "妹妹", py: "mèimei", mean: "여동생" },
            { id: 9, category: "2. 사람/가족", zh: "丈夫", py: "zhàngfu", mean: "남편" },
            { id: 10, category: "2. 사람/가족", zh: "妻子", py: "qīzi", mean: "아내" },
            { id: 11, category: "2. 사람/가족", zh: "孩子", py: "háizi", mean: "아이, 자녀" },
            { id: 12, category: "2. 사람/가족", zh: "男人", py: "nánrén", mean: "남자" },
            { id: 13, category: "2. 사람/가족", zh: "女人", py: "nǚrén", mean: "여자" },
            { id: 14, category: "2. 사람/가족", zh: "服务员", py: "fúwùyuán", mean: "종업원, 서비스원" },

            // --- 3. 명사 (사물/장소/시간) ---
            { id: 15, category: "3. 사물/장소", zh: "报纸", py: "bàozhǐ", mean: "신문" },
            { id: 16, category: "3. 사물/장소", zh: "宾馆", py: "bīnguǎn", mean: "호텔, 여관" },
            { id: 17, category: "3. 사물/장소", zh: "房间", py: "fángjiān", mean: "방" },
            { id: 18, category: "3. 사물/장소", zh: "教室", py: "jiàoshì", mean: "교실" },
            { id: 19, category: "3. 사물/장소", zh: "机场", py: "jīchǎng", mean: "공항" },
            { id: 20, category: "3. 사물/장소", zh: "路", py: "lù", mean: "길, 도로" },
            { id: 21, category: "3. 사물/장소", zh: "门", py: "mén", mean: "문" },
            { id: 22, category: "3. 사물/장소", zh: "票", py: "piào", mean: "표, 티켓" },
            { id: 23, category: "3. 사물/장소", zh: "铅笔", py: "qiānbǐ", mean: "연필" },
            { id: 24, category: "3. 사물/장소", zh: "手表", py: "shǒubiǎo", mean: "손목시계" },
            { id: 25, category: "3. 사물/장소", zh: "手机", py: "shǒujī", mean: "휴대폰" },
            { id: 26, category: "3. 사물/장소", zh: "事情", py: "shìqing", mean: "일, 사건" },
            { id: 27, category: "3. 사물/장소", zh: "意思", py: "yìsi", mean: "의미, 뜻" },
            { id: 28, category: "3. 사물/장소", zh: "课", py: "kè", mean: "수업, 과" },
            { id: 29, category: "3. 사물/장소", zh: "题", py: "tí", mean: "문제, 제목" },
            { id: 30, category: "3. 사물/장소", zh: "雪", py: "xuě", mean: "눈(Snow)" },
            { id: 31, category: "3. 사물/장소", zh: "药", py: "yào", mean: "약" },
            { id: 32, category: "3. 사물/장소", zh: "公共汽车", py: "gōnggòng qìchē", mean: "버스" },
            { id: 33, category: "3. 사물/장소", zh: "自行车", py: "zìxíngchē", mean: "자전거" },
            { id: 34, category: "3. 사물/장소", zh: "船", py: "chuán", mean: "배, 선박" },

            // --- 4. 명사 (음식/방위) ---
            { id: 35, category: "4. 음식/방위", zh: "鸡蛋", py: "jīdàn", mean: "계란" },
            { id: 36, category: "4. 음식/방위", zh: "咖啡", py: "kāfēi", mean: "커피" },
            { id: 37, category: "4. 음식/방위", zh: "面条", py: "miàntiáo", mean: "국수" },
            { id: 38, category: "4. 음식/방위", zh: "牛奶", py: "niúnǎi", mean: "우유" },
            { id: 39, category: "4. 음식/방위", zh: "羊肉", py: "yángròu", mean: "양고기" },
            { id: 40, category: "4. 음식/방위", zh: "西瓜", py: "xīguā", mean: "수박" },
            { id: 41, category: "4. 음식/방위", zh: "鱼", py: "yú", mean: "물고기, 생선" },
            { id: 42, category: "4. 음식/방위", zh: "左边", py: "zuǒbiān", mean: "왼쪽" },
            { id: 43, category: "4. 음식/방위", zh: "右边", py: "yòubiān", mean: "오른쪽" },
            { id: 44, category: "4. 음식/방위", zh: "旁边", py: "pángbiān", mean: "옆" },
            { id: 45, category: "4. 음식/방위", zh: "外面", py: "wàimiàn", mean: "밖, 바깥" },

            // --- 5. 동사 (행동/동작) ---
            { id: 46, category: "5. 동사 (동작)", zh: "穿", py: "chuān", mean: "입다, 신다" },
            { id: 47, category: "5. 동사 (동작)", zh: "洗", py: "xǐ", mean: "씻다, 빨다" },
            { id: 48, category: "5. 동사 (동작)", zh: "笑", py: "xiào", mean: "웃다" },
            { id: 49, category: "5. 동사 (동작)", zh: "哭", py: "kū", mean: "울다" },
            { id: 50, category: "5. 동사 (동작)", zh: "找", py: "zhǎo", mean: "찾다, 거슬러 주다" },
            { id: 51, category: "5. 동사 (동작)", zh: "给", py: "gěi", mean: "주다" },
            { id: 52, category: "5. 동사 (동작)", zh: "送", py: "sòng", mean: "보내다, 선물하다" },
            { id: 53, category: "5. 동사 (동작)", zh: "卖", py: "mài", mean: "팔다" },
            { id: 54, category: "5. 동사 (동작)", zh: "让", py: "ràng", mean: "양보하다, ~하게 하다" },
            { id: 55, category: "5. 동사 (동작)", zh: "进", py: "jìn", mean: "들어가다, 들어오다" },
            { id: 56, category: "5. 동사 (동작)", zh: "出", py: "chū", mean: "나가다, 나오다" },
            { id: 57, category: "5. 동사 (동작)", zh: "到", py: "dào", mean: "도착하다" },
            { id: 58, category: "5. 동사 (동작)", zh: "走", py: "zǒu", mean: "걷다, 가다" },
            { id: 59, category: "5. 동사 (동작)", zh: "等", py: "děng", mean: "기다리다" },
            { id: 60, category: "5. 동사 (동작)", zh: "起床", py: "qǐchuáng", mean: "일어나다, 기상하다" },
            { id: 61, category: "5. 동사 (동작)", zh: "上班", py: "shàngbān", mean: "출근하다" },
            { id: 62, category: "5. 동사 (동작)", zh: "休息", py: "xiūxi", mean: "쉬다, 휴식하다" },

            // --- 6. 동사 (인지/소통/기타) ---
            { id: 63, category: "6. 동사 (소통/기타)", zh: "知道", py: "zhīdào", mean: "알다" },
            { id: 64, category: "6. 동사 (소통/기타)", zh: "懂", py: "dǒng", mean: "이해하다, 알다" },
            { id: 65, category: "6. 동사 (소통/기타)", zh: "觉得", py: "juéde", mean: "~라고 생각하다, 느끼다" },
            { id: 66, category: "6. 동사 (소통/기타)", zh: "希望", py: "xīwàng", mean: "희망하다, 바라다" },
            { id: 67, category: "6. 동사 (소통/기타)", zh: "准备", py: "zhǔnbèi", mean: "준비하다" },
            { id: 68, category: "6. 동사 (소통/기타)", zh: "开始", py: "kāishǐ", mean: "시작하다" },
            { id: 69, category: "6. 동사 (소통/기타)", zh: "完", py: "wán", mean: "끝나다, 마치다" },
            { id: 70, category: "6. 동사 (소통/기타)", zh: "帮助", py: "bāngzhù", mean: "돕다" },
            { id: 71, category: "6. 동사 (소통/기타)", zh: "告诉", py: "gàosu", mean: "알려주다, 말하다" },
            { id: 72, category: "6. 동사 (소통/기타)", zh: "回答", py: "huídá", mean: "대답하다" },
            { id: 73, category: "6. 동사 (소통/기타)", zh: "介绍", py: "jièshào", mean: "소개하다" },
            { id: 74, category: "6. 동사 (소통/기타)", zh: "欢迎", py: "huānyíng", mean: "환영하다" },
            { id: 75, category: "6. 동사 (소통/기타)", zh: "生病", py: "shēngbìng", mean: "병에 걸리다" },
            { id: 76, category: "6. 동사 (소통/기타)", zh: "可能", py: "kěnéng", mean: "가능하다, 아마도" },
            { id: 77, category: "6. 동사 (소통/기타)", zh: "可以", py: "kěyǐ", mean: "~할 수 있다, 해도 좋다" },
            { id: 78, category: "6. 동사 (소통/기타)", zh: "要", py: "yào", mean: "원하다, ~해야 한다" },

            // --- 7. 여가 / 스포츠 ---
            { id: 79, category: "7. 여가/스포츠", zh: "唱歌", py: "chànggē", mean: "노래하다" },
            { id: 80, category: "7. 여가/스포츠", zh: "跳舞", py: "tiàowǔ", mean: "춤추다" },
            { id: 81, category: "7. 여가/스포츠", zh: "旅游", py: "lǚyóu", mean: "여행하다" },
            { id: 82, category: "7. 여가/스포츠", zh: "玩", py: "wán", mean: "놀다, 장난하다" },
            { id: 83, category: "7. 여가/스포츠", zh: "运动", py: "yùndòng", mean: "운동하다" },
            { id: 84, category: "7. 여가/스포츠", zh: "跑步", py: "pǎobù", mean: "달리기하다" },
            { id: 85, category: "7. 여가/스포츠", zh: "游泳", py: "yóuyǒng", mean: "수영하다" },
            { id: 86, category: "7. 여가/스포츠", zh: "打篮球", py: "dǎ lánqiú", mean: "농구하다" },
            { id: 87, category: "7. 여가/스포츠", zh: "踢足球", py: "tī zúqiú", mean: "축구하다" },

            // --- 8. 형용사 (상태/성질) ---
            { id: 88, category: "8. 형용사", zh: "好", py: "hǎo", mean: "좋다" },
            { id: 89, category: "8. 형용사", zh: "好吃", py: "hǎochī", mean: "맛있다" },
            { id: 90, category: "8. 형용사", zh: "大", py: "dà", mean: "크다" },
            { id: 91, category: "8. 형용사", zh: "小", py: "xiǎo", mean: "작다" },
            { id: 92, category: "8. 형용사", zh: "长", py: "cháng", mean: "길다" },
            { id: 93, category: "8. 형용사", zh: "高", py: "gāo", mean: "높다, 키가 크다" },
            { id: 94, category: "8. 형용사", zh: "新", py: "xīn", mean: "새롭다" },
            { id: 95, category: "8. 형용사", zh: "贵", py: "guì", mean: "비싸다" },
            { id: 96, category: "8. 형용사", zh: "便宜", py: "piányi", mean: "싸다, 저렴하다" },
            { id: 97, category: "8. 형용사", zh: "远", py: "yuǎn", mean: "멀다" },
            { id: 98, category: "8. 형용사", zh: "近", py: "jìn", mean: "가깝다" },
            { id: 99, category: "8. 형용사", zh: "快", py: "kuài", mean: "빠르다" },
            { id: 100, category: "8. 형용사", zh: "慢", py: "màn", mean: "느리다" },
            { id: 101, category: "8. 형용사", zh: "忙", py: "máng", mean: "바쁘다" },
            { id: 102, category: "8. 형용사", zh: "累", py: "lèi", mean: "피곤하다" },
            { id: 103, category: "8. 형용사", zh: "快乐", py: "kuàilè", mean: "즐겁다, 행복하다" },
            { id: 104, category: "8. 형용사", zh: "对", py: "duì", mean: "맞다, 옳다" },
            { id: 105, category: "8. 형용사", zh: "错", py: "cuò", mean: "틀리다, 잘못되다" },
            { id: 106, category: "8. 형용사", zh: "晴", py: "qíng", mean: "맑다" },
            { id: 107, category: "8. 형용사", zh: "阴", py: "yīn", mean: "흐리다" },

            // --- 9. 색상 ---
            { id: 108, category: "9. 색상", zh: "红", py: "hóng", mean: "붉다, 빨갛다" },
            { id: 109, category: "9. 색상", zh: "白", py: "bái", mean: "희다, 하얗다" },
            { id: 110, category: "9. 색상", zh: "黑", py: "hēi", mean: "검다, 까맣다" },

            // --- 10. 부사 ---
            { id: 111, category: "10. 부사", zh: "非常", py: "fēicháng", mean: "매우, 대단히" },
            { id: 112, category: "10. 부사", zh: "真", py: "zhēn", mean: "정말, 진짜로" },
            { id: 113, category: "10. 부사", zh: "最", py: "zuì", mean: "가장, 제일" },
            { id: 114, category: "10. 부사", zh: "也", py: "yě", mean: "~도 또한" },
            { id: 115, category: "10. 부사", zh: "还", py: "hái", mean: "아직, 여전히, 더" },
            { id: 116, category: "10. 부사", zh: "就", py: "jiù", mean: "곧, 바로" },
            { id: 117, category: "10. 부사", zh: "再", py: "zài", mean: "다시, 또 (미래)" },
            { id: 118, category: "10. 부사", zh: "正在", py: "zhèngzài", mean: "마침 ~하고 있다" },
            { id: 119, category: "10. 부사", zh: "已经", py: "yǐjīng", mean: "이미, 벌써" },
            { id: 120, category: "10. 부사", zh: "别", py: "bié", mean: "~하지 마라" },

            // --- 11. 전치사 / 접속사 ---
            { id: 121, category: "11. 전치사/접속사", zh: "比", py: "bǐ", mean: "~보다 (비교)" },
            { id: 122, category: "11. 전치사/접속사", zh: "从", py: "cóng", mean: "~부터 (기점)" },
            { id: 123, category: "11. 전치사/접속사", zh: "对", py: "duì", mean: "~에게, ~에 대하여" },
            { id: 124, category: "11. 전치사/접속사", zh: "离", py: "lí", mean: "~에서 떨어져 있다" },
            { id: 125, category: "11. 전치사/접속사", zh: "向", py: "xiàng", mean: "~을 향하여" },
            { id: 126, category: "11. 전치사/접속사", zh: "因为", py: "yīnwèi", mean: "왜냐하면, ~때문에" },
            { id: 127, category: "11. 전치사/접속사", zh: "所以", py: "suǒyǐ", mean: "그래서" },
            { id: 128, category: "11. 전치사/접속사", zh: "但是", py: "dànshì", mean: "그러나, 하지만" },

            // --- 12. 수사 / 양사 / 조사 ---
            { id: 129, category: "12. 수사/양사/조사", zh: "两", py: "liǎng", mean: "둘, 2 (양사 앞)" },
            { id: 130, category: "12. 수사/양사/조사", zh: "百", py: "bǎi", mean: "백 (100)" },
            { id: 131, category: "12. 수사/양사/조사", zh: "千", py: "qiān", mean: "천 (1,000)" },
            { id: 132, category: "12. 수사/양사/조사", zh: "第一", py: "dì-yī", mean: "제일, 첫째" },
            { id: 133, category: "12. 수사/양사/조사", zh: "次", py: "cì", mean: "번, 차례 (동량사)" },
            { id: 134, category: "12. 수사/양사/조사", zh: "件", py: "jiàn", mean: "벌, 건 (옷/일 양사)" },
            { id: 135, category: "12. 수사/양사/조사", zh: "公斤", py: "gōngjīn", mean: "킬로그램 (kg)" },
            { id: 136, category: "12. 수사/양사/조사", zh: "元", py: "yuán", mean: "원 (위안, 화폐 단위)" },
            { id: 137, category: "12. 수사/양사/조사", zh: "吧", py: "ba", mean: "~하자, ~지? (청유/추측)" },
            { id: 138, category: "12. 수사/양사/조사", zh: "得", py: "de", mean: "~하는 정도가 ~하다 (정도보어)" },
            { id: 139, category: "12. 수사/양사/조사", zh: "过", py: "guo", mean: "~한 적이 있다 (경험)" },
            { id: 140, category: "12. 수사/양사/조사", zh: "着", py: "zhe", mean: "~하고 있다 (상태 지속)" },

            // --- 13. 기타 기초 명사 (시간/날짜) ---
            { id: 141, category: "13. 기타 기초 단어", zh: "早上", py: "zǎoshang", mean: "아침" },
            { id: 142, category: "13. 기타 기초 단어", zh: "晚上", py: "wǎnshang", mean: "저녁, 밤" },
            { id: 143, category: "13. 기타 기초 단어", zh: "去年", py: "qùnián", mean: "작년" },
            { id: 144, category: "13. 기타 기초 단어", zh: "今年", py: "jīnnián", mean: "올해" },
            { id: 145, category: "13. 기타 기초 단어", zh: "明年", py: "míngnián", mean: "내년" },
            { id: 146, category: "13. 기타 기초 단어", zh: "生日", py: "shēngrì", mean: "생일" },
            { id: 147, category: "13. 기타 기초 단어", zh: "时间", py: "shíjiān", mean: "시간" },
            { id: 148, category: "13. 기타 기초 단어", zh: "小时", py: "xiǎoshí", mean: "시간 (Hour)" },
            { id: 149, category: "13. 기타 기초 단어", zh: "分钟", py: "fēnzhōng", mean: "분 (Minute)" },
            { id: 150, category: "13. 기타 기초 단어", zh: "问题", py: "wèntí", mean: "문제, 질문" }
        ]
    },
    // 세 번째 주제: HSK 3급
    "hsk3": {
        title: "HSK 3급",
        words: [
            // --- 1. 명사 (사람/가족/직업) ---
            { id: 1, category: "1. 사람/직업", zh: "阿姨", py: "āyí", mean: "이모, 아주머니" },
            { id: 2, category: "1. 사람/직업", zh: "叔叔", py: "shūshu", mean: "삼촌, 아저씨" },
            { id: 3, category: "1. 사람/직업", zh: "爷爷", py: "yéye", mean: "할아버지" },
            { id: 4, category: "1. 사람/직업", zh: "奶奶", py: "nǎinai", mean: "할머니" },
            { id: 5, category: "1. 사람/직업", zh: "邻居", py: "línjū", mean: "이웃" },
            { id: 6, category: "1. 사람/직업", zh: "同事", py: "tóngshì", mean: "직장 동료" },
            { id: 7, category: "1. 사람/직업", zh: "经理", py: "jīnglǐ", mean: "매니저, 사장" },
            { id: 8, category: "1. 사람/직업", zh: "客人", py: "kèrén", mean: "손님" },
            { id: 9, category: "1. 사람/직업", zh: "司机", py: "sījī", mean: "기사, 운전사" },
            { id: 10, category: "1. 사람/직업", zh: "校长", py: "xiàozhǎng", mean: "교장 총장" },

            // --- 2. 명사 (장소/공간) ---
            { id: 11, category: "2. 장소/공간", zh: "银行", py: "yínháng", mean: "은행" },
            { id: 12, category: "2. 장소/공간", zh: "超市", py: "chāoshì", mean: "슈퍼마켓" },
            { id: 13, category: "2. 장소/공간", zh: "公园", py: "gōngyuán", mean: "공원" },
            { id: 14, category: "2. 장소/공간", zh: "图书馆", py: "túshūguǎn", mean: "도서관" },
            { id: 15, category: "2. 장소/공간", zh: "办公室", py: "bàngōngshì", mean: "사무실" },
            { id: 16, category: "2. 장소/공간", zh: "洗手间", py: "xǐshǒujiān", mean: "화장실" },
            { id: 17, category: "2. 장소/공간", zh: "电梯", py: "diàntī", mean: "엘리베이터" },
            { id: 18, category: "2. 장소/공간", zh: "街道", py: "jiēdào", mean: "거리, 길거리" },
            { id: 19, category: "2. 장소/공간", zh: "城市", py: "chéngshì", mean: "도시" },
            { id: 20, category: "2. 장소/공간", zh: "地方", py: "dìfang", mean: "장소, 곳" },

            // --- 3. 명사 (사물/생활용품) ---
            { id: 21, category: "3. 사물/생활용품", zh: "护照", py: "hùzhào", mean: "여권" },
            { id: 22, category: "3. 사물/생활용품", zh: "信用卡", py: "xìnyòngkǎ", mean: "신용카드" },
            { id: 23, category: "3. 사물/생활용품", zh: "钱包", py: "qiánbāo", mean: "지갑" },
            { id: 24, category: "3. 사물/생활용품", zh: "行李箱", py: "xínglǐxiāng", mean: "캐리어, 트렁크" },
            { id: 25, category: "3. 사물/생활용품", zh: "伞", py: "sǎn", mean: "우산" },
            { id: 26, category: "3. 사물/생활용품", zh: "鞋", py: "xié", mean: "신발" },
            { id: 27, category: "3. 사물/생활용품", zh: "裙子", py: "qúnzi", mean: "치마" },
            { id: 28, category: "3. 사물/생활용품", zh: "裤子", py: "kùzi", mean: "바지" },
            { id: 29, category: "3. 사물/생활용품", zh: "衬衫", py: "chènshān", mean: "셔츠" },
            { id: 30, category: "3. 사물/생활용품", zh: "词典", py: "cídiǎn", mean: "사전" },
            { id: 31, category: "3. 사물/생활용품", zh: "菜单", py: "càidān", mean: "메뉴판" },
            { id: 32, category: "3. 사물/생활용품", zh: "空调", py: "kōngtiáo", mean: "에어컨" },
            { id: 33, category: "3. 사물/생활용품", zh: "冰箱", py: "bīngxiāng", mean: "냉장고" },
            { id: 34, category: "3. 사물/생활용품", zh: "照片", py: "zhàopiàn", mean: "사진" },
            { id: 35, category: "3. 사물/생활용품", zh: "照相机", py: "zhàoxiàngjī", mean: "카메라" },

            // --- 4. 명사 (시간/계절/추상) ---
            { id: 36, category: "4. 시간/계절/추상", zh: "季节", py: "jìjié", mean: "계절" },
            { id: 37, category: "4. 시간/계절/추상", zh: "春", py: "chūn", mean: "봄" },
            { id: 38, category: "4. 시간/계절/추상", zh: "夏", py: "xià", mean: "여름" },
            { id: 39, category: "4. 시간/계절/추상", zh: "秋", py: "qiū", mean: "가을" },
            { id: 40, category: "4. 시간/계절/추상", zh: "冬", py: "dōng", mean: "겨울" },
            { id: 41, category: "4. 시간/계절/추상", zh: "周末", py: "zhōumò", mean: "주말" },
            { id: 42, category: "4. 시간/계절/추상", zh: "节日", py: "jiérì", mean: "명절, 기념일" },
            { id: 43, category: "4. 시간/계절/추상", zh: "历史", py: "lìshǐ", mean: "역사" },
            { id: 44, category: "4. 시간/계절/추상", zh: "故事", py: "gùshi", mean: "이야기" },
            { id: 45, category: "4. 시간/계절/추상", zh: "声音", py: "shēngyīn", mean: "소리, 목소리" },
            { id: 46, category: "4. 시간/계절/추상", zh: "爱好", py: "àihào", mean: "취미" },
            { id: 47, category: "4. 시간/계절/추상", zh: "习惯", py: "xíguàn", mean: "습관" },
            { id: 48, category: "4. 시간/계절/추상", zh: "新闻", py: "xīnwén", mean: "뉴스" },
            { id: 49, category: "4. 시간/계절/추상", zh: "会议", py: "huìyì", mean: "회의" },
            { id: 50, category: "4. 시간/계절/추상", zh: "机会", py: "jīhuì", mean: "기회" },

            // --- 5. 동사 (신체/물리적 동작) ---
            { id: 51, category: "5. 동사 (물리적 동작)", zh: "搬", py: "bān", mean: "옮기다, 이사하다" },
            { id: 52, category: "5. 동사 (물리적 동작)", zh: "帮忙", py: "bāngmáng", mean: "도와주다" },
            { id: 53, category: "5. 동사 (물리적 동작)", zh: "打扫", py: "dǎsǎo", mean: "청소하다" },
            { id: 54, category: "5. 동사 (물리적 동작)", zh: "洗澡", py: "xǐzǎo", mean: "목욕하다, 샤워하다" },
            { id: 55, category: "5. 동사 (물리적 동작)", zh: "刷牙", py: "shuāyá", mean: "양치질하다" },
            { id: 56, category: "5. 동사 (물리적 동작)", zh: "拿", py: "ná", mean: "들다, 쥐다, 가져오다" },
            { id: 57, category: "5. 동사 (물리적 동작)", zh: "放", py: "fàng", mean: "놓다, 두다" },
            { id: 58, category: "5. 동사 (물리적 동작)", zh: "换", py: "huàn", mean: "바꾸다, 교환하다" },
            { id: 59, category: "5. 동사 (물리적 동작)", zh: "借", py: "jiè", mean: "빌리다, 빌려주다" },
            { id: 60, category: "5. 동사 (물리적 동작)", zh: "还", py: "huán", mean: "돌려주다, 반납하다" },
            { id: 61, category: "5. 동사 (물리적 동작)", zh: "爬山", py: "páshān", mean: "등산하다" },
            { id: 62, category: "5. 동사 (물리적 동작)", zh: "骑", py: "qí", mean: "(자전거/말 등을) 타다" },
            { id: 63, category: "5. 동사 (물리적 동작)", zh: "起飞", py: "qǐfēi", mean: "이륙하다" },
            { id: 64, category: "5. 동사 (물리적 동작)", zh: "上网", py: "shàngwǎng", mean: "인터넷을 하다" },
            { id: 65, category: "5. 동사 (물리적 동작)", zh: "发烧", py: "fāshāo", mean: "열이 나다" },

            // --- 6. 동사 (상태/인지/소통) ---
            { id: 66, category: "6. 동사 (인지/소통)", zh: "参加", py: "cānjiā", mean: "참가하다" },
            { id: 67, category: "6. 동사 (인지/소통)", zh: "举行", py: "jǔxíng", mean: "개최하다, 열다" },
            { id: 68, category: "6. 동사 (인지/소통)", zh: "发现", py: "fāxiàn", mean: "발견하다, 알아차리다" },
            { id: 69, category: "6. 동사 (인지/소통)", zh: "解决", py: "jiějué", mean: "해결하다" },
            { id: 70, category: "6. 동사 (인지/소통)", zh: "离开", py: "líkāi", mean: "떠나다, 벗어나다" },
            { id: 71, category: "6. 동사 (인지/소통)", zh: "聊天", py: "liáotiān", mean: "수다 떨다, 채팅하다" },
            { id: 72, category: "6. 동사 (인지/소통)", zh: "必须", py: "bìxū", mean: "반드시 ~해야 한다" },
            { id: 73, category: "6. 동사 (인지/소통)", zh: "需要", py: "xūyào", mean: "필요하다, 요구되다" },
            { id: 74, category: "6. 동사 (인지/소통)", zh: "变化", py: "biànhuà", mean: "변화하다" },
            { id: 75, category: "6. 동사 (인지/소통)", zh: "表示", py: "biǎoshì", mean: "표시하다, 나타내다" },
            { id: 76, category: "6. 동사 (인지/소통)", zh: "担心", py: "dānxīn", mean: "걱정하다" },
            { id: 77, category: "6. 동사 (인지/소통)", zh: "放心", py: "fàngxīn", mean: "안심하다" },
            { id: 78, category: "6. 동사 (인지/소통)", zh: "记得", py: "jìde", mean: "기억하고 있다" },
            { id: 79, category: "6. 동사 (인지/소통)", zh: "忘记", py: "wàngjì", mean: "잊다, 까먹다" },
            { id: 80, category: "6. 동사 (인지/소통)", zh: "决定", py: "juédìng", mean: "결정하다" },
            { id: 81, category: "6. 동사 (인지/소통)", zh: "了解", py: "liǎojiě", mean: "자세히 알다, 이해하다" },
            { id: 82, category: "6. 동사 (인지/소통)", zh: "明白", py: "míngbai", mean: "명백히 알다, 이해하다" },
            { id: 83, category: "6. 동사 (인지/소통)", zh: "认为", py: "rènwéi", mean: "여기다, 생각하다" },
            { id: 84, category: "6. 동사 (인지/소통)", zh: "相信", py: "xiāngxìn", mean: "믿다, 신뢰하다" },
            { id: 85, category: "6. 동사 (인지/소통)", zh: "选择", py: "xuǎnzé", mean: "선택하다" },
            { id: 86, category: "6. 동사 (인지/소통)", zh: "同意", py: "tóngyì", mean: "동의하다" },
            { id: 87, category: "6. 동사 (인지/소통)", zh: "以为", py: "yǐwéi", mean: "~인 줄 알았다 (착각)" },
            { id: 88, category: "6. 동사 (인지/소통)", zh: "遇到", py: "yùdào", mean: "마주치다, 조우하다" },
            { id: 89, category: "6. 동사 (인지/소통)", zh: "照顾", py: "zhàogù", mean: "돌보다, 보살피다" },
            { id: 90, category: "6. 동사 (인지/소통)", zh: "注意", py: "zhùyì", mean: "주의하다, 조심하다" },
            { id: 91, category: "6. 동사 (인지/소통)", zh: "祝", py: "zhù", mean: "축하하다, 기원하다" },
            { id: 92, category: "6. 동사 (인지/소통)", zh: "要求", py: "yāoqiú", mean: "요구하다" },
            { id: 93, category: "6. 동사 (인지/소통)", zh: "影响", py: "yǐngxiǎng", mean: "영향을 주다" },

            // --- 7. 형용사 (외모/상태) ---
            { id: 94, category: "7. 형용사", zh: "胖", py: "pàng", mean: "뚱뚱하다" },
            { id: 95, category: "7. 형용사", zh: "瘦", py: "shòu", mean: "마르다" },
            { id: 96, category: "7. 형용사", zh: "矮", py: "ǎi", mean: "키가 작다" },
            { id: 97, category: "7. 형용사", zh: "旧", py: "jiù", mean: "낡다, 오래되다" },
            { id: 98, category: "7. 형용사", zh: "聪明", py: "cōngming", mean: "똑똑하다" },
            { id: 99, category: "7. 형용사", zh: "可爱", py: "kě'ài", mean: "귀엽다" },
            { id: 100, category: "7. 형용사", zh: "干净", py: "gānjìng", mean: "깨끗하다" },
            { id: 101, category: "7. 형용사", zh: "安静", py: "ānjìng", mean: "조용하다" },
            { id: 102, category: "7. 형용사", zh: "安全", py: "ānquán", mean: "안전하다" },
            { id: 103, category: "7. 형용사", zh: "奇怪", py: "qíguài", mean: "이상하다, 기이하다" },
            { id: 104, category: "7. 형용사", zh: "清楚", py: "qīngchu", mean: "분명하다, 뚜렷하다" },
            { id: 105, category: "7. 형용사", zh: "舒服", py: "shūfu", mean: "편안하다, 기분 좋다" },
            { id: 106, category: "7. 형용사", zh: "容易", py: "róngyì", mean: "쉽다" },
            { id: 107, category: "7. 형용사", zh: "简单", py: "jiǎndān", mean: "간단하다" },
            { id: 108, category: "7. 형용사", zh: "甜", py: "tián", mean: "달다" },
            { id: 109, category: "7. 형용사", zh: "饱", py: "bǎo", mean: "배부르다" },
            { id: 110, category: "7. 형용사", zh: "渴", py: "kě", mean: "목마르다" },
            { id: 111, category: "7. 형용사", zh: "饿", py: "è", mean: "배고프다" },
            { id: 112, category: "7. 형용사", zh: "难过", py: "nánguò", mean: "슬프다, 괴롭다" },
            { id: 113, category: "7. 형용사", zh: "生气", py: "shēngqì", mean: "화나다" },
            { id: 114, category: "7. 형용사", zh: "新鲜", py: "xīnxiān", mean: "신선하다" },
            { id: 115, category: "7. 형용사", zh: "相同", py: "xiāngtóng", mean: "같다, 동일하다" },

            // --- 8. 부사 ---
            { id: 116, category: "8. 부사", zh: "才", py: "cái", mean: "비로소, 겨우" },
            { id: 117, category: "8. 부사", zh: "必须", py: "bìxū", mean: "반드시" },
            { id: 118, category: "8. 부사", zh: "当然", py: "dāngrán", mean: "당연히" },
            { id: 119, category: "8. 부사", zh: "几乎", py: "jīhū", mean: "거의" },
            { id: 120, category: "8. 부사", zh: "经常", py: "jīngcháng", mean: "자주, 늘" },
            { id: 121, category: "8. 부사", zh: "马上", py: "mǎshàng", mean: "즉시, 바로" },
            { id: 122, category: "8. 부사", zh: "其实", py: "qíshí", mean: "사실은, 실제로는" },
            { id: 123, category: "8. 부사", zh: "突然", py: "tūrán", mean: "갑자기" },
            { id: 124, category: "8. 부사", zh: "先", py: "xiān", mean: "먼저, 우선" },
            { id: 125, category: "8. 부사", zh: "一直", py: "yìzhí", mean: "계속, 줄곧" },
            { id: 126, category: "8. 부사", zh: "总是", py: "zǒngshì", mean: "항상, 늘" },
            { id: 127, category: "8. 부사", zh: "终于", py: "zhōngyú", mean: "마침내, 드디어" },
            { id: 128, category: "8. 부사", zh: "特别", py: "tèbié", mean: "특별히, 아주" },
            { id: 129, category: "8. 부사", zh: "更", py: "gèng", mean: "더욱, 한층 더" },
            { id: 130, category: "8. 부사", zh: "极", py: "jí", mean: "극히, 몹시 (~极了)" },

            // --- 9. 전치사/접속사/기타 ---
            { id: 131, category: "9. 접속사/전치사/기타", zh: "或者", py: "huòzhě", mean: "혹은, 아니면 (평서문)" },
            { id: 132, category: "9. 접속사/전치사/기타", zh: "还是", py: "háishì", mean: "아니면 (의문문)" },
            { id: 133, category: "9. 접속사/전치사/기타", zh: "为了", py: "wèile", mean: "~을 위하여" },
            { id: 134, category: "9. 접속사/전치사/기타", zh: "除了", py: "chúle", mean: "~을 제외하고" },
            { id: 135, category: "9. 접속사/전치사/기타", zh: "关于", py: "guānyú", mean: "~에 관하여" },
            { id: 136, category: "9. 접속사/전치사/기타", zh: "如果", py: "rúguǒ", mean: "만약 ~라면" },
            { id: 137, category: "9. 접속사/전치사/기타", zh: "虽然", py: "suīrán", mean: "비록 ~일지라도" },
            { id: 138, category: "9. 접속사/전치사/기타", zh: "只有", py: "zhǐyǒu", mean: "오직 ~해야만" },
            { id: 139, category: "9. 접속사/전치사/기타", zh: "然后", py: "ránhòu", mean: "그러고 나서" },
            { id: 140, category: "9. 접속사/전치사/기타", zh: "根据", py: "gēnjù", mean: "~에 근거하여" },
            
            // --- 10. 양사 ---
            { id: 141, category: "10. 양사", zh: "把", py: "bǎ", mean: "자루 (의자/우산 등 손잡이)" },
            { id: 142, category: "10. 양사", zh: "双", py: "shuāng", mean: "켤레, 쌍 (신발/젓가락 등)" },
            { id: 143, category: "10. 양사", zh: "辆", py: "liàng", mean: "대 (자동차/자전거 등)" },
            { id: 144, category: "10. 양사", zh: "条", py: "tiáo", mean: "마리, 벌 (길고 가느다란 것)" },
            { id: 145, category: "10. 양사", zh: "张", py: "zhāng", mean: "장 (종이/침대/책상 등)" },
            { id: 146, category: "10. 양사", zh: "瓶", py: "píng", mean: "병 (음료수 등)" },
            { id: 147, category: "10. 양사", zh: "层", py: "céng", mean: "층, 겹" },
            { id: 148, category: "10. 양사", zh: "段", py: "duàn", mean: "단락, 구간" },
            { id: 149, category: "10. 양사", zh: "种", py: "zhǒng", mean: "종류" },
            { id: 150, category: "10. 양사", zh: "角", py: "jiǎo", mean: "자오 (화폐 단위, 0.1위안)" }
        ]
    },
    // 다섯 번째 주제: HSK 4급
    "hsk4": {
        title: "HSK 4급",
        words: [
            // --- 1. 추상 명사 / 사회 ---
            { id: 1, category: "1. 추상 명사 / 사회", zh: "爱情", py: "àiqíng", mean: "사랑, 애정" },
            { id: 2, category: "1. 추상 명사 / 사회", zh: "标准", py: "biāozhǔn", mean: "표준, 기준" },
            { id: 3, category: "1. 추상 명사 / 사회", zh: "不仅", py: "bùjǐn", mean: "뿐만 아니라" },
            { id: 4, category: "1. 추상 명사 / 사회", zh: "材料", py: "cáiliào", mean: "재료, 데이터" },
            { id: 5, category: "1. 추상 명사 / 사회", zh: "法律", py: "fǎlǜ", mean: "법률" },
            { id: 6, category: "1. 추상 명사 / 사회", zh: "工资", py: "gōngzī", mean: "급여, 월급" },
            { id: 7, category: "1. 추상 명사 / 사회", zh: "好处", py: "hǎochu", mean: "장점, 이로운 점" },
            { id: 8, category: "1. 추상 명사 / 사회", zh: "机会", py: "jīhuì", mean: "기회" },
            { id: 9, category: "1. 추상 명사 / 사회", zh: "经验", py: "jīngyàn", mean: "경험" },
            { id: 10, category: "1. 추상 명사 / 사회", zh: "空气", py: "kōngqì", mean: "공기" },
            { id: 11, category: "1. 추상 명사 / 사회", zh: "困难", py: "kùnnan", mean: "곤란, 어려움" },
            { id: 12, category: "1. 추상 명사 / 사회", zh: "礼모", py: "lǐmào", mean: "예의" },
            { id: 13, category: "1. 추상 명사 / 사회", zh: "能力", py: "nénglì", mean: "능력" },
            { id: 14, category: "1. 추상 명사 / 사회", zh: "题目", py: "tímù", mean: "제목, 주제" },
            { id: 15, category: "1. 추상 명사 / 사회", zh: "艺术", py: "yìshù", mean: "예술" },

            // --- 2. 동사 (심리/사고) ---
            { id: 16, category: "2. 동사 (심리/사고)", zh: "怀疑", py: "huáiyí", mean: "의심하다" },
            { id: 17, category: "2. 동사 (심리/사고)", zh: "解释", py: "jiěshì", mean: "설명하다, 해명하다" },
            { id: 18, category: "2. 동사 (심리/사고)", zh: "考虑", py: "kǎolǜ", mean: "고려하다, 생각하다" },
            { id: 19, category: "2. 동사 (심리/사고)", zh: "其实", py: "qíshí", mean: "사실은" },
            { id: 20, category: "2. 동사 (심리/사고)", zh: "认为", py: "rènwéi", mean: "여기다, 생각하다" },
            { id: 21, category: "2. 동사 (심리/사고)", zh: "适合", py: "shìhé", mean: "적합하다, 알맞다" },
            { id: 22, category: "2. 동사 (심리/사고)", zh: "同意", py: "tóngyì", mean: "동의하다" },
            { id: 23, category: "2. 동사 (심리/사고)", zh: "羡慕", py: "xiànmù", mean: "부러워하다" },
            { id: 24, category: "2. 동사 (심리/사고)", zh: "相信", py: "xiāngxìn", mean: "믿다" },
            { id: 25, category: "2. 동사 (심리/사고)", zh: "允许", py: "yǔnxǔ", mean: "허가하다, 허락하다" },

            // --- 3. 동사 (행동/변화) ---
            { id: 26, category: "3. 동사 (행동/변화)", zh: "安排", py: "ānpái", mean: "배치하다, 안배하다" },
            { id: 27, category: "3. 동사 (행동/변화)", zh: "保护", py: "bǎohù", mean: "보호하다" },
            { id: 28, category: "3. 동사 (행동/변화)", zh: "保证", py: "bǎozhèng", mean: "보증하다" },
            { id: 29, category: "3. 동사 (행동/변화)", zh: "报名", py: "bàomíng", mean: "등록하다, 신청하다" },
            { id: 30, category: "3. 동사 (행동/변화)", zh: "毕业", py: "bìyè", mean: "졸업하다" },
            { id: 31, category: "3. 동사 (행동/변화)", zh: "打扮", py: "dǎban", mean: "차려입다, 꾸미다" },
            { id: 32, category: "3. 동사 (행동/변화)", zh: "道歉", py: "dàoqiàn", mean: "사과하다" },
            { id: 33, category: "3. 동사 (행동/변화)", zh: "发展", py: "fāzhǎn", mean: "발전하다" },
            { id: 34, category: "3. 동사 (행동/변화)", zh: "反对", py: "fǎnduì", mean: "반대하다" },
            { id: 35, category: "3. 동사 (행동/변화)", zh: "改变", py: "gǎibiàn", mean: "변화시키다" },
            { id: 36, category: "3. 동사 (행동/변화)", zh: "管理", py: "guǎnlǐ", mean: "관리하다" },
            { id: 37, category: "3. 동사 (행동/변화)", zh: "坚持", py: "jiānchí", mean: "견지하다, 지속하다" },
            { id: 38, category: "3. 동사 (행동/변화)", zh: "积累", py: "jīlěi", mean: "쌓다, 누적하다" },
            { id: 39, category: "3. 동사 (행동/변화)", zh: "拒绝", py: "jùjué", mean: "거절하다" },
            { id: 40, category: "3. 동사 (행동/변화)", zh: "流泪", py: "liú lèi", mean: "눈물을 흘리다" },

            // --- 4. 형용사 (성격/상태) ---
            { id: 41, category: "4. 형용사", zh: "笨", py: "bèn", mean: "어리석다, 둔하다" },
            { id: 42, category: "4. 형용사", zh: "诚实", py: "chéngshí", mean: "정직하다" },
            { id: 43, category: "4. 형용사", zh: "粗心", py: "cūxīn", mean: "덜렁대다, 소홀하다" },
            { id: 44, category: "4. 형용사", zh: "得意", py: "déyì", mean: "의기양양하다" },
            { id: 45, category: "4. 형용사", zh: "烦恼", py: "fánnǎo", mean: "번뇌하다, 걱정스럽다" },
            { id: 46, category: "4. 형용사", zh: "复杂", py: "fùzá", mean: "복잡하다" },
            { id: 47, category: "4. 형용사", zh: "害羞", py: "hàixiū", mean: "부끄러워하다" },
            { id: 48, category: "4. 형용사", zh: "后悔", py: "hòuhuǐ", mean: "후회하다" },
            { id: 49, category: "4. 형용사", zh: "骄傲", py: "jiāo'ào", mean: "거만하다, 자랑스럽다" },
            { id: 50, category: "4. 형용사", zh: "紧张", py: "jǐnzhāng", mean: "긴장하다" },
            { id: 51, category: "4. 형용사", zh: "精彩", py: "jīngcǎi", mean: "화려하다, 훌륭하다" },
            { id: 52, category: "4. 형용사", zh: "浪漫", py: "làngmàn", mean: "낭만적이다" },
            { id: 53, category: "4. 형용사", zh: "热闹", py: "rènao", mean: "번화하다, 시끌벅적하다" },
            { id: 54, category: "4. 형용사", zh: "伤心", py: "shāngxīn", mean: "슬퍼하다" },
            { id: 55, category: "4. 형용사", zh: "幽默", py: "yōumò", mean: "유머러스하다" },

            // --- 5. 부사 (정도/범위/시간) ---
            { id: 56, category: "5. 부사", zh: "大概", py: "dàgài", mean: "대개, 아마" },
            { id: 57, category: "5. 부사", zh: "到底", py: "dàodǐ", mean: "도대체, 결국" },
            { id: 58, category: "5. 부사", zh: "反而", py: "fǎn'ér", mean: "반대로, 도리어" },
            { id: 59, category: "5. 부사", zh: "刚才", py: "gāngcái", mean: "방금" },
            { id: 60, category: "5. 부사", zh: "果然", py: "guǒrán", mean: "과연" },
            { id: 61, category: "5. 부사", zh: "忽然", py: "hūrán", mean: "갑자기" },
            { id: 62, category: "5. 부사", zh: "互相", py: "hùxiāng", mean: "서로" },
            { id: 63, category: "5. 부사", zh: "即使", py: "jíshǐ", mean: "설령 ~일지라도" },
            { id: 64, category: "5. 부사", zh: "竟然", py: "jìngrán", mean: "뜻밖에도" },
            { id: 65, category: "5. 부사", zh: "偶尔", py: "ǒu'ěr", mean: "어쩌다, 가끔" },
            { id: 66, category: "5. 부사", zh: "千万", py: "qiānwàn", mean: "부디, 제발" },
            { id: 67, category: "5. 부사", zh: "稍微", py: "shāowēi", mean: "약간, 조금" },
            { id: 68, category: "5. 부사", zh: "顺便", py: "shùnbiàn", mean: "기왕 하는 김에" },
            { id: 69, category: "5. 부사", zh: "也许", py: "yěxǔ", mean: "아마도" },
            { id: 70, category: "5. 부사", zh: "尤其", py: "yóuqí", mean: "특히" },

            // --- 6. 접속사 / 기타 ---
            { id: 71, category: "6. 접속사 / 기타", zh: "否则", py: "fǒuzé", mean: "그렇지 않으면" },
            { id: 72, category: "6. 접속사 / 기타", zh: "既然", py: "jìrán", mean: "이미 ~한 이상" },
            { id: 73, category: "6. 접속사 / 기타", zh: "例如", py: "lìrú", mean: "예를 들어" },
            { id: 74, category: "6. 접속사 / 기타", zh: "难道", py: "nándào", mean: "설마 ~하겠는가" },
            { id: 75, category: "6. 접속사 / 기타", zh: "所以", py: "suǒyǐ", mean: "그래서" },
            { id: 76, category: "6. 접속사 / 기타", zh: "不管", py: "bùguǎn", mean: "~에 관계없이" },
            { id: 77, category: "6. 접속사 / 기타", zh: "因此", py: "yīncǐ", mean: "그러므로" },
            { id: 78, category: "6. 접속사 / 기타", zh: "只要", py: "zhǐyào", mean: "오직 ~하기만 하면" },
            { id: 79, category: "6. 접속사 / 기타", zh: "注意", py: "zhùyì", mean: "주의하다" },
            { id: 80, category: "6. 접속사 / 기타", zh: "总是", py: "zǒngshì", mean: "늘, 언제나" },

            // --- (중략: 필수 단어 150개를 위한 추가 목록) ---
            { id: 81, category: "3. 동사 (행동/변화)", zh: "擦", py: "cā", mean: "닦다" },
            { id: 82, category: "3. 동사 (행동/변화)", zh: "猜", py: "cāi", mean: "추측하다" },
            { id: 83, category: "3. 동사 (행동/변화)", zh: "传", py: "chuán", mean: "전하다" },
            { id: 84, category: "3. 동사 (행동/변화)", zh: "存", py: "cún", mean: "보관하다" },
            { id: 85, category: "3. 동사 (행동/변화)", zh: "丢", py: "diū", mean: "잃어버리다" },
            { id: 86, category: "3. 동사 (행동/변화)", zh: "符合", py: "fúhé", mean: "부합하다" },
            { id: 87, category: "3. 동사 (행동/변화)", zh: "复印", py: "fùyìn", mean: "복사하다" },
            { id: 88, category: "3. 동사 (행동/변화)", zh: "估计", py: "gūjì", mean: "추정하다" },
            { id: 89, category: "3. 동사 (행동/변화)", zh: "逛", py: "guàng", mean: "돌아다니다" },
            { id: 90, category: "3. 동사 (행동/변화)", zh: "合格", py: "hégé", mean: "합격하다" },
            { id: 91, category: "4. 형용사", zh: "厚", py: "hòu", mean: "두껍다" },
            { id: 92, category: "4. 형용사", zh: "活跃", py: "huóyuè", mean: "활발하다" },
            { id: 93, category: "1. 추상 명사 / 사회", zh: "基础", py: "jīchǔ", mean: "기초" },
            { id: 94, category: "1. 추상 명사 / 사회", zh: "奖金", py: "jiǎngjīn", mean: "상금, 보너스" },
            { id: 95, category: "3. 동사 (행동/변화)", zh: "降低", py: "jiàngdī", mean: "낮추다" },
            { id: 96, category: "1. 추상 명사 / 사회", zh: "交通", py: "jiāotōng", mean: "교통" },
            { id: 97, category: "3. 동사 (행동/변화)", zh: "接受", py: "jiēshòu", mean: "받아들이다" },
            { id: 98, category: "3. 동사 (행동/변화)", zh: "节约", py: "jiéyuē", mean: "절약하다" },
            { id: 99, category: "4. 형용사", zh: "紧张", py: "jǐnzhāng", mean: "긴장하다" },
            { id: 100, category: "3. 동사 (행동/변화)", zh: "进行", py: "jìnxíng", mean: "진행하다" },
            { id: 101, category: "1. 추상 명사 / 사회", zh: "警察", py: "jǐngchá", mean: "경찰" },
            { id: 102, category: "4. 형용사", zh: "竟然", py: "jìngrán", mean: "뜻밖에도" },
            { id: 103, category: "3. 동사 (행동/변화)", zh: "禁止", py: "jìnzhǐ", mean: "금지하다" },
            { id: 104, category: "1. 추상 명사 / 사회", zh: "看法", py: "kànfǎ", mean: "견해, 관점" },
            { id: 105, category: "4. 형용사", zh: "可怜", py: "kělián", mean: "가련하다" },
            { id: 106, category: "4. 형용사", zh: "可惜", py: "kěxī", mean: "아쉽다" },
            { id: 107, category: "4. 형용사", zh: "肯定", py: "kěndìng", mean: "긍정하다, 확실히" },
            { id: 108, category: "1. 추상 명사 / 사회", zh: "垃圾桶", py: "lājītǒng", mean: "쓰레기통" },
            { id: 109, category: "4. 형용사", zh: "懒", py: "lǎn", mean: "게으르다" },
            { id: 110, category: "4. 형용사", zh: "凉快", py: "liángkuai", mean: "시원하다" },
            { id: 111, category: "3. 동사 (행동/변화)", zh: "联系", py: "liánxì", mean: "연락하다" },
            { id: 112, category: "4. 형용사", zh: "亮", py: "liàng", mean: "밝다" },
            { id: 113, category: "1. 추상 명사 / 사회", zh: "律师", py: "lǜshī", mean: "변호사" },
            { id: 114, category: "4. 형용사", zh: "麻烦", py: "máfan", mean: "번거롭다" },
            { id: 115, category: "4. 형용사", zh: "满", py: "mǎn", mean: "가득 차다" },
            { id: 116, category: "4. 형용사", zh: "满意", py: "mǎnyì", mean: "만족하다" },
            { id: 117, category: "1. 추상 명사 / 사회", zh: "密码", py: "mìmǎ", mean: "비밀번호" },
            { id: 118, category: "1. 추상 명사 / 사회", zh: "免费", py: "miǎnfèi", mean: "무료" },
            { id: 119, category: "1. 추상 명사 / 사회", zh: "民族", py: "mínzú", mean: "민족" },
            { id: 120, category: "1. 추상 명사 / 사회", zh: "目的", py: "mùdì", mean: "목적" },
            { id: 121, category: "4. 형용사", zh: "耐心", py: "nàixīn", mean: "인내심이 있다" },
            { id: 122, category: "4. 형용사", zh: "难受", py: "nánshòu", mean: "괴롭다" },
            { id: 123, category: "1. 추상 명사 / 사회", zh: "农村", py: "nóngcūn", mean: "농촌" },
            { id: 124, category: "3. 동사 (행동/변화)", zh: "弄", py: "nòng", mean: "하다, 만들다" },
            { id: 125, category: "4. 형용사", zh: "暖和", py: "nuǎnhuo", mean: "따뜻하다" },
            { id: 126, category: "3. 동사 (행동/변화)", zh: "排队", py: "páiduì", mean: "줄을 서다" },
            { id: 127, category: "3. 동사 (행동/변화)", zh: "排列", py: "páiliè", mean: "배열하다" },
            { id: 128, category: "3. 동사 (행동/변화)", zh: "判断", py: "pànduàn", mean: "판단하다" },
            { id: 129, category: "3. 동사 (행동/변화)", zh: "陪", py: "péi", mean: "동반하다" },
            { id: 130, category: "3. 동사 (행동/변화)", zh: "批评", py: "pīpíng", mean: "비평하다" },
            { id: 131, category: "1. 추상 명사 / 사회", zh: "皮肤", py: "pífū", mean: "피부" },
            { id: 132, category: "1. 추상 명사 / 사회", zh: "脾气", py: "píqi", mean: "성미, 성격" },
            { id: 133, category: "3. 동사 (행동/변화)", zh: "骗", py: "piàn", mean: "속이다" },
            { id: 134, category: "1. 추상 명사 / 사회", zh: "乒乓球", py: "pīngpāngqiú", mean: "탁구" },
            { id: 135, category: "1. 추상 명사 / 사회", zh: "瓶子", py: "píngzi", mean: "병" },
            { id: 136, category: "4. 형용사", zh: "普遍", py: "pǔbiàn", mean: "보편적이다" },
            { id: 137, category: "3. 동사 (행동/변화)", zh: "敲", py: "qiāo", mean: "두드리다" },
            { id: 138, category: "1. 추상 명사 / 사회", zh: "签证", py: "qiānzhèng", mean: "비자" },
            { id: 139, category: "1. 추상 명사 / 사회", zh: "巧克力", py: "qiǎokèlì", mean: "초콜릿" },
            { id: 140, category: "1. 추상 명사 / 사회", zh: "亲戚", py: "qīnqi", mean: "친척" },
            { id: 141, category: "4. 형용사", zh: "轻", py: "qīng", mean: "가볍다" },
            { id: 142, category: "4. 형용사", zh: "穷", py: "qióng", mean: "가난하다" },
            { id: 143, category: "3. 동사 (행동/변화)", zh: "区别", py: "qūbié", mean: "구별하다" },
            { id: 144, category: "4. 형용사", zh: "缺点", py: "quēdiǎn", mean: "결점" },
            { id: 145, category: "3. 동사 (행동/변화)", zh: "确实", py: "quèshí", mean: "확실하다" },
            { id: 146, category: "4. 형용사", zh: "热闹", py: "rènao", mean: "번화하다" },
            { id: 147, category: "1. 추상 명사 / 사회", zh: "人民币", py: "rénmínbì", mean: "인민폐" },
            { id: 148, category: "4. 형용사", zh: "软", py: "ruǎn", mean: "부드럽다" },
            { id: 149, category: "3. 동사 (행동/변화)", zh: "散步", py: "sànbù", mean: "산책하다" },
            { id: 150, category: "3. 동사 (행동/변화)", zh: "稍微", py: "shāowēi", mean: "약간" }
        ]
    }
}